### ISSUE TITLE
Whitelist/Blacklist - email blacklist is by passed when it is sent with more than 2 normal recipient email!

### ISSUE THREAD

**Issue by somono168** [mailwatch/MailWatch#255]
First let me describe about my email environment:
- Supposed that i have domain "me.com" for global email and "int.me.com" for local email.
- and I have a fews mailing list: global@me.com, managers@me.com, branches@me.com.
- I create a blacklist from="default" to="global@me.com", and whitelist from="me.com" to="global@me.com". So the allemail from "int.me.com" can not send email to global@me.com.

The blacklist blocked perfectly with sender test@int.me.com when there are two recipients "global@me.com, test01@me.com". However, the blacklist does not work at all when there are more than two recipients "global@me.com, test01@me.com, test02@me.com".

It look like if there are more than two good recipients among the blocked recipient, the blacklist will not work.

My Question is:
Is there anyway to absolutely block the email even there are some normal recipients are included?

Thank you,
##

**Comment by asuweb** [comment]
Are we sure this is actually a Mailwatch bug and not a mailscanner bug/feature?

I think this is related to the whitelist/blacklist logic in mailscanner.

In Message.pm
 ```
# Do the whitelist check before the blacklist check.
  # If anyone whitelists it, then everyone gets the message.
  # If no-one has whitelisted it, then consider the blacklist.
  $iswhitelisted = 0;
  my $maxrecips = MailScanner::Config::Value('whitelistmaxrecips');
  $maxrecips = 999999 unless $maxrecips;


```

**Comment by somono168** [comment]
Thank asuweb,

I will test again based on your information to know if it really Mailscanner bug/features or a Mailwatch Bug.

**Comment by Skywalker-11** [comment]
This should to be a bug in MailWatch because there are no applied whitelist entries. So it should look into the blacklist and find the block rule. 

Maybe we are matching every subdomain for a white/blacklist entry so that an entry for bla.com also apply to fuu.bla.com, bla.fuu.bla.com etc.?

**Comment by somono168** [comment]
I have tested again with scenario like this:

1. In Mailwatch B/W List:
- from: example.com , to: test@example.com => WhiteList
- from: default , to: test@example.com => BlackList

2. Test sending email from test@gmail.com
- test 1 with 5 recipients: (test@example.com, test@gmail.com, test1@gmail.com, test@yahoo.com, test2@yahoo.com) => the result: the email from test@gmail.com got blacklist in MailWatch
- test 2 with 4 recipient: (test@example.com, test2@example.com, test3@example.com, test@yahoo.com) => the result: I can send email to all recipients.

So the blacklist filter won't work if there are 2 recipient , which are not in blacklist filter, from same domain.

As asuweb and Skywalker-11 suggest Message.pm and SQLBlackWhiteList.pm file that might cause this bug, and i tried to look into the file, but i cannot figure it out where should i change in that code. Sorry my programming skill is very poor. So if you figure out what should be changed in the code, please write your new code here. and I will test it.

Thank you.

**Comment by Skywalker-11** [comment]
I can reproduce the problem.
Mail matches no whitelist entry but in blacklist the `return 1 if $BlackWhite->{$todomain}{'default'};` is triggered
In Mailwatch it is correctly shown as blacklisted but the mail is still delivered. So it looks like MailScanner is somehow ignoring our blacklist here.

**Comment by Skywalker-11** [comment]
Is there  a documentation what mailscanner expects us to return or can anyone tell me where it is called by MailScanner? I can't find it in the source.

**Comment by Skywalker-11** [comment]
Now it gets crazy: 
If we have the correct setting in MailScanner.conf for `Spam Actions` with the store option instead of deliver MailWatch-Blacklist is not triggered. BUT if deliver is set MailWatch-Blacklist is correctly triggered. But this doesn't help because even it is noticed as spam by MailWatch mailscanner still delivers it...

**Comment by Skywalker-11** [comment]
It works if we use `Spam Actions = store-spam ...`

**Comment by Skywalker-11** [comment]
@somono168 can you try using `Spam Actions = store-spam` in the MailScanner.conf and verify that the mails are filtered correctly?

**Comment by somono168** [comment]
Sorry late .. i am not at office this few days. I will test it on Monday
next week and i will let you know. Thank you for your help :)

On 4 Feb 2017 7:28 p.m., "Michael Pietsch" <notifications@github.com> wrote:

@somono168 <https://github.com/somono168> can you try using Spam Actions =
store-spam in the MailScanner.conf and verify that the mails are filtered
correctly?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mailwatch/1.2.0/issues/255#issuecomment-277442405>, or mute
the thread

**Comment by somono168** [comment]
Hi @Skywalker-11,

In my MailScanner.conf, Spam Action was already set to store.

Now i changed it to "Spam Actions = store-spam" , but it still not working.

My MailWatch Version:1.2.0 - RC1

My MailScanner Version:4.85.2

**Comment by Skywalker-11** [comment]
In current develop with applied fixes for utf8mb4 and *.pm files it seem to work fine together with current mailscanner (v5.0.3) and `Spam Actions = store`

**Comment by somono168** [comment]
I think i am not lucky at this time and need to wait for new release of MailWatch. Hope it can fix this.

By the way, thank you guys so much for your time trying to solve this problem :)

**Comment by Skywalker-11** [comment]
@somono168 Can you try the patched MailWatch.pm at https://github.com/Skywalker-11/1.2.0/blob/2951934632e6585d11783779f6f732431375d977/MailScanner_perl_scripts/SQLBlackWhiteList.pm and validate if that fixes the problem?
