### ISSUE TITLE
Feature request - domain admin accounts create new users.

### ISSUE THREAD

**Issue by mealerz** [mailwatch/MailWatch#276]
Hi,
I think domain admin accounts should have the ability to create user accounts for their own domain, so that they can populate the database with a list of the domains email accounts. 
##

**Comment by endelwar** [comment]
I Agree!

**Comment by asuweb** [comment]
Agreed - this would be a useful feature.  As would csv upload of users/passwords from the GUI

**Comment by mealerz** [comment]
Bit of a problem here. The users seem to have ability to create administrators, so they can then log in and see every domain.

**Comment by Skywalker-11** [comment]
@mealerz should be fix in current develop

**Comment by Skywalker-11** [comment]
can be closed

**Comment by mealerz** [comment]
Yes this works. It has a slight problem in that when you log in as domain admin and try to create an admin user, it says - Error: You don't have the permissions, to add users of domain %s
Would it not be better to remove the ability to select administrator from the drop down if you are a domain admin?

**Comment by mealerz** [comment]
Got this working now and just having a look. Would it not be better if you are a domain admin not to see the 'admin' option from the drop down?
Other than that, this is brilliant!
