### ISSUE TITLE
Sendmail Issue - Mail going through without beeing checked

### ISSUE THREAD

**Issue by miggu69** [mailwatch/MailWatch#334]
Mail going through without beeing checked

We have an Issue, that a few mail are going through sendmail and we do not found the Message ID into MailWatch. The message are just not scanned, and the are delivered with Spam into

Does any one have an Idee or the same issue?

Thanks

**Comment by endelwar** [comment]
Are the same messages analysed by MailScanner?

**Comment by miggu69** [comment]
To be honnest we do not see these Email in Record on Mailwatch, we just see these in the logs and the goes through and are delivered without any check

**Comment by asuweb** [comment]
Are you using sendmail as your MTA?

**Comment by miggu69** [comment]
yes we do

**Comment by endelwar** [comment]
@miggu69 are sendmail's logs referring to mailscanner in any way? are there some lines that say "calling custom end function MailWatchLogging" and/or "Logging message AB01234567.ABCDE to SQL"?
What is `MailScanner --lint` reporting?

**Comment by asuweb** [comment]
@miggu69 any update on this?

**Comment by endelwar** [comment]
@miggu69 any update on this?

**Comment by endelwar** [comment]
Closing, reopening if feedback is coming
