### ISSUE TITLE
Strange Aborted connection message in /var/log/syslog

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#345]
I discovered this message in my test server.

Jan  4 10:08:00 antispam-test mysqld: 170104 10:08:00 [Warning] Aborted connection 1465 to db: 'mailscanner' user: 'mailscanner' host: 'localhost' (Got timeout reading communication packets)

Does someone have an idea where it come from?

Debian wheezy + exim + mailscanner 5.0.3 + mariadb 10.0.28

**Comment by asuweb** [comment]
Sounds like an issue with mariadb timing out.  Are you getting lots of these or only this one?

**Comment by stefaweb** [comment]
I've looked in syslog for one week. Message started January 2. One or two per day but he server is not realy used. This is just my dev server.

I've sent mails to the test server. Warning message seems not related to receive or sent messages to the server.

I've restarted mailscanner and matriadb, no warning message generated.

**Comment by asuweb** [comment]
Are you still getting these errors in the logs?

**Comment by stefaweb** [comment]
Yes.
Seems to come some time after a mailscanner restart. In fact 10 minutes after the restart.

**Comment by stefaweb** [comment]
I've activated the mariadb log. Nothing special inside at the time of the connect error in syslog.

**Comment by stefaweb** [comment]
I've found that the script who generate this log is MailWatch.pm.

**Comment by stefaweb** [comment]
"wait timeout" in Mysql is 600 secondes...

**Comment by stefaweb** [comment]
Problem still here with my new Debian 8 Jessie dev server.
A temporary fix is to place this in mysql config file.
wait_timeout = 3600

**Comment by stefaweb** [comment]
The problem seems to be the related to the way that the "persistent session" is managed in the Perl code of MailWatch.pm.

**Comment by endelwar** [comment]
Digged MySQL and MariaDB documentation and found that default `wait_timeout` is 28800 seconds for both:

- http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_wait_timeout
- https://mariadb.com/kb/en/mariadb/server-system-variables/#wait_timeout

28800 seconds (8 hours) is greater that MailScanner `Restart Every` config option (default to 7200 seconds/2 hours).

If you configure MySQL/MariaDB with a  `wait_timeout` smaller that MailScanner `Restart Every` persistent connections like the one MailWatch.pm can be killed.

**Comment by stefaweb** [comment]
Defaut in Debian package is 600 seconds.
/etc/mysql/my.cnf
wait_timeout		= 600

I've changed it to 7200 seconds to see.

**Comment by stefaweb** [comment]
Snif, 

with wait_timeout = 10800

```
Jan 10 06:35:40 antispam-dev mysqld: 170110  6:35:40 [Warning] Aborted connection 2325 to db: 'mailscanner' user: 'mailwatch' host: 'localhost' (Got timeout reading communication packets)
Jan 10 09:18:37 antispam-dev mysqld: 170110  9:18:37 [Warning] Aborted connection 2612 to db: 'mailscanner' user: 'mailwatch' host: 'localhost' (Got timeout reading communication packets)
Jan 10 15:41:07 antispam-dev mysqld: 170110 15:41:07 [Warning] Aborted connection 1044 to db: 'mailscanner' user: 'mailwatch' host: 'localhost' (Got timeout reading communication packets)
Jan 10 18:52:25 antispam-dev mysqld: 170110 18:52:25 [Warning] Aborted connection 1578 to db: 'mailscanner' user: 'mailwatch' host: 'localhost' (Got timeout reading communication packets)

```

**Comment by Skywalker-11** [comment]
@stefaweb can this be closed?

**Comment by stefaweb** [comment]
Still here on the dev server.

**Comment by Skywalker-11** [comment]
Did you try to increase `max_allowed_packet` for mysql?
[https://dba.stackexchange.com/questions/19135/mysql-error-reading-communication-packets](https://dba.stackexchange.com/questions/19135/mysql-error-reading-communication-packets)

**Comment by stefaweb** [comment]
I try. Was 16M. Put 256M.
Waiting...

**Comment by stefaweb** [comment]
Still here...

```
Jun  7 17:22:16 antispam-dev mysqld[734]: 2017-06-07 17:22:16 140587153079040 [Warning] Aborted connection 22893 to db: 'mailscanner' user: 'mailwatch' host: 'localhost' (Got timeout reading communication packets)
Jun  7 18:13:44 antispam-dev mysqld[734]: 2017-06-07 18:13:44 140587153382144 [Warning] Aborted connection 23084 to db: 'mailscanner' user: 'mailwatch' host: 'localhost' (Got timeout reading communication packets)
```

**Comment by Skywalker-11** [comment]
Can you try using a different sql user for the web gui and mailscanner part so we know were to look at?

**Comment by stefaweb** [comment]
This is coming from MailWatch.pm. I'm already using 2 différents mysql login to know.

> I've found that the script who generate this log is MailWatch.pm.
> 10 minutes after the start of mailscanner (5.0.3).

I don't have this on the prod server.

Do you have a mailwatch dev server without trafic to look if you have this in the log? On the prod server, witch is a clone of the dev server, I don't have the message.

**Comment by Skywalker-11** [comment]
Just checked but at least in the last two weeks I could not find such errors on my prod server and my dev server (which only has send 2 reports from mailwatch per day). Does your prod server has the same mysql and perl versions installed as your dev server?

Or do you have to enable further logging for mysql so that the errors are shown?

**Comment by stefaweb** [comment]
An idea. I've to check` log_error_verbosity` (but should be default value).
dev: mariaDB 10.1 (I updated to 10.1 to see if message will be gone)
prod: mariaDB 10.0
The rest is identical.

**Comment by Skywalker-11** [comment]
Can we close?

**Comment by stefaweb** [comment]
Can be closed as not related to MW but problem still here.
