### ISSUE TITLE
No virus report. Error!

### ISSUE THREAD

**Issue by Giangiz** [mailwatch/MailWatch#387]
Hello. With rep_viruses.php i get 'Error: no rows retrieved from database ' .
With rep_top_viruses.php i get Error: no rows retrieved from database...0 
I upgraded the new files but the problems remain the same
there are solutions?

Thanks

[ system ubuntu 14.04 ]

**Comment by asuweb** [comment]
Did you run upgrade.php to upgrade the schema?

**Comment by Giangiz** [comment]
Hi. I haven't run the upgrade. This is necessary for solve the problem?

**Comment by asuweb** [comment]
If you've upgraded mailwatch the yes, you need to run upgrade.php to incorporate any schema changes.

**Comment by stefaweb** [comment]
Use the version in develop. The version in RC4 is not good.

**Comment by Giangiz** [comment]
Ok. But where i find the version develop? Thanks

**Comment by stefaweb** [comment]
Here: https://github.com/mailwatch/1.2.0/tree/develop

**Comment by endelwar** [comment]
Are there any rows in database which are marked as virus?

**Comment by asuweb** [comment]
It shouldn't throw an error even if there are no viruses found - it supposed to display "No Records Found" or something similar

**Comment by stefaweb** [comment]
Yes, I just "localized" this!

**Comment by Giangiz** [comment]
"Are there any rows in database which are marked as virus?"

Yes. I have one rows in db which are marked as virus. 
I will make with develop and write here the result. Thanks

**Comment by asuweb** [comment]
@Giangiz any news on this?

**Comment by Giangiz** [comment]
Sorry for the delay. I built new project and now works fine!
