### ISSUE TITLE
Releasing blocked files through rpc.

### ISSUE THREAD

**Issue by mealerz** [mailwatch/MailWatch#409]
I'm having problems releasing blocked files through rpc. It works if I go onto the server to perform the action, but from remote server I get the following - 

XML-RPC Error: Invalid return payload: enable debugging to examine incoming payload (XML error: Invalid document end at line 2, column 1) (RPC)

On server I do not have any errors apart from - 

[Thu Jan 19 11:43:10.540581 2017] [:error] [pid 43102] [client 212.42.162.34:54081] PHP Notice:  Undefined variable: _SESSION in /usr/local/www/newer/mailscanner/functions.php on line 3336

Nothing that would stop this. Please could someone explain how I could debug this? 

Thanks,
Rich

**Comment by stefaweb** [comment]
If you activate DEBUG = true in conf.php, do you have more message?

**Comment by mealerz** [comment]
@stefaweb 

I get this - 

---GOT---
HTTP/1.1 200 OK
Date: Thu, 19 Jan 2017 16:51:51 GMT
Server: Apache/2.4.23 (FreeBSD) PHP/5.6.27
X-Powered-By: PHP/5.6.27
Vary: Accept-Charset
Content-Length: 307
Connection: close
Content-Type: text/xml;charset=UTF-8

<br />
<b>Notice</b>:  Undefined variable: _SESSION in <b>/usr/local/www/newer/mailscanner/functions.php</b> on line <b>3336</b><br />
<?xml version="1.0"?>
<methodResponse>
<params>
<param>
<value><string>Release: message released to rich@mydomain.com</string></value>
</param>
</params>
</methodResponse>
---END---
HEADER: date: Thu, 19 Jan 2017 16:51:51 GMT
HEADER: server: Apache/2.4.23 (FreeBSD) PHP/5.6.27
HEADER: x-powered-by: PHP/5.6.27
HEADER: vary: Accept-Charset
HEADER: content-length: 307
HEADER: connection: close
HEADER: content-type: text/xml;charset=UTF-8
XML error: Invalid document end at line 2, column 1

I've just realised I do get the email, but I still get the response at the bottom - 

XML-RPC Error: Invalid return payload: enable debugging to examine incoming payload (XML error: Invalid document end at line 2, column 1) (RPC)

So I get the email, but I get an invalid response. I shall have a further look into this now.

**Comment by asuweb** [comment]
What version of mailwatch are you using?

**Comment by mealerz** [comment]
@asuweb 
Version 1.2.0 - RC1 DEV

**Comment by mealerz** [comment]
I seem to have no problems releasing viruses though.

**Comment by asuweb** [comment]
I suspect there's a typo on line 3336 and it's missing the `$_SESSION`, but we're on RC4 now and the code has changed so you will likely find that upgrading to RC4 will fix this issue.  I havne't got RC1 to hand to check, but a quick search for `_SESSION` in `functions.php` should confirm

**Comment by mealerz** [comment]
Yes I think you're right. I've got a newer version on another server and I've just tested that and it works fine. I'll upgrade this one tomorrow. Sorry for this, I should have tested more. I'll report back tomorrow and then close this one.

**Comment by asuweb** [comment]
No problem :)

**Comment by asuweb** [comment]
@mealerz is this still an issue or can it be closed?

**Comment by mealerz** [comment]
Hi @asuweb - sorry for the delay in testing this. I've installed rc4 on machine 1 and log into machine 1 to try and release a blocked filename attachment. On machine 2 I have just now installed RC4. I can release the attachment from machine 2, where the file is blocked and located, but on machine 1 I get an error and then I log into machine 2 and I see this in the logs - 

[Wed Feb 01 16:37:27.317072 2017] [:error] [pid 1849] [client my_ip_address:12126] PHP Notice:  Undefined variable: _SESSION in /usr/local/www/1.2.0-RC4/mailscanner/functions.php on line 3499

However, on machine 3 I also have another filename checks, found possible filename hiding and on machine 1 I can release that fine, so I think there is a problem with machine 2.

What would stop this from working, do you know? Very strange.

**Comment by mealerz** [comment]
Before, the problem was this - 

[Wed Feb 01 16:27:21.797548 2017] [:error] [pid 43102] [client my_ip_address:32833] PHP Notice:  Undefined variable: _SESSION in /usr/local/www/newer/mailscanner/functions.php on line 3336

So the line has changed.

**Comment by mealerz** [comment]
Also I have php56-session-5.6.27 on all servers.

**Comment by mealerz** [comment]
Also, the email is being released, so again this seems to be a reporting issue. I'm getting the email!

**Comment by mealerz** [comment]
I'm still getting this problem. I get an error on the release but the email goes out fine. Has this been fixed in a newer version? I'm willing to test. It's only happening on filename checks, so most of the time we just see problems when we try to release a double barrel extension.

**Comment by endelwar** [comment]
@mealerz can you please update me on error row number after upgrading to 1.2.4? Also have you tried the [replace_id_with_maillogid branch](https://github.com/mailwatch/MailWatch/tree/feature/replace_id_with_maillogid)?

**Comment by Skywalker-11** [comment]
Any news on this?

**Comment by mealerz** [comment]
Sorry, let me run some more tests and come back to you.

**Comment by mealerz** [comment]
I'll need to build / upgrade a server since I am using MySQL 5.5 and when I import the db I'm getting this - ERROR 1293 (HY000) at line 89: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

So give me a day or so and I'll come back to you with the results.

**Comment by Skywalker-11** [comment]
@mealerz have you used develop or 1.2.4 release? It should be fixed in current develop

**Comment by mealerz** [comment]
I'm nearly there. I'm going to run some tests using php70 and should it work on MySQL 5.7?
I'll let you know when I've finished. Just finalising this server build now.

**Comment by mealerz** [comment]
I'll use the develop version :-)

**Comment by mealerz** [comment]
I can confirm the releasing works fine. Wow this is looking good!

Could someone explain why I see 2 items to release? 

If I release the top item - the email, it sends me how I want it - Email message with warning, attachment, I open the attachment and it shows the original email with original attachment. Great.

When I release the attachment on it's own, it sends me just an email with warning and attachment included. This is not great. 

I used to see this all the time so I changed the code to hide it. Would you like me to send you the code?

**Comment by mealerz** [comment]
![problem-release](https://user-images.githubusercontent.com/1402362/28369608-0c9a3354-6c90-11e7-936d-5c8ef5132c51.png)

**Comment by mealerz** [comment]
I'm not explaining this very well, so I've sent a pic. I believe we should be hiding the bottom attachment line completely, since sendmail already sends the attachment. I don't know if this will break other MTA's though.

**Comment by Skywalker-11** [comment]
The idea behind this is probably that the original message already has been send to the recipient without the dangerous attachment so there is no need to send the full mail when releasing. But in case the mail also has been detected as Spam the mail will not be delivered at all so you have to be able to release all of the mail.

**Comment by mealerz** [comment]
Well I think this can be closed then. I am releasing these fine now remotely over rpc. I'm very happy with that. I think you all have done a splendid job. Please let me know if you would like me to test anything else and I will git clone to my new test machine. I am just using MySQL 5.6 but php 7.0. I will look to upgrade to MySQL 5.7 soon. Thanks.

**Comment by Skywalker-11** [comment]
@mealerz can you close this then?
