### ISSUE TITLE
Upgrading to new Mailwatch, css in login.php

### ISSUE THREAD

**Issue by mealerz** [mailwatch/MailWatch#412]
I'm just upgrading to RC4 and it seems so much better. Very nice work everyone involved. 
Just wondering if RC5 will have login.php css moved to style.css?

**Comment by asuweb** [comment]
RC5 will actually be V1.2 stable

And then I believe work will be commencing on V2.0 - which will include a new UI

**Comment by stefaweb** [comment]
Still there in RC4.
You can do it in develop.
Many things have been corrected in develop since RC4. Specially the upgrade script.

**Comment by asuweb** [comment]
It would be a good idea for maintainability to move all css to style.css - I'll add it to my todo list

**Comment by stefaweb** [comment]
quarantine_action.php also have a css inside.

**Comment by asuweb** [comment]
I'll go through every file and move any css to style.css
