### ISSUE TITLE
TODO: space before words in sf_version.php 

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#448]
Add more space between the frame and the words.

![capture d ecran 2017-01-27 a 18 25 41](https://cloud.githubusercontent.com/assets/12907102/22395265/a979d84e-e538-11e6-90ed-f6774c6fc563.png)

**Comment by asuweb** [comment]
Can be fixed at the same time as #417

**Comment by stefaweb** [comment]
ok, thank

**Comment by stefaweb** [comment]
Done.
