### ISSUE TITLE
Wishlist: Install script for Mailscanner / Mailwatch

### ISSUE THREAD

**Issue by asuweb** [mailwatch/MailWatch#453]
A lot of the mailwatch installation process could be fairly easily scripted - having just done 2 parallel installs, there's very little that couldn't be handled automatically with the relevant arguments supplied to the script.

This would likely reduce the number of failed setups and idiosyncrasy which makes debugging particularly tricky.  

It could also be set to automatically fetch and install mailscanner should the user wish

**Comment by endelwar** [comment]
I agree with you! I was thinking the same last week.
And this should be shipped with 1.2.0, and be very well tested before release.

- create.sql has to be replaced by an install.php console script
- upgrade.php has to be included in install.php which has to check tables existence, field length and encoding, the it should be removed
- perl libraries version should be checked
- documentation has to be updated together with code
- blame systemd for its existence ;)

**Comment by stefaweb** [comment]
I hate systemd too !

Good idea install script.

**Comment by asuweb** [comment]
@endelwar - Great minds think alike.  Shouldn't you be changing nappies? ;-)

Yes, it definitely needs extensive testing.  

I was thinking more a shell script rather than php, which would handle the installation and setup of the full stack, that way there's some control over what's installed and incompatibilities can be minimised.

**Comment by Skywalker-11** [comment]
And we have to decide what operating systems we want to support. We won't be able to make the install script work for every system. Also if we put the instructions for all operating systems in one big file or split them for each os. 

I suggest that we split the upgrade/install into multiple files (sql, package/perl management, file copying / permissions). That way they can easier be maintained.

As for supported systems I suggest:
Webservers: nginx, Apache (with virtual-host or conf.d file; maybe specify the web folder path for MailWatch during setup)
OS: Debian, Ubuntu, SUSE

**Comment by asuweb** [comment]
Centos, RHEL

**Comment by stefaweb** [comment]
Hello!

Write install scripts and test them is very time consuming.

If possible, I will prefer that we publish RC5 "as this" with the curent incoming PR before switching to a new install concept.

**Comment by asuweb** [comment]
I agree writing and maintaining install scripts is time consuming, but then so if find "bugs" which may or may not bugs in the concept of mailwatch.   If we can standardise the install / setup process, then there should be far less time consumed tracking down issues which seem to be system / setup related.

**Comment by stefaweb** [comment]
Like #-4-3-0!

**Comment by stefaweb** [comment]
This tool have an interesting system to manage OS.

https://github.com/extremeshok/clamav-unofficial-sigs

```
antispam-dev:/home/xxxxx# ll /etc/clamav-unofficial-sigs/
total 100
-rw-r--r-- 1 root root 24517 janv.  7 18:37 master.conf
-rw-r--r-- 1 root root  1222 janv.  7 16:50 os.archlinux.conf
-rw-r--r-- 1 root root  1211 janv.  7 16:50 os.centos6.conf
-rw-r--r-- 1 root root  1303 janv.  7 16:50 os.centos6-cpanel.conf
-rw-r--r-- 1 root root  1320 janv.  7 16:50 os.centos7-atomic.conf
-rw-r--r-- 1 root root  1352 janv.  7 16:50 os.centos7.conf
-rw-r--r-- 1 root root  1223 janv.  7 18:15 os.conf
-rw-r--r-- 1 root root  1228 janv.  7 16:50 os.debian7.conf
-rw-r--r-- 1 root root  1224 janv.  7 16:50 os.debian8.conf
-rw-r--r-- 1 root root  1300 janv.  7 16:50 os.freebsd.conf
-rw-r--r-- 1 root root  1209 janv.  7 16:50 os.gentoo.conf
-rw-r--r-- 1 root root  1341 janv.  7 16:50 os.openbsd.conf
-rw-r--r-- 1 root root  1232 janv.  7 16:50 os.opensuse.conf
-rw-r--r-- 1 root root  1846 janv.  7 16:50 os.osx.conf
-rw-r--r-- 1 root root  1240 janv.  7 16:50 os.raspbian.conf
-rw-r--r-- 1 root root  1254 janv.  7 16:50 os.slackware.conf
-rw-r--r-- 1 root root  1714 janv.  7 16:50 os.solaris10.conf
-rw-r--r-- 1 root root  1712 janv.  7 16:50 os.solaris11.conf
-rw-r--r-- 1 root root  1213 janv.  7 16:50 os.ubuntu.conf
-rw-r--r-- 1 root root  1970 janv.  7 16:52 user.conf

```

**Comment by endelwar** [comment]
Install script is here: https://github.com/mailwatch/mailwatch-install-script
