### ISSUE TITLE
Change user to username in tables spamscores and audit_log

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#462]
If possible, It will be may be useful to change user to username in tables spamscores and audit_log. 

With this, we will have the same name "username" everywhere.

```
CREATE TABLE IF NOT EXISTS `spamscores` (
  `user` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `lowspamscore` decimal(10,0) NOT NULL DEFAULT '0',
  `highspamscore` decimal(10,0) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

```
CREATE TABLE IF NOT EXISTS `audit_log` (
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `ip_address` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `action` longtext COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Comment by asuweb** [comment]
Would it perhaps be better to change user to userID and then use the corresponding userid of the user that is already defined in the users table?  This would keep it in sync should the username be changed.

Additionally, where is the table `spamscores` actually used?  The same fields are present in the `users` table

**Comment by stefaweb** [comment]
Good point. I've not saw this.

**Comment by stefaweb** [comment]
> Additionally, where is the table spamscores actually used? The same fields are present in the users table

NO reference to 'spamscores' table in code!

A relic of the past?

**Comment by endelwar** [comment]
> NO reference to 'spamscores' table in code!
> 
> A relic of the past?

Was added in 1.0.3 along with SQLSpamSettings.pm, but never used, apparently: safe to remove.

**Comment by stefaweb** [comment]
> safe to remove.

Added to #471.
