### ISSUE TITLE
Whishlist: add a B/W entries counter in black/white list

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#509]
Like this.

![8ec7dbf8-eebc-11e6-9070-56547cc873d4](https://cloud.githubusercontent.com/assets/12907102/22779951/05dd8170-eebd-11e6-8e80-a9aa728285ca.png)

**Comment by stefaweb** [comment]
Something wrong with last PR. Count is the same for BL and WL.

![sc](https://user-images.githubusercontent.com/12907102/29553993-d54ec970-871d-11e7-95bd-a2a926ea25ab.png)

**Comment by endelwar** [comment]
bad copy/paste :(

**Comment by stefaweb** [comment]
Fine with last PR. Thanks!
