### ISSUE TITLE
MailScanner-5.0.4-4

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#510]
Seems that a new MailScanner-5.0.4-4 is available.

https://github.com/MailScanner/v5

```
11/10/2016 Changes in    v5.0.4-4
==================================
- support for Postfix long queue IDs
- updated RHEL/Debian/SuSE install scripts
- updated cron job scripts
- updated init script
- changed Debian upstart from 80/20 to 80/80
- updated RHEL packages in install.sh
- updated SuSE packages in install.sh
- Postfix double scan during custom fix
- fixed ms-init and ms-check
- fixed ramdisk portion of install scripts
- fixed perl module declarations
```

But not directly available as binary. You should build it (easy).

No yet tried.

**Comment by asuweb** [comment]
I have, it works fine

**Comment by stefaweb** [comment]
And the upgrade from v5.0.3-7. Smooth?

**Comment by asuweb** [comment]
I can't remember which version I upgraded from, but it was smooth with no issues as far as I remember

**Comment by shawniverson** [comment]
These are the latest packages, afaik.  I haven't seen a 5.0.4-4 packaged as
of yet.

https://s3.amazonaws.com/msv5/release/MailScanner-5.0.4-3.rhel.tar.gz

Debian
https://s3.amazonaws.com/msv5/release/MailScanner-5.0.4-3.deb.tar.gz

Nix
https://s3.amazonaws.com/msv5/release/MailScanner-5.0.4-3.nix.tar.gz

RHEL
https://s3.amazonaws.com/msv5/release/MailScanner-5.0.4-3.rhel.tar.gz

SuSE
https://s3.amazonaws.com/msv5/release/MailScanner-5.0.4-3.suse.tar.gz

**Comment by stefaweb** [comment]
Upgrade to 5.0.4-4 done. No problem at all.
default, conf.d and custom files still here after the update.

**Comment by asuweb** [comment]
@shawniverson - yes, mailscanner haven't packaged the latest master branch for some reason. The master branch on git is 5.0.4.4.
