### ISSUE TITLE
Whishlist: A connection box when database failed.

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#511]
In case of problem we got.

![capture d ecran 2017-02-10 a 20 25 51](https://cloud.githubusercontent.com/assets/12907102/22841054/45a300f0-efd0-11e6-8762-fc1b95eae072.png)

If we can replace this with a simple box with a message in this style.

![error](https://cloud.githubusercontent.com/assets/12907102/22841070/60b95bc8-efd0-11e6-8408-fb329ede6276.jpg)

**Comment by asuweb** [comment]
It would be a good idea to provide proper error catching, rather than the use of `die()`

We need to decide if we want to do this for v1.2 or wait until 2.0

**Comment by stefaweb** [comment]
84 die() in code...  😟

**Comment by asuweb** [comment]
Yes, - it wouldn't be too difficult to replace them will a call to a fatal error function, which we could then use to format the errors for user display, log them somewhere and die gracefully.

Just depends if we want that in v1.2 or v2

**Comment by stefaweb** [comment]
For the database 1.2.

For the rest, 2.0.

**Comment by asuweb** [comment]
PR #852

**Comment by asuweb** [comment]
Can be closed
