### ISSUE TITLE
store/delete/deliver/header in detail.php not localized

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#538]
I'm trying to find where are located `store`, `delete`,  `deliver` and `header` in detail.php but not found.

![capture d ecran 2017-02-16 a 10 34 10](https://cloud.githubusercontent.com/assets/12907102/23015652/f3552ee6-f433-11e6-989f-d8c889eb5169.png)

![capture d ecran 2017-02-16 a 10 35 09](https://cloud.githubusercontent.com/assets/12907102/23015657/f71e0a66-f433-11e6-8f14-7c4012cda73b.png)

![capture d ecran 2017-02-16 a 10 38 27](https://cloud.githubusercontent.com/assets/12907102/23015712/2adf5d50-f434-11e6-808a-12b528d35e15.png)

**Comment by asuweb** [comment]
Directly from the MailScanner.conf - can't be localised (well, not without some more code changes)

**Comment by stefaweb** [comment]
In fact, I've found the words in `/etc/MailScanner/reports/fr/languages.conf` and  `/etc/MailScanner/reports/fr/languages.conf.strings` but I'm afraid to complete the localization in these files due to possible edge effects.

**Comment by stefaweb** [comment]
I've found this one also.

![capture d ecran 2017-02-16 a 10 54 39](https://cloud.githubusercontent.com/assets/12907102/23016358/7e1bf8be-f436-11e6-90bb-b5bf63fd8fae.png)

**Comment by Skywalker-11** [comment]
Maybe we can search for the keywords and replace the message with a corresponding localized one
