### ISSUE TITLE
fixMessageId does not seem to work

### ISSUE THREAD

**Issue by remkolodder** [mailwatch/MailWatch#548]
Hi,

I have configured a Distributed MailScanner setup. My remote gateways are the parsers of the email and therefor insert the data into the database, which is read by the webserver and processed from there.

We use Postfix, which is defined in MailScanner.conf as 'MTA = postfix'. This goes for all our machines, including the webserver (Which does not have an active running Mailscanner itself!). When viewing messages on the "message operations" screen, and selecting a message for learning as ham or spam, the message id is not transformed from a "_" into a ".".

```php
function fixMessageId($id)
{
    $mta = get_conf_var('mta');
    if ($mta === 'postfix') {
        $id = str_replace('_', '.', $id);
    }

    return $id;
}
```

This function, as you are aware of, should arrange that. hashing out the if .. { and } lines (forcing the replacement of the $id) makes it work on the webserver. The get_conf_var function should open the /usr/local/etc/MailScanner/MailScanner.conf (freebsd host) and read the MTA variable there (or at least I figure that it isn't case sensitive, it does not matter when I change that in the functions.php file).

Am I doing something wrong here or?

```shell
/usr/local/etc/MailScanner]$ grep -i mta *
MailScanner.conf:MTA = postfix
```

Thanks,
Remko

**Comment by Skywalker-11** [comment]
I can't reproduce this with current develop as with my postfix installation the mails already has an id of form "OPT-XXXXXXXXXXX.XXXXX" on the webpage eg. for the Spam radio button:
`<input name="OPT-7944F780809.AB232" type="RADIO" value="S">`

In the db they also are stored in format "XXXXXXXXXXX.XXXXX". Can you check how they are logged in the maillog table and shown on the webpage?

**Comment by remkolodder** [comment]
So; 

In the DB they are listed as XXXX.XXX as you mention. On the webpage, they are listed as "OPT-XXX.XXX" as you mention. But when I mark a "probably" spam message as spam and press Learn:

Message ID 1C2B22D4FDD_AB1E7 Message ID 

while the message source mentions:

<td align="center" style="white-space:nowrap"><input name="OPT-1C2B22D4FDD.AB1E7" type="RADIO" value="S">&nbsp;<input name="OPT-1C2B22D4FDD.AB1E7" type="RADIO" value="H">&nbsp;<input name="OPT-1C2B22D4FDD.AB1E7" type="RADIO" value="F">&nbsp;<input name="OPTRELEASE-1C2B22D4FDD.AB1E7" type="checkbox" value="R"></td>
 <td align="center">[<a href="detail.php?id=1C2B22D4FDD.AB1E7">#</a>]</td>

The moment that I strictly apply: $id = str_replace('_', '.', $id); it works fine.

This is all from the "Message operations" page.

How can we get into this a bit deeper to see why it behaves like this?

**Comment by Skywalker-11** [comment]
I don't see a problem in current develop. What version if MailWatch are you using?
![image](https://cloud.githubusercontent.com/assets/11180862/23086818/b92157bc-f56f-11e6-8676-4330c8b7e61b.png)

**Comment by remkolodder** [comment]
I am using the 'develop' branch. Still at some point the $id is placed as _, it is not learning (ham/spam anything it is only reporting "Message ID XXX_XXX", while the SQL records have a . (dot) instead of the lowercase hyphen and the UI also shows the dot.

But still, without doing the str_replace, it does not work.

**Comment by remkolodder** [comment]
when I add a ``echo $id > /tmp/ms.txt`;` in do_message_ops.php;

```
    foreach ($_POST as $k => $v) {
        if (preg_match('/^OPT-(.+)$/', $k, $Regs)) {
            $id = $Regs[1];
            `echo $id > /tmp/ms.txt`;
            $id = fixMessageId($id);

```
it reports the id as:

```
cat /tmp/ms.txt
2461F2D4FD7_AB43C
```

So there is the _ all of a sudden. While it is being shown properly on the website and database, it is represented as _ and the fixMessageID just does not kick in; if I add the echoes in fixMessageID (under functions.php) like this;

```
function fixMessageId($id)
{
    $mta = get_conf_var('MTA');
    `echo mta: $mta >> /tmp/ms.txt`;
    `echo id: $id >> /tmp/ms.txt`;
    if ($mta === 'postfix') {
        $id = str_replace('_', '.', $id);
    }

    return $id;
}
```

it reports the following as output, the postfix isn't matched and thus the id is not fixed.

```
mta:
id: 2461F2D4FD7_AB43C
```

**Comment by Skywalker-11** [comment]
@remkolodder are you sure that the mta is defined on the webserver and not eg. overwritten in the conf.d directory of mailscanner? Also check if the MailScanner.conf file and the file under conf.d is readable by the webserver user eg. with `sudo -u www-data cat /etc/MailScanner/MailScanner.conf`

When testing it with 
```
if (preg_match('/^OPT-(.+)$/', $k, $Regs)) {
     var_dump($k);
     $id = $Regs[1];
     $id = fixMessageId($id);
     var_dump($id);
} elseif ...
```

I get a printout like `string(21) "OPT-86464781114_A34D5" string(17) "86464781114.A34D5"` so it seems to work but mta has to be detected correctly.

**Comment by remkolodder** [comment]
yes, well that isn't detected, I even included 'mta' in the MailScanner.conf:

``
 /usr/local/etc/MailScanner]$ grep -Ri mta *
MailScanner.conf:MTA = postfix
MailScanner.conf:mta = postfix
``

That didn't change anything . I hope that the configuration only loads MailScanner.conf and no sample files because the example file lists 'MTA = Sendmail'. (I'll change that to make sure, did that, didn't change).

``
/usr/local/etc/MailScanner]$ sudo -u www -H cat MailScanner.conf | head -4
# Main configuration file for the MailScanner E-Mail Virus Scanner
#
# It's good practice to check through configuration files to make sure
# they fit with your system and your needs, whatever you expect them to
``

**Comment by Skywalker-11** [comment]
I found the problem in line 1395 of functions.php
```
    if (DISTRIBUTED_SETUP) {
        return false;
    }
```

@endelwar is there a reason why we don't allow the use of MailScanner variables if we use a distributed setup?

**Comment by remkolodder** [comment]
Yes, removing that gives an error, but at least it sees the proper mta setup. and properly learns spam/ham messages.

`Warning: closedir() expects parameter 1 to be resource, boolean given in mailscanner/functions.php on line 1446`

**Comment by asuweb** [comment]
@Skywalker-11 

> is there a reason why we don't allow the use of MailScanner variables if we use a distributed setup?

My understanding of the "distributed setup" is for occasions where mailwatch is installed on a standalone system - i.e, one that does not also run MailScanner.  In this case we can't use MailScanner variables because MailScanner isn't available to mailwatch.

Any other deployment where MailWatch and mailscanner reside on the same server, distributed setup should be set to false.

**Comment by remkolodder** [comment]
@asuweb I can appreciate that and this indeed makes sense. The check for the right message though depends on the $mta variable being set (or in it's absense or different configuration, it will not further use the fixMessageID routine). Should we, in case we have DISTRIBUTED SETUP defined, can we use define('MTA','postfix'); in the conf.php and use that instead?

`if(defined('MTA')) { $mta=MTA; } else { $mta = get_conf_var('MTA'); }
`

**Comment by remkolodder** [comment]
@asuweb In addition to your questions: when I setup DISTRIBUTED_SETUP to false, I am no longer able to view the remote quarantine files etc. I just deployed MailScanner on this machine as well, with a via puppet delivered configuration so that all machines are equal. The only difference is, is that MailScanner has no function on that machine so all there is, is the software installed, nothing more nothing less (with the same configuration as the edge-servers).

I locally added the things in my earlier comment:

conf.php add `define('MTA','postfix');`
functions.php add `if (defined('MTA')) { $mta = MTA; } else { $mta = get_conf_var('MTA'); }`

We can even expand that with `if (defined('MTA') && defined('DISTRIBUTED_SETUP')) { $mta = MTA; } `etc. So that this is only read when DISTRIBUTED_SETUP is enabled and MTA is defined..

**Comment by stefaweb** [comment]
Is this Issue solved?

**Comment by remkolodder** [comment]
Hi @stefaweb no this is not yet resolved. We need to find a way to set some variables without rely'ing on MailScanner being installed on the machine itself.

Perhaps we should just do the conf.php and only set `define('MTA', 'yourmtahere'); ` and not rely on the MailScanner setting for that at all. Perhaps more variables are involved here, but I am only hitting MTA at the moment..

Thanks

**Comment by endelwar** [comment]
> Should we, in case we have DISTRIBUTED SETUP defined, can we use define('MTA','postfix'); in the conf.php and use that instead

That would make impossible to have distributed setup with different MTA

**Comment by endelwar** [comment]
> is there a reason why we don't allow the use of MailScanner variables if we use a distributed setup?

@Skywalker-11 in a distributed setup every mailscanner instance can be configured in a different way one from the other (also different version of mailscanner), so a single mailscanner config for the whole distributed system is a no go, except in the case that it's a cluster with the same exact mailscanner.conf

**Comment by remkolodder** [comment]
@endelwar OK, that makes sense, but it does not work in this way either.

If we can configure a distributed_setup, you can set that every instance should be configured the same, so that "one" similar configuration applies. If one deviates from that, then local hacks might be in place.

But, possibly more easy to fix generally; we use the RPC way of telling the peer's (frontend nodes) that a message needs to be learned as spam, ham, or be released, from the webfrontend.

So, if we issue a call that "XXXX_XXX" should be learned as spam, then the RPC call would be without any modification, the but receiving host is configured as, MTA = postfix, or sendmail or whatever, and can alter the message_id from an underscore to a dot if needed.
Then it simply does not matter what the local configuration has, it fires away the proper information and the processing node does the rewrite.

**Comment by endelwar** [comment]
I've looked back at the code, and the dot/underscore replacement was put there because php convert dots in $_GET variables automatically (http://php.net/manual/en/language.variables.external.php) and Postfix uses a dot in message id.
Now that we have introduced `maillog.maillog_id` field in database we can use that and get rid of `fixMessageId()`

**Comment by remkolodder** [comment]
So how would that work? e.g. if I can test whether that works without the fix then ofcourse I will happily use that ;-)

**Comment by endelwar** [comment]
Some code need to be changes, basically everywhere (I think, need to check better) there is a query on maillog that says `SELECT id AS id2` need to be replaced by `SELECT maillog_id AS id2` so that the numeric id is get instead of the alphanumeric one, thus no more fixMessageId()

**Comment by endelwar** [comment]
I've started working on a branch that will replace MTA id with database id, it can be tested here: https://github.com/mailwatch/MailWatch/tree/feature/replace_id_with_maillogid

**Comment by stefaweb** [comment]
> I've started working on a branch that will replace MTA id with database id

What the advantage of this?

**Comment by endelwar** [comment]
> What the advantage of this?

no more reference to MTA messageid in urls and code logic

**Comment by stefaweb** [comment]
ok thanks.
