### ISSUE TITLE
Site http://www.securelist.com broken (VIRUS_INFO)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#559]
Broken for days.

define('VIRUS_INFO', 'http://www.securelist.com/en/descriptions?words=%s&amp;behavior=&amp;Search=Search&amp;search_type=1');

![capture d ecran 2017-02-20 a 17 35 23](https://cloud.githubusercontent.com/assets/12907102/23133902/113df264-f793-11e6-8461-1819f8678648.png)

**Comment by asuweb** [comment]
It doesn't work reliably when you run multiple virus scanners, as it never recognises the vendor specific naming. 

I've yet to find an alternative.

**Comment by stefaweb** [comment]
And this?

`https://threats.kaspersky.com/en/?s=Constructor.DOS.G2`

https://threats.kaspersky.com/en/threat/

**Comment by Skywalker-11** [comment]
@stefaweb The problem is that each anti virus has theire own names for viruses. Eg see here [Virustotal.com](https://www.virustotal.com/de/file/c7bffc634ef8329353660e0b8047c66c8d0c2e2d962a2efda82ee79066a2c322/analysis/)

**Comment by endelwar** [comment]
What about removing it? I can't find a website that works with multivendor virus names

**Comment by asuweb** [comment]
Personally,  I would remove it. It serves little purpose and as you say, there are no reliable multi vendor sources

**Comment by stefaweb** [comment]
Not found a replacement too.
I agree to remove this.

**Comment by endelwar** [comment]
I leaved the feature in place, but disabled by default in 8bd8fb8b3341ff2c8ffeaa68d9bf7c339d1d2eb4
