### ISSUE TITLE
Move all inline css styles to style.css 

### ISSUE THREAD

**Issue by Skywalker-11** [mailwatch/MailWatch#573]
Post 1.2 release

**Comment by asuweb** [comment]
Agreed

**Comment by stefaweb** [comment]
A lot of work and testing to do this.
I agreed.

**Comment by mealerz** [comment]
Could we also have a customer css that loads after this style.css file, so we can put in our own css?

**Comment by asuweb** [comment]
Yes, that's a good approach :)
