### ISSUE TITLE
consider adding "ISSUE_TEMPLATE" and/or "PULL_REQUEST_TEMPLATE"

### ISSUE THREAD

**Issue by remkolodder** [mailwatch/MailWatch#591]
Hi,

Because I (and probably others) forget to mention s ome specific information in tickets, it might be beneficial to serve people a template. I forked mailwatch and tested this. If you add ISSUE_TEMPLATE to the root of the tree (/or under .github which is then not easily seen from the gui and checkouts) then you can add a markdown denoted file that serves some "required" information upfront.

Owncloud does that for example;

https://github.com/owncloud/core/issues/new
https://github.com/owncloud/core/tree/master/.github

Just a thought :)

**Comment by asuweb** [comment]
I like this idea - @endelwar, perhaps this could be adopted?

**Comment by endelwar** [comment]
I like it!
I would like it to be a mix of these:
- https://github.com/owncloud/core/blob/master/.github/issue_template.md
- https://github.com/bolt/bolt/blob/master/.github/ISSUE_TEMPLATE.md
- https://github.com/thephpleague/skeleton/blob/master/ISSUE_TEMPLATE.md

**Comment by remkolodder** [comment]
Hi, I am back from being absent a little. " A mix of these " sounds interesting but what are the actual Requirements so that I can port those over? I mean I can just copy/paste them all in one go, but that wouldn't be very useful I think?

Cheers

**Comment by Skywalker-11** [comment]
I suggest to create a pull request with a basic version and then fine tune it and merge to mater branch once it is satisfying.

**Comment by endelwar** [comment]
Just added issue_template.md to develop, please have a look at it, is it complete? Will be made puplic with next release of MailWatch (1.2.1 in a few days)

**Comment by Skywalker-11** [comment]
When upgrading may add previous mailwatch version.

**Comment by remkolodder** [comment]
This looks fine I think. Sorry for dropping the ball on this one...

We could also ask for a github checkout: when did you last update the local installation. (Because since the project on github is a rolling target, things might already be fixed in between).
