### ISSUE TITLE
Incomplete display in viewmail.php/viewpart.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#596]
I discovered that many messages are not well displayed with viewmail.php.

Can we do something to have a better decoding?

I've also found this comment in the code:
`/* this is a quick hack to fix issue #154, This need to be recoded in next version */`

The message contains parts well decoded and others parts not.

![capture d ecran 2017-02-26 a 14 13 51](https://cloud.githubusercontent.com/assets/12907102/23340013/d66e69e8-fc2e-11e6-891a-fce740f17e0d.png)

![capture d ecran 2017-02-26 a 14 16 46](https://cloud.githubusercontent.com/assets/12907102/23340014/dc69b2a8-fc2e-11e6-8cd3-5d6ebba7943b.png)

EDIT: message stored in quarantine 
[1chxBO-00013y-4C.zip](https://github.com/mailwatch/1.2.0/files/802003/1chxBO-00013y-4C.zip)

**Comment by shawniverson** [comment]
What are the chances that the unsafe tag removal in mailscanner is causing this?

**Comment by stefaweb** [comment]
For this one, I don't see tag removed.

```
Feb 26 12:40:06 antispam-dev MailScanner[3919]: New Batch: Scanning 1 messages, 49087 bytes
Feb 26 12:40:06 antispam-dev MailScanner[3919]: Virus and Content Scanning: Starting
Feb 26 12:40:06 antispam-dev MailScanner[3919]: Virus Scanning completed at 197271 bytes per second
Feb 26 12:40:06 antispam-dev MailScanner[3919]: Spam Checks: Starting
Feb 26 12:40:09 antispam-dev MailScanner[3919]: Message 1chxBO-00013y-4C from 51.254.72.90 (news@my.canal-msg.com) to domain.tld is spam, SpamAssassin (not cached, score=10.661, required 5, AWL 0.26, DKIM_SIGNED 0.10, DKIM_VALID -0.10, DKIM_VALID_AU -0.10, HTML_MESSAGE 0.00, MIME_HTML_ONLY 1.10, RAZOR2_CF_RANGE_51_100 0.36, RAZOR2_CF_RANGE_E8_51_100 2.43, RAZOR2_CHECK 2.50, RP_MATCHES_RCVD -0.00, URIBL_BLACK 1.70, URI_NO_WWW_BIZ_CGI 2.40)
Feb 26 12:40:09 antispam-dev MailScanner[3919]: Spam Checks: Found 1 spam messages
Feb 26 12:40:09 antispam-dev MailScanner[3919]: Spam Actions: message 1chxBO-00013y-4C actions are store
Feb 26 12:40:09 antispam-dev MailScanner[3919]: Spam Checks completed at 18062 bytes per second
Feb 26 12:40:09 antispam-dev MailScanner[3919]: Deleted 1 messages from processing-database
Feb 26 12:40:09 antispam-dev MailScanner[3919]: Batch completed at 16534 bytes per second (49087 / 2)
Feb 26 12:40:09 antispam-dev MailScanner[3919]: Batch (1 message) processed in 2.97 seconds
Feb 26 12:40:09 antispam-dev MailScanner[3919]: MailWatch: Logging message 1chxBO-00013y-4C to SQL
Feb 26 12:40:09 antispam-dev MailScanner[3919]: "Always Looked Up Last" took 0.00 seconds
```

**Comment by stefaweb** [comment]
It crashed here when displaying the <style type="text/css">. A problem with `"` ?

```
Pour cesser de recevoir nos communications <a  href="http://my.canal-msg.com/tr/?id=1168723490c183150ad9c856ef10bc94a24dfb233e438bfe0a859f3fc1b55b4cc6613563a91ddde9">d&eacute;sabonnez-vous</a><br>
		Pour visualiser correctement ce message, acc&eacute;dez &agrave; la <a  href="http://my.canal-msg.com/mr/?id=1168723490c183150ad9c856ef10bc94dcb9591c0787b34484c57bb700000645df37645c47be245933cb68092c1ff310">version en ligne</a>
	</font>
</div>        
    <style type="text/css">
		p{
			margin:10px 0;
			padding:0;
		}
```

**Comment by stefaweb** [comment]
The problem seems in viewpart.php not viewmail.php. The css have been lost somewhere.

```
		Pour visualiser correctement ce message, acc&eacute;dez &agrave; la <a  href="http://my.canal-msg.com/mr/?id=1168723490c183150ad9c856ef10bc94dcb9591c0787b34484c57bb700000645df37645c47be245933cb68092c1ff310">version en ligne</a>
	</font>
</div>        
    
		p{
			margin:10px 0;
			padding:0;

```

**Comment by shawniverson** [comment]
What about this in conf.php?

define('ALLOWED_TAGS', '<a><br><b><body><div><font><h1><h2><h3><h4><head><html><i><li><ol><p><small><span><strong><table><title><tr><td><th><u><ul>');

**Comment by stefaweb** [comment]
Great shawniverson!

No `<style>` in ALLOWED_TAGS. I added it. Work fine.

Do we need to add it by default in conf.php.example or can we consider this a security mesure?

**Comment by stefaweb** [comment]
But if not <style> in ALLOWED_TAGS, we normal usage will be to do not display the css on the screen.

**Comment by shawniverson** [comment]
I'm not sure a style tag is any sort of threat.  I'm more concerned about script tags and the like.

**Comment by Skywalker-11** [comment]
You can use css to load additional files eg. fonts but I don't think that it is a thread. Also we can prevent loading of external sites by using `<iframe sandbox ...` see [here](https://www.w3schools.com/tags/att_iframe_sandbox.asp)

**Comment by stefaweb** [comment]
Found this to remove the content of not allowed tag.

```
function strip_tags_content($text, $tags = '', $invert = FALSE) { 

  preg_match_all('/<(.+?)[\s]*\/?[\s]*>/si', trim($tags), $tags); 
  $tags = array_unique($tags[1]); 
    
  if(is_array($tags) AND count($tags) > 0) { 
    if($invert == FALSE) { 
      return preg_replace('@<(?!(?:'. implode('|', $tags) .')\b)(\w+)\b.*?>.*?</\1>@si', '', $text); 
    } 
    else { 
      return preg_replace('@<('. implode('|', $tags) .')\b.*?>.*?</\1>@si', '', $text); 
    } 
  } 
  elseif($invert == FALSE) { 
    return preg_replace('@<(\w+)\b.*?>.*?</\1>@si', '', $text); 
  } 
  return $text; 
} 
```

**Comment by stefaweb** [comment]
A volunteer to do housework in viewmail.php/viewpart.php? 😀

**Comment by endelwar** [comment]
This should be replaced by a proper HTML parser like in this example http://stackoverflow.com/a/2630219/1139600

**Comment by stefaweb** [comment]
@endelwar: could you just add <style> in ALLOWED_TAGS? We will avoid questions.

**Comment by endelwar** [comment]
`style` tag can be used as attack vector, not going to add it in default list of allowed tag, the sysadmin is free to add or remove tags in that list when she/he configure the system.

see https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet#STYLE_sheet
