### ISSUE TITLE
Problem in /var/spool/MailScanner/incoming/SpamAssassin-Temp

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#610]
Hello!

Need urgent help.

SpamAssassin temp files are not deleted.

I've tens of directory/file as ".spamassassin7077pXSUZltmp" in  /var/spool/MailScanner/incoming/SpamAssassin-Temp

Do you know where to look to correct the problem?

**Comment by stefaweb** [comment]
I've may be found the source of the problem.

If `Quarantine Infections = yes` in Mailscanner, the temp directories and the files inside are not deleted.

**Comment by stefaweb** [comment]
Still not found.

I've done a cron with `find /var/spool/MailScanner/incoming/SpamAssassin-Temp -name '.spamassassin*' -ctime +1 -print | xargs rm -R .spamassassin*` as temporary fix.

I don't have this problem with my old prod server with MailScanner 4.85.2-3 and spamassassin 3.3.2-5+deb7u3.

**Comment by stefaweb** [comment]
Not related to MailWatch. I close.

**Comment by Lichengchang** [comment]
@stefaweb 
Hi,
I encountered the same problem
Could you tell me how to resolve the problem?

**Comment by stefaweb** [comment]
Hi @Lichengchang!

I just added this to crontab.

```
# To delete tmp files in SpamAssassin-Temp
@hourly /usr/bin/find /var/spool/MailScanner/incoming/SpamAssassin-Temp -name '.spamassassin*' -mmin +30 -print | xargs rm -rf
```
