### ISSUE TITLE
Problem with viewmail.php from quarantine report (Fatal error)

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#614]
When I click on a message listed in the quarantine report:

`https://host.domain.tld//viewmail.php?id=1clJ9n-0006MK-0k`

I got in the MailWatch GUI:

`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 48682974 bytes) in /var/www/html/mailscanner/lib/pear/Mail/mimeDecode.php on line 442`

But if I enter "1clJ9n-0006MK-0k" directly in the search ID box, no problem, no error message. The message detail is well printed on screen.

**Comment by asuweb** [comment]
By search ID box do you mean the one at the top left of the screen?

**Comment by stefaweb** [comment]
Yes

Also, look the double '//' in URL of the quarantine report link.

**Comment by stefaweb** [comment]
But why viewmail.php and not detail.php in report?

**Comment by asuweb** [comment]
Ok, but the search box returns detail.php and not viewmail.php so I don't see the relation?

The out of memory is occurring on a call to preg_match, which is used to split the headers and body of the email - is the email particularly large?

**Comment by stefaweb** [comment]
Yes, it's large.

When I'm in detail.php?id=1clJ9n-0006MK-0k and click at the bottom on "message" (viewmail.php?id=1clJ9n-0006MK-0k), I've the same error.

The mail is not a spam. Juste a regular mail with a very big PDF attachment (30Mo).

**Comment by asuweb** [comment]
Report has always linked to viewmail - presumably because an end user isn't in the slightest interested in the headers, but only what the email contains

**Comment by stefaweb** [comment]
Ok, I understand for detail/viewmail. Best to go directly to viewmail.

**Comment by stefaweb** [comment]
> The out of memory is occurring on a call to preg_match,

Do we have a solution to ovoid this.

I can put more memory but it's not the best solution. What will append if we receive a 100Mo mail?  ;-)

**Comment by asuweb** [comment]
Possibly we need to look at moving away from pear where possible. There are numerous reports and it's acknowledged in the pear mail package that mimeDecode it isn't the most efficient method of parsing emails. 

There are alternative ways to do it. Need to check where mimeDecode is currently used.

I'll have a look later or tomorrow

**Comment by stefaweb** [comment]
And this ?

http://php.net/manual/en/book.mailparse.php

**Comment by asuweb** [comment]
Yes, mailparse is one solution I had in mind.  The downside is it requires installation of PECL extensions, which ideally we'd like to avoid.

**Comment by asuweb** [comment]
The underlying cause of this issue is the large attachment size, which possibly isn't all that common as often large attachments are blocked by policy at an SMTP level.  

I'm not suggesting it shouldn't be fixed, just that it might wait until v2 or post 1.20.  It's probably going to need a fairly large re-write to replace PEAR functions for this.

@endelwar - any thoughts on this one?

**Comment by endelwar** [comment]
@asuweb I've to carefully test both `mailparse` and `imap_mime_header_decode`, but I think that the latter is easyer to install as imap extension is pretty common packaged in distribution.

All this is work for V2

**Comment by Skywalker-11** [comment]
@endelwar do you want to set milestone to v2?
