### ISSUE TITLE
Mailwatch cluster: No status mail queues

### ISSUE THREAD

**Issue by rebirther** [mailwatch/MailWatch#628]
Why is there no mail queue status for the entire cluster?

I use 1 mailwatch-server for DB + 2 mailwatch-servers to send messages.
As a result, I see the queue only within one server.
Is it a mistake or is conceived?

**Comment by asuweb** [comment]
Which MTA are you using (Sendmail/Postfix/Exim)?

If postfix, then there is no current way to do it as we don't store the active queue in the database.  And also postfix only uses one queue, so differentiating between inbound and outbound isn't possible.

With sendmail or Exim, a cron script is provided which will record the active queues in the database, so it should work in your case (assuming you aren't using postfix).

It is possible we could also provide database logging for postfix, as it would be useful - it'll just require some more thought.

**Comment by rebirther** [comment]
Postfix is used.
I also saw that on those servers that are used for sending, there are both "Inbound" and "Outbound". That is, two lines on Postfix.

And unless it is impossible to send RPC on all existing nodes, asking for them thereby the mail queue?

**Comment by Skywalker-11** [comment]
Can you try [https://github.com/Skywalker-11/1.2.0/commits/feature/postfixrpccount](https://github.com/Skywalker-11/1.2.0/commits/feature/postfixrpccount)

It adds the ability to show the number of incoming/outgoing mails  in postfix on remote hosts by rpc. You have to define an additional constant in the conf.php on the server you are using for the gui:
`define('RPC_REMOTE_SERVER', 'other.example.com 10.0.0.2');`

The value is a space seperated list with servers which shall be included in that counting (you also have to specify the localhost server if it runs postfix itself). It can be fqdn or ips.

**Comment by Skywalker-11** [comment]
@rebirther have you tried this?

**Comment by rebirther** [comment]
I tried it. The GUI does not work for me because of this error:
syntax error, unexpected '[' in /var/www/functions.php
`$rsp = xmlrpc_wrapper(RPC_REMOTE_SERVER[$i]);`

**Comment by Skywalker-11** [comment]
I have updated the code in that branch already that fixed that error.
These are the current files: 
[https://github.com/Skywalker-11/1.2.0/blob/feature/postfixrpccount/mailscanner/rpcserver.php](https://github.com/Skywalker-11/1.2.0/blob/feature/postfixrpccount/mailscanner/rpcserver.php)
[https://github.com/Skywalker-11/1.2.0/blob/feature/postfixrpccount/mailscanner/functions.php](https://github.com/Skywalker-11/1.2.0/blob/feature/postfixrpccount/mailscanner/functions.php)

**Comment by rebirther** [comment]
@Skywalker-11 thanks, it helped.

**Comment by Skywalker-11** [comment]
@rebirther Is it working as expected?

**Comment by Skywalker-11** [comment]
@rebirther can we close this?

**Comment by rebirther** [comment]
@Skywalker-11 yes

**Comment by asuweb** [comment]
@Skywalker-11 - This doesn't seem to work in the current dev version - at least not on my setup?

**Comment by Skywalker-11** [comment]
I just tested it and it work with develop.
These settings are important:
RPC_RELATIVE_PATH (path on remote)
RPC_ALLOWED_CLIENTS
RPC_REMOTE_SERVER (hostname/ip of remote)
DISTRIBUTED_SETUP true

**Comment by Skywalker-11** [comment]
Remember that it still is only the status (messages count of in/out queues). The queues themself aren't fetched over rpc yet so that postfixmailq.php stays empty.
![image](https://cloud.githubusercontent.com/assets/11180862/25182586/65505ce8-2515-11e7-9339-d9cdf56859cd.png)

**Comment by asuweb** [comment]
Ahh OK, I see. It only works if distributed setup is true. Which isn't true in my case, as all nodes run mailscanner and mailwatch.

**Comment by Skywalker-11** [comment]
We could replace the check of DISTRIBUTED_SETUP with defined('RPC_REMOTE_SERVER') in line 527/531. Haven't thought of your situation when I wrote this.

**Comment by Skywalker-11** [comment]
Can we close this?
