### ISSUE TITLE
XML-RPC Error: Client <IP> is not authorized to connect

### ISSUE THREAD

**Issue by rebirther** [mailwatch/MailWatch#632]
`XML-RPC Error: Client <IP> is not authorized to connect`

Previously, for RPC, it was enough to assign an IP (which can be connected) to RPC_ALLOWED_CLIENTS.
But on 1.2.0 RC5 it does not work.

Settings for RPC changed?

![123](https://cloud.githubusercontent.com/assets/23431941/23824146/dbacf062-06a3-11e7-8d75-f664e148f462.png)

The query itself goes away, but in the Apache logs on ...229 here it is:
`X.X.X.156 - - [11/Mar/2017:21:40:45 +0700] "POST /mailscanner/rpcserver.php HTTP/1.0" 200 504 "-" "XML-RPC for PHP 3.0.0.beta"`

**Comment by Skywalker-11** [comment]
Can you try to add both IPs of the sending and receiving servers in conf.php on each server and try again?

**Comment by Skywalker-11** [comment]
@rebirther any news on this?

**Comment by rebirther** [comment]
@Skywalker-11 thanks. Your advice has helped.

**Comment by Skywalker-11** [comment]
Can you let this open for now because we either have to change the description to match that or fix the logic

**Comment by asuweb** [comment]
I'm having this issue as well.  

It seems to me the logic might be slightly incorrect.  I've have added both IP's to the list of allowed clients, but still the issue persists.

Interestingly - the word "client" to me means the connecting server so in this case the IP being displayed in the error should be that of the connecting server (i.e, the one making the RPC call), however in my case, the IP being displayed as not authorized is an alias IP on the remote server, which is the IP that postfix is currently bound to.

**Comment by Skywalker-11** [comment]
@asuweb just to confirm you have a situation like this:
Server1: IP 192.168.1.1, with MailWatch
Server2: IP 192.168.1.2, 192.168.1.3(alias IP) with Postfix+MailWatch

conf.php contains for both servers `define('RPC_ALLOWED_CLIENTS', '192.168.1.1 192.168.1.2');`  and you get a message that 192.168.1.3 is not allowed to query RPC calls?

Does it help to add 192.168.1.3 to the lists on both servers?

**Comment by asuweb** [comment]
Yes, more or less.  All 3 IP's are in the RPC_ALLOWED_CLIENTS on both servers.

**Comment by asuweb** [comment]
OK, so part of the issue is SSL related - I have `FORCE_SSL, true` but if I remove that, then it doens't give me the client denied anymore, I now get a `Not OK, 302` - so it seems that it's detecting a redirect somewhere now.

**Comment by asuweb** [comment]
I've solved the 302 issue - that was a vhost problem.  I can confirm this issue is SSL related.  RPC is working without it.  I suspect it's to do with secure cookies during the RPC calls.

**Comment by asuweb** [comment]
```
---GOT---
HTTP/1.1 200 OK
Date: Mon, 17 Apr 2017 17:38:55 GMT
Server: Apache/2.2.15 (CentOS)
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-Powered-By: PHP/5.6.30
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Set-Cookie: MailWatch=pjttihstoue9unldhdtah28lq2; path=/; secure; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Length: 285
Connection: close
Content-Type: text/html; charset=UTF-8

<methodResponse>
<fault>
<value>
<struct><member><name>faultCode</name>
<value><int>801</int></value>
</member>
<member>
<name>faultString</name>
<value><string>Client 123.123.123.123 is not authorized to connect.</string></value>
</member>
</struct>
</value>
</fault>
</methodResponse>
---END---
HEADER: date: Mon, 17 Apr 2017 17:38:55 GMT
HEADER: server: Apache/2.2.15 (CentOS)
HEADER: strict-transport-security: max-age=63072000; includeSubDomains; preload
HEADER: x-frame-options: SAMEORIGIN
HEADER: x-content-type-options: nosniff
HEADER: x-powered-by: PHP/5.6.30
HEADER: x-xss-protection: 1; mode=block
HEADER: set-cookie: MailWatch=pjttihstoue9unldhdtah28lq2; path=/; secure; HttpOnly
HEADER: expires: Thu, 19 Nov 1981 08:52:00 GMT
HEADER: cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
HEADER: pragma: no-cache
HEADER: content-length: 285
HEADER: connection: close
HEADER: content-type: text/html; charset=UTF-8
COOKIE: MailWatch=pjttihstoue9unldhdtah28lq2
---PARSED---
xmlrpcval::__set_state(array(
   'me' => 
  array (
    'struct' => 
    array (
      'faultCode' => 
      xmlrpcval::__set_state(array(
         'me' => 
        array (
          'int' => 801,
        ),
         'mytype' => 1,
         '_php_class' => NULL,
      )),
      'faultString' => 
      xmlrpcval::__set_state(array(
         'me' => 
        array (
          'string' => 'Client 123.123.123.123 is not authorized to connect.',
        ),
         'mytype' => 1,
         '_php_class' => NULL,
      )),
    ),
  ),
   'mytype' => 3,
   '_php_class' => NULL,
))
---END---

XML-RPC Error: Client 123.123.123.123 is not authorized to connect.

**Comment by Skywalker-11** [comment]
So the RPC call is done over http not https?

**Comment by asuweb** [comment]
Ok, done some further digging.

RPC works if `SSL_ONLY` is set to false.  It works in this case with `define('RPC_SSL', true);` and also `define('RPC_SSL', false);`

If we set `SSL_ONLY` to true - it fails regardless of the `RPC_SSL` setting.

**Comment by asuweb** [comment]
So somewhere, forcing `SSL_ONLY` to true is breaking RPC calls.

**Comment by asuweb** [comment]
This logic block doesn't seem correct to me...
```
function xmlrpc_wrapper($host, $msg)
{
    $method = 'http';
    // Work out port
    if (defined('SSL_ONLY') && SSL_ONLY) {
        $port = 443;
        $method = 'https';
    } elseif (defined('RPC_PORT')) {
        $port = RPC_PORT;
        if (defined('RPC_SSL') && RPC_SSL) {
            $method = 'https';
            if (!defined('RPC_PORT')) {
                $port = 443;
            }
        }
    } else {
        $port = 80;
    }
```

**Comment by shawniverson** [comment]
That looks ugly to me too, and would RPC_PORT set to 443 plus RPC_SSL set
be identical to SSL_ONLY?  So, why all these options?

Also, the inner most if statement will never evaluate true.

**Comment by Skywalker-11** [comment]
Yep. This will never be true.
``` if (!defined('RPC_PORT')) {
                $port = 443;
            }``` 

I think this should be a seperate elseif
 ```if (defined('RPC_SSL') && RPC_SSL) {
            $method = 'https';
            if (!defined('RPC_PORT')) {
                $port = 443;
            }
        }```

**Comment by asuweb** [comment]
Don't know where that post has gone, but yes, it's pretty ugly.  But actually it shouldn't break anything.

**Comment by asuweb** [comment]
I can't find any thing specific which would be breaking RPC with `SSL_ONLY` but something is

**Comment by asuweb** [comment]
Just updating to the latest dev version, in case there's something there

**Comment by Skywalker-11** [comment]
So this should be correct
```
 // Work out port
    if (defined('SSL_ONLY') && SSL_ONLY) {
        $port = 443;
        $method = 'https';
    } elseif (defined('RPC_SSL') && RPC_SSL) {
        $method = 'https';
        if (!defined('RPC_PORT')) {
            $port = 443;
        } else {
            $port = RPC_PORT;
        }
    } elseif (defined('RPC_PORT')) {
        $port = RPC_PORT;
    } else {
        $port = 80;
    }```

**Comment by asuweb** [comment]
That looks more logical - but I don't think it'll fix this issue, as in the case of `SSL_ONLY` the first block will be true, which it was  before - but still the same issue.  Weird!

I've updated to the latest dev, it hasn't fixed it

**Comment by shawniverson** [comment]
What about these two blocks in functions.php?

```
//Enforce SSL if SSL_ONLY=true
if (PHP_SAPI !== 'cli' && SSL_ONLY && (!empty($_SERVER['PHP_SELF']))) {
    if (!isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'on') {
        header('Location: https://' . sanitizeInput($_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']));
        exit;
    }
}
```
```
if (SSL_ONLY === true) {
    ini_set('session.cookie_secure', 1);
    $session_cookie_secure = true;
}
```

Does one of them cause XML_RPC to fail?

**Comment by Skywalker-11** [comment]
btw. shouldn't is_rpc_client_allowed in functions.php use `$_SERVER['REMOTE_ADDR']` to validate the client
 and not test himself 🤣

**Comment by asuweb** [comment]
I was just looking at that just now - it's doesn't make a sense the way it is...

**Comment by asuweb** [comment]
No, actually it should be server_addr - remote addr is the browser clients IP, which we don't want in this case.

**Comment by Skywalker-11** [comment]
But server_addr is the local server that receives the RPC request. Isn't he just checking if he himself is allowed to act as an RPC client? Shouldn't the server that receives the rpc call from the other server test if the other server is allowed to send requests? 
So server1: "rpc client" sends rpc call to server2
server2 receives rpc call checks if "rpc client" is allowed to send request (currently test if he himself is allowed to)

**Comment by asuweb** [comment]
Yes, the current logic appears to be missing an essential part - the address of the server making the call.  

What still doens't make sense though is why it doesn't work when `SSL_ONLY` is true - I'm still scratching my head with that.  But I agree, the current logic doens't seem to check what we should be checking.

**Comment by asuweb** [comment]
@shawniverson - neither of those 2 bits are causing this

**Comment by shawniverson** [comment]
@asuweb, well, I can see why you are scratching your head....

**Comment by asuweb** [comment]
Thanks for your help guys - was a local config issue with ServerAlias - might be worth adding to the documentation, but if you're using ip aliases with different hostnames, the hostname needs to be listed in the vhost ServerAlias else RPC will fail

**Comment by Skywalker-11** [comment]
Can be closed

**Comment by Skywalker-11** [comment]
@endelwar can you also close this?
