### ISSUE TITLE
envelope-from versus from in maillog:from_address

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#642]
Could you please check on your side?

On my server, the data stored in the from_address of table maillog is not the From: address but the envelope-from.

Normal or not?

**Comment by Skywalker-11** [comment]
Usually you want to know on behalf of what person the mail is send from and not what service actually sendet it. Especially normal end users who probably want to know it this way.
So I think it should be displayed that way. But the MailWatch should log both From: and the envelope-from. From: should be in the header column

**Comment by stefaweb** [comment]
This cause a problem with b/w list and others places too.

Header:
```
(envelope-from <bachelleriepa+caf_=user=domain.tld@gmail.com>)
From: MEDEF Evénement <envoi@communication.medef.fr>
```
From in GUI: `bachelleriepa+caf_=user=domain.tld@gmail.com`
From in B/W list: `bachelleriepa+caf_=user=domain.tld@gmail.com`
From in Quarantine Report: `bachelleriepa+caf_=user=domain.tld@gmail.com`

Very often, the envelope-from is autogenerated and used only one time (not repetitive). Specially when it's a mailing list and the B/W list doesn't work.

As this: `SRS0+85fc79ef7bab2ec5=856==@mult-e-shopping.org`

**Comment by stefaweb** [comment]
Found this in a forum

`MailScanner only operate on the envelope sender/recipients, hence that is what MailWatch sees as well.`

Bad news.

But when I see how it was difficult to correctly match the From: in the Header in mailq.php. I understand.
