### ISSUE TITLE
msgid regexp too restrictive?

### ISSUE THREAD

**Issue by Fonant** [mailwatch/MailWatch#652]
On my server some messages fail the msgid regexp test. Message IDs have 14 characters which can be any number or letter of any case.

Some messages match "[0-9B-DF-HJ-NP-TV-Zb-df-hj-np-tv-z.]{12,24}" but some don't.

I fixed the issue on my machine by changing the last pattern from "[0-9A-Za-z]{12}" to "[0-9A-Za-z]{12,14}"

**Comment by shawniverson** [comment]
Which MTA are you using?

**Comment by shawniverson** [comment]
That particular regex is for postfix long IDs as documented here.

http://www.postfix.org/postconf.5.html

"New queue files are created with names such as 3Pt2mN2VXxznjll. These are encoded in a 52-character alphabet that contains digits (0-9), upper-case letters (B-Z) and lower-case letters (b-z). For safety reasons the vowels (AEIOUaeiou) are excluded from the alphabet. The name format is: 6 or more characters for the time in seconds, 4 characters for the time in microseconds, the 'z'; the remainder is the file inode number encoded in the first 51 characters of the 52-character alphabet."

**Comment by Fonant** [comment]
Sendmail

**Comment by shawniverson** [comment]
Ahh, I see you changed the end one.  Yeah, that's for sendmail.  Looks like msgids for it can be longer than 12?  That is interesting, couldn't find good docs on that.

**Comment by shawniverson** [comment]
The sendmail docs actually contradict what you have as a msgid, but I think it should be changed to your method.  Probably just bad documentation.

**Comment by stefaweb** [comment]
@Fonant 

As Sendmail user, can you test this #657?

**Comment by stefaweb** [comment]
Hello! 
Does anyone use Sendmail to test?

**Comment by philrandal** [comment]
I've just encountered a postfix msgid with 13 characters before the period.

The regexp currently allows 12.

Line 4408 of functions.php needs changing from:

            if (preg_match('/^([A-F0-9]{7,12}\.[A-F0-9]{5}|[0-9B-DF-HJ-NP-TV-Zb-df-hj-np-tv-z.]{8,16}(?=z[A-Za-x]{4,8})|[0-9A-Za-z]{6}-[A-Za-z0-9]{6}-[A-Za-z0-9]{2}|[0-9A-Za-z]{12,14})$/',

to

            if (preg_match('/^([A-F0-9]{7,13}\.[A-F0-9]{5}|[0-9B-DF-HJ-NP-TV-Zb-df-hj-np-tv-z.]{8,16}(?=z[A-Za-x]{4,8})|[0-9A-Za-z]{6}-[A-Za-z0-9]{6}-[A-Za-z0-9]{2}|[0-9A-Za-z]{12,14})$/',

or maybe even more than 13.

**Comment by Skywalker-11** [comment]
Mailscanner also allows up to 20 characters before the period: [https://github.com/MailScanner/v5/blob/master/common/usr/share/MailScanner/perl/MailScanner/Postfix.pm](https://github.com/MailScanner/v5/blob/master/common/usr/share/MailScanner/perl/MailScanner/Postfix.pm)

**Comment by endelwar** [comment]
Let's match with MailScanner: if somedays a message come up with 21 chars it won't pass MailScanner, and thus won't arrive on MailWatch

**Comment by shawniverson** [comment]
I think it should be set to 20.  I bet it grows in size over time.

**Comment by shawniverson** [comment]
@endelwar year 10,000 bug?, haha!

**Comment by endelwar** [comment]
> year 10,000 bug?, haha!

It's a serious thing, there is also a RFC: https://tools.ietf.org/html/rfc2550 😄😄😄

**Comment by oskarkender** [comment]
In Centos 8.2 with Sendmail 8.15.2 the length of the msgid is 15 characters

if (preg_match('/^([A-F0-9]{7,20}\.[A-F0-9]{5}|[0-9B-DF-HJ-NP-TV-Zb-df-hj-np-tv-z]{8,20}|[0-9B-DF-HJ-NP-TV-Zb-df-hj-np-tv-z.]{8,20}\.[A-F0-9]{5}|[0-9A-Za-z]{6}-[A-Za-z0-9]{6}-[A-Za-z0-9]{2}|[0-9A-Za-z]{12,15})$/',

Is right for me.

**Comment by endelwar** [comment]
@oskarkender can you provide a 15 chars message id generated by Sendmail 8.15.2?

**Comment by oskarkender** [comment]
0A9CdqOg1157377
0A9EqX3o1219367

**Comment by endelwar** [comment]
Thanks, I'm going to make a new release soon
