### ISSUE TITLE
For Sendmail user, some code to test #656

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#657]
I modified the code to print the Sendmail queue in GUI in #656 PR.

Use direct `sendmail -bp` command to print Sendmail queue in GUI instead of SQL query.

To be tested by Sendmail user.

**Comment by Fonant** [comment]
Sorry, the change only seems to affect a distributed MailWatch setup, which I don't have.

**Comment by stefaweb** [comment]
Oops, it seems that I activated the wrong lines.

I updated the PR.

If working, I will add the constants in config.php.

**Comment by Fonant** [comment]
Two issues:

1. Syntax error, missing "(" after preg_match on two lines.
2. For sudo to work I need to add apache to /etc/sudoers. I'd rather only allow apache to run "/usr/bin/mailq" (which on RHEL?CentOS is a set of symbolic links via the "alternatives" system to /usr/sbin/sendmail.sendmail) and not "/usr/sbin/sendmail". Could we make this command a configuration option, with "/usr/bin/mailq" the default?

**Comment by stefaweb** [comment]
1. was corrected in PR.

2. if work, I plan to add this in config.php

```
define('SENDMAIL_QUEUE_IN', '/usr/bin/mailq  -bp -OQueueDirectory=/var/spool/mqueue.in');
define('SENDMAIL_QUEUE_OUT', '/usr/bin/mailq -bp');

```
As this, people can change not if needed (as for Exim).

For sudo, its already done. I've just to correct bin path.

https://github.com/mailwatch/MailWatch/blob/develop/tools/sudo/mailwatch

**Comment by stefaweb** [comment]
Added SENDMAIL_QUEUE_ constants in last commit.

**Comment by stefaweb** [comment]
Merged.
