### ISSUE TITLE
Some Subject not decoded in GUI

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#658]
I receive some mail with subject not decoded. I don't know if we can correct this.

![capture d ecran 2017-03-21 a 08 44 31](https://cloud.githubusercontent.com/assets/12907102/24137136/b9a21454-0e12-11e7-92e8-d3d36b08ad3f.png)

The Header in database:

```
From: "Mag Dunn" <omermutcali@spectr-omsk.ru>
To: <user@domain.tld>
Subject: èÏÔÉÔÅ ËÕÐÉÔØ ÂÉÔËÏÉÎÙ? óÅÊÞÁÓ ÓÁÍÏÅ ×ÒÅÍÑ!
Date: Tue, 21 Mar 2017 15:38:45 +0800
MIME-Version: 1.0
Content-Type: text/plain;
     format=flowed;
     charset="KOI8-R";
     reply-type=original
Content-Transfer-Encoding: 8bit
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2800.1106
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2800.1106
```

**Comment by Skywalker-11** [comment]
do you know how that header should look like when decoded?

**Comment by stefaweb** [comment]
I got this but using the charset wrote in Header.  In Subject ($text), we don't have the charset.

```
<?php
$text = "\350\317\324\311\324\305 \313\325\320\311\324\330 \302\311\324\313\317\311\316\331? \363\305\312\336\301\323 \323\301\315\317\305 \327\322\305\315\321!";

$elements = imap_mime_header_decode($text);
for ($i=0; $i<count($elements); $i++) {
    echo "Charset: {$elements[$i]->charset}\n";
    echo "Text: {$elements[$i]->text}\n";
    //$string = @iconv($elements[$i]->charset, 'UTF-8//TRANSLIT//IGNORE', $elements[$i]->text);
    $string = @iconv('KOI8-R', 'UTF-8//TRANSLIT//IGNORE', $elements[$i]->text);
    echo "Decoded Text: " . $string . "\n";
}
?>
```

Result:

```
Charset: default
Text: ������ ������ ��������? ������ ����� �����!
Decoded Text: Хотите купить биткоины? Сейчас самое врем
```

default = ASCII

**Comment by Skywalker-11** [comment]
Is it correct that if the subject is not encoded as ASCII it should include the charset (=?...) ? If thats the case you can check for that to see if you have to decode it

**Comment by stefaweb** [comment]
In log, I don't see the charset.

`2017-03-21 08:41:11 1cqEPm-0000Hj-Nt <= omermutcali@spectr-omsk.ru H=(223.155.194.159) [223.155.194.159]:1086 I=[62.210.166.5]:25 P=smtp S=1377 M8S=0 id=000301d2a216$82297160$8034ed8f@HQ4JYZ9GCU8B4I4 T="\350\317\324\311\324\305 \313\325\320\311\324\330 \302\311\324\313\317\311\316\331? \363\305\312\336\301\323 \323\301\315\317\305 \327\322\305\315\321!" from <omermutcali@spectr-omsk.ru> for user@domain.tld`

**Comment by Skywalker-11** [comment]
Is this happening in develop or also with #634

**Comment by stefaweb** [comment]
I've to try for #634. The problem is that the message is a very dirty dangerous code from Russian guys. Difficult to liberate it to user. 

I may be use "alternate recipient" to liberate it? I don't remember if when we use  "alternate recipient", the mail goes only to the  "alternate recipient" or also to the original recipient?

**Comment by stefaweb** [comment]
I checked my code. If charset = "default" no decoding as default is ASCII.

```
                    if (strtolower($linePartArr[$j]->charset) === 'default') {
                        if ($linePartArr[$j]->text != " ") {
                            $convLine .= ($linePartArr[$j]->text);
                        }
                    } else {

```
The problem is in develop and in #634.

**Comment by Skywalker-11** [comment]
Can we close?
