### ISSUE TITLE
Wishlist: display From: when envelope-from do not exist

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#659]
Currently for bounce and other mail without `envelope-from`, the `from_address` in database is empty and nothing is printed in GUI.

It will be nice to display in GUI the `From:` (stored in headers field) when` envelope-from` is empty.

For pages: status.php, quarantine.php, rep_message_listing.php and rep_message_ops.php

I've done this for Sendmail and Exim Queue mailq.php page (PR # #634).

**Comment by asuweb** [comment]
Would you propose this to be stored in the DB (via Message.pm) or just displayed at runtime?

**Comment by stefaweb** [comment]
Via Message.pm seems the best (info got at the source...) as the header stored in MailWatch database is already modified (decoded and some parts removed).

But you know as its difficult to analyse the source header... ;-)

Take it from maillog:headers is may be easiest and don't need a new version of MailScanner.

I let you judge that.  😎

**Comment by asuweb** [comment]
Should be possible in Message.pm.  If we check that "From" is not empty and if it is, do a regex on the header to find `From:...`

Should work

**Comment by stefaweb** [comment]
Its seems better to have a specific field in database to store the From:.

from_address (to store From:)
envelope_from (to store envelope-from)

But we need to modify code in MW where we currently use from_address to display envelope-from.

With that we can later choice if we want to print From: or envelope-from in GUI.

**Comment by asuweb** [comment]
Yes, ok - that makes sense and seems logical.

**Comment by stefaweb** [comment]
And evaluate the impact of this on White / Black List code.

**Comment by asuweb** [comment]
What we really need on the team is someone who likes perl....

**Comment by stefaweb** [comment]
The problem is that Perl is no longer studied at high school. They study Python instead.
