### ISSUE TITLE
Part 11 not found 

### ISSUE THREAD

**Issue by spec1re** [mailwatch/MailWatch#697]
I have this in viewmail.php since 1.20 Final

![unbenannt](https://cloud.githubusercontent.com/assets/11883076/24282677/f29f85b4-1058-11e7-9cef-85258fa3cc0d.JPG)

**Comment by stefaweb** [comment]
Should be solved in last develop version.

Be patient, version 1.2.1 is coming.

**Comment by spec1re** [comment]
Thank you stefaweb, I'm will wait. :)

**Comment by shawniverson** [comment]
I'm seeing this on the latest develop as well.

"Part 21 not found"

**Comment by shawniverson** [comment]
Found issue, preparing PR

**Comment by spec1re** [comment]
Looks good here, thanks. :)

**Comment by stefaweb** [comment]
can be closed.
