### ISSUE TITLE
Looking for translator!

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#698]
You are a native speakers of one of these languages, we need help translating MailWatch.

Spanish
Dutch
Italian
Portuguese

https://github.com/mailwatch/1.2.0/tree/develop/mailscanner/languages

@endelwar: can you post an advertising for this in the Mailing list?

**Comment by remkolodder** [comment]
I was already working on the dutch version, I’ll hope to get results soon-ish :)

**Comment by AntonyShaji** [comment]
Hi Stéphane, we have team of native translator for Spanish, Dutch, Italian Portuguese etc. We deliver quality and on time. Kindly send us your document to contacts@asimolinguistics.com skype : antonyshaji17

**Comment by Skywalker-11** [comment]
@AnthonyShaji each language file is located at mailwatch/languages/

The languages de, en, fr are translated already. Feel free to look at the other language files or create an other language by copying an existing file and adjusting the strings.

**Comment by Skywalker-11** [comment]
@remkolodder Have you made progress in this?

**Comment by stefaweb** [comment]
May be @shawniverson can place a call on the EFA forum?

**Comment by ghost** [comment]
@stefaweb Gladly!  A little late to the effort, but no time like the present, right?

**Comment by ghost** [comment]
https://forum.efa-project.org/viewtopic.php?f=19&t=3342&p=13363

**Comment by gunterunq** [comment]
Hello, in the last days I made the translation to Latin American Spanish, and I share it so that you can include it in the project. Thank you.
[es.php.zip](https://github.com/mailwatch/MailWatch/files/2870268/es.php.zip)

**Comment by endelwar** [comment]
Thanks @gunterunq ! I'm going to name this translation "es-419", as per ISO 639, do you agree?

**Comment by gunterunq** [comment]
> Thanks @gunterunq ! I'm going to name this translation "es-419", as per ISO 639, do you agree?

Ok ! And please adjust the header info... I forgot it !
