### ISSUE TITLE
Top virus in GUI

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#713]
How is working this feature?

Or this feature is really working?

I got 2 virus today but "top virus" is empty.

![capture d ecran 2017-03-29 a 17 49 33](https://cloud.githubusercontent.com/assets/12907102/24463864/4f49e69e-14a8-11e7-8d5e-e601278f3cba.png)

(with a patched RC5)

**Comment by shawniverson** [comment]
I vaguely recall something up with that when more than one virus scanner
was in use....can't seem to find that thread....

**Comment by Skywalker-11** [comment]
You're right only the first virus scanner is used in MailWatch

**Comment by stefaweb** [comment]
I've only one virus scanner installed (clamav).

**Comment by Skywalker-11** [comment]
Are they correctly shown on the report page?

**Comment by stefaweb** [comment]
Yes, if I selected today and virus, I got them.

![capture d ecran 2017-03-29 a 20 55 35](https://cloud.githubusercontent.com/assets/12907102/24471359/2a38329c-14c2-11e7-952d-32b5f364ffc0.png)

**Comment by stefaweb** [comment]
This was working in the past.

**Comment by Skywalker-11** [comment]
Does this return something
`SELECT report FROM maillog WHERE virusinfected>0 AND date = CURRENT_DATE()`

**Comment by stefaweb** [comment]
Yes.

```
Clamd: 57Callie.js was infected: Txt.Downloader.Nemucod-14748 MailScanner: JScript Scripts are dangerous in email (57Callie.js) ,Clamd: 57Callie.js was infected: Txt.Downloader.Nemucod-14748 MailScanner: JScript Scripts are dangerous in email (57Callie.js)

Clamd: 58Elfrida.js was infected: Txt.Malware.Agent-1813827 MailScanner: JScript Scripts are dangerous in email (58Elfrida.js) ,Clamd: 58Elfrida.js was infected: Txt.Malware.Agent-1813827 MailScanner: JScript Scripts are dangerous in email (58Elfrida.js)

```

**Comment by endelwar** [comment]
> This was working in the past.

no, never did. the actual code return none if top 2 virus count is equal
https://github.com/mailwatch/1.2.0/blob/f79b89d1413872e0762fb88d6a5c25e300897e2b/mailscanner/functions.php#L1270-L1273

**Comment by stefaweb** [comment]
Ok, I've only 2 virus. Need 3 MINIMUM...

I close.

**Comment by endelwar** [comment]
that won't do either: if you have 100 different viruses all with an entry "none" is returned because there isn't a top virus: they have all equal count.

some code need to be written to return something useful, like the 2, 3, or 4 viruses that appeared first or something like that when count is tie

reopening.

**Comment by Skywalker-11** [comment]
Are you sure you are using clamav and not clamd? The line start with `was infected` only applies to `clamavmodule`or `clamd` but not `clamav` (see functions.php line 141-200)

**Comment by stefaweb** [comment]
The deamon version clamd as well.

`clamav     496     1  0 mars29 ?       00:07:13 /usr/sbin/clamd --foreground=true`

**Comment by endelwar** [comment]
> The line start with was infected only applies to

I don't remember when, but clamav uniformed the output some time ago, see https://github.com/mailwatch/1.2.0/blob/develop/mailscanner/rep_viruses.php#L62-L63

**Comment by stefaweb** [comment]
Can this be closed?

**Comment by Skywalker-11** [comment]
Should be in fixed in develop but I didn't have enough test data

**Comment by stefaweb** [comment]
Ok. I closed. If the problem come back we can reopen.
