### ISSUE TITLE
Problem with session_start()

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#720]
With last develop.

`Notice: session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /var/www/html/mailscanner/login.php on line 37`

```
# ll /var/lib/php5/sessions/
-rw------- 1 mailwatch mailwatch 109 mars  31 11:26 sess_6vfvmt6vfah8u8gv4mmtroqac6
```

The mail watch vhost run as mailwatch/mailwatch using apache 2.3 + mpm_itk.

I rebooted the dev server to be sure.

**Comment by endelwar** [comment]
set `session.save_path` for this vhost to a path writable by mailwatch user

**Comment by stefaweb** [comment]
Works. Thanks.

**Comment by stefaweb** [comment]
But with default apache vhost (www-data), we will have the same problem.

```
# ll /var/lib/php5/
drwx-wx-wt 2 root root 192512 mars  31 12:00 sessions
```

We can may be create a 'session' directory in mailscanner/ directory and add a set for this in MW code?

**Comment by asuweb** [comment]
`session.save_path` is normally set in php.ini so there shouldn't be an issue with this in most setups.

**Comment by Skywalker-11** [comment]
It should be noticed somewhere in the docs. Maybe a separate section 'Troubleshooting'

**Comment by endelwar** [comment]
Yes @Skywalker-11, maybe in faq (or rename faq in "Troubleshooting" or "common problems").

this issue is present only on debian/ubuntu where garbage collection is disabled by default and a cron job clean the old sessions (always hated this...)

**Comment by stefaweb** [comment]
Is it normal to have only one session file if 2 users are connected?

**Comment by stefaweb** [comment]
I move my comments on session on #721. Something wrong somewhere.

**Comment by Skywalker-11** [comment]
Can be closed
