### ISSUE TITLE
Session expiry test

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#721]
With last develop, when I'm on status or queue, no auto disconnect. Well!

But if I stay on another page, no auto disconnect after 5 minutes!

I'm lost, the new session expiry time is in place or not?

**Comment by stefaweb** [comment]
Sometime I have only one session file, sometime not when I connect with more than one user. I try to understand. I investigate...

Is is not normal when we disconnect one user, the corresponding session file is not deleted?

session.save_path = /tmp

**Comment by shawniverson** [comment]
Which page are you on?

**Comment by shawniverson** [comment]
When you are on a static page, i.e. Quarantine, for example, "auto
disconnect" doesn't really happen until you try to do something or move
away from the page after 5 min.

We would have to introduce an inactivity script to the pages in order to
really auto disconnect.

**Comment by shawniverson** [comment]
The cookie is set to expire on browser close.  The cookie may still be present until garbage collection occurs.

**Comment by shawniverson** [comment]
Are you in the same browser trying to log in as different users, or different browsers (or separate incognito/private windows)?

Chances are that if you try to log in as multiple users in the same browser, the most recent login will be the active one (which should result in the previous session getting kicked).

**Comment by stefaweb** [comment]
I restarted from scratch.

I reboot the server.
No session file in /tmp.
With a browser I go login page -> I got one session file (why ?, I not logged)
I open the session with admin1 -> I still have the same session file
With a another browser I go to login page -> I got new session file
I open the session with admin2 -> the session file from login is delete and replaced with a new one.

Concerning the session expiry. I doing new test. I'll you know.

**Comment by shawniverson** [comment]
> With a browser I go login page -> I got one session file (why ?, I not logged)

That is correct, there is a pre-login session created.

> I open the session with admin1 -> I still have the same session file

You will, but the session id will regenerate upon login.

> With a another browser I go to login page -> I got new session file

Yes

> I open the session with admin2 -> the session file from login is delete and replaced with a new one.

Yes

**Comment by stefaweb** [comment]
Ok for this. I prefer to be sure that all is correct.

**Comment by shawniverson** [comment]
@stefaweb aren't sessions fun?  Glad you are going deep with this.  I appreciate the testing 👍

**Comment by stefaweb** [comment]
For session expiry.

I'm on status and queue pages. No session expiry. Ok.

I'm on sf_version.php. I wait 7 minutes (don't touch the page). Nothing append. Nothing move.
I click on report menu. I go to login page. OK 

But the best in term of ergonomic will be an inactivity script to the pages in order to auto disconnect and go to login page.

I'm on status page. I wait 7 minutes. I click on status page (menu). I'm still on status page (not disconnected). OK

I'm on sf_version.php. I wait 7 minutes (don't touch the page). Nothing append. Nothing move.
I click on status menu. I go to login page. OK 

I'm on status page. I wait 7 minutes. I click on report page. I go to report page. Is it normal? 

For me not. We must be disconnected and go to login page. 

In fact personally, I prefer to stay connected for this case but in term of security, it's not good.

**Comment by shawniverson** [comment]
> I'm on status page. I wait 7 minutes. I click on report page. I go to report page. Is it normal?

Yes, because your session is getting refreshed every STATUS_REFRESH seconds, so you remain logged in.  

I am following @endelwar in his post to #708:

> we should follow this path:

> reduce the session duration to max 5 minutes for all

> restart session count down on user interaction (page changed or manually refreshed, not on bored playing with a select or checkbox)

> pages with autorefresh on (status, mail queue) should follow the rule above, obviously without manual interaction

> if STATUS_REFRESH > session time out we should use the latter as page refresh timeout (minus some seconds to let the browser do its job in time)

**Comment by stefaweb** [comment]
And I wrote in #662.  😀

> If you are on status/queue, no disconnect when session end. status/queue pages still continue to show mail flux and refresh.
> If your click on something on the status/queue page after session end (detail or menus), the system go to login page. 

The "inactivity script" to return automatically to the login page is not important. I've see 2 schools here. Some systems goes automatically to the login page, some others systems stay on the page and just print a message "session expired, you should login again".

**Comment by shawniverson** [comment]
@stefaweb I prefer the inactivity approach myself, personally I don't like thinking the page is active, trying to do something, and them poof! login page 😕 Would be a great thing to add eventually.  As for session tracking of individual pages, yeah, that may be quite a bit of work, as it is going beyond just the session itself and down to individual pages.

**Comment by stefaweb** [comment]
Synology is doing the second approach and the system crash due to the big ajax code. In many cases, you need to quit the browser or you stay in a loop and can't reconnect.

**Comment by Skywalker-11** [comment]
Simplest way to do that redirext would be to use js `setTimeout` and do the redirect to the login page with it. It could be called ob every page by adding it to html_start ib functions.php

**Comment by Skywalker-11** [comment]
PR #724 implements the auto redirect to the login page

**Comment by stefaweb** [comment]
Hello!
Last code seems to work fine.

**Comment by Skywalker-11** [comment]
can this be closed?

**Comment by stefaweb** [comment]
Done.
