### ISSUE TITLE
SA Learning and Releasing not working in detail.php

### ISSUE THREAD

**Issue by saxos1983** [mailwatch/MailWatch#722]
When I try to SA learn or release a message, nothing happens when I press the Submit button.
The same page is shown but no information text if the action was successful.
The message is also not released.

The actions are working in rep_message_ops.php under Reports --> Message Actions

This worked before the upgrade to 3.0.1.9.

**Comment by shawniverson** [comment]
Please post this over at https://efa-project.org since it appears to be
related to eFa.

**Comment by spec1re** [comment]
I have the same issue here with MailWatch and FreeBSD.

**Comment by shawniverson** [comment]
In that case, I'll pull latest develop and see what is happening...

**Comment by shawniverson** [comment]
I am having trouble reproducing this issue on latest develop:

Release: message released to shawniverson@example.org
SA Learn Learned tokens from 1 message(s) (1 message(s) examined)

**Comment by shawniverson** [comment]
Can someone share a message header (with sensitive info removed) of a message that will not release in detail.php?

**Comment by shawniverson** [comment]
Oh, I was on the wrong page!  Yeah, found the issue.

**Comment by shawniverson** [comment]
Looks like ID isn't getting passed to do_message_ops.php properly....troubleshooting.

**Comment by shawniverson** [comment]
Problem found, preparing PR

**Comment by spec1re** [comment]
SA Learning still broken.

**Comment by stefaweb** [comment]
@spec1re 

Could you check with 1.2.2 version?

**Comment by spec1re** [comment]
@stefaweb 

sure give me a few mins.

**Comment by spec1re** [comment]
`Cannot open MailScanner configuration file (dienomsconf03)`

:(

**Comment by spec1re** [comment]
```
php /usr/local/www/mailscanner/upgrade.php
Cannot open MailScanner configuration file (dienomsconf03)
```
Same for upgrade.php

**Comment by Skywalker-11** [comment]
Where is your MailScanner config file located?
Can you check if `MS_CONFIG_DIR` in conf.php of MailWatch points to the correct folder?

**Comment by spec1re** [comment]
```
/usr/local/etc/MailScanner/MailScanner.conf

define('MS_CONFIG_DIR', '/usr/local/etc/MailScanner/');
```

**Comment by Skywalker-11** [comment]
What are the permissions of the MailScanner config and are they readable to the user you are running the upgrade script and the webserver?
`ls -l /usr/local/etc/MailScanner/MailScanner.conf`
`ls -l /usr/local/etc/MailScanner/conf.d/`

**Comment by spec1re** [comment]
```
-rw-r--r--  1 root  wheel  15880 Apr  3 12:19 /usr/local/etc/MailScanner/MailScanner.conf
-rw-r--r--  1 root  wheel  2409 Mar 17 12:02 extra.conf
```
Its all root and nginx/php is running as root as well here, I know its bad but this is how pfSense works and I'm the only one who has access to it via rules/policy.

**Comment by Skywalker-11** [comment]
Sorry, I can't reproduce it here. Can you create a separate issue and describe further which os etc. you are using?

**Comment by spec1re** [comment]
Okay, there you go. https://github.com/mailwatch/MailWatch/issues/725

**Comment by spec1re** [comment]
Finally upgraded to 1.2.2 but SA Learn still not working, when you click on learn its just does nothing beside reloading the page.

**Comment by Skywalker-11** [comment]
@spec1re It should change the view to this. Is that happening?
![image](https://cloud.githubusercontent.com/assets/11180862/24704054/47ef086c-1a06-11e7-93c2-52997c111a60.png)

**Comment by spec1re** [comment]
@Skywalker-11 - No, just the same page where you can see the header and select an action fo sa-learn.

![grafik](https://cloud.githubusercontent.com/assets/11883076/24709114/69207a28-1a08-11e7-90e8-6cfbdfccf6fa.png)

**Comment by stefaweb** [comment]
Works here with last develop.

**Comment by endelwar** [comment]
@spec1re can you try with english interface and see if the issue is  still there?

**Comment by spec1re** [comment]
@endelwar - Indeed with `define('LANG', 'en');` it works. :)

**Comment by stefaweb** [comment]
Hum, look for the `case` in the code. Translation going to far or badly managed.

**Comment by Skywalker-11** [comment]
This causes the problem
`if (isset($_POST['submit']) && deepSanitizeInput($_POST['submit'], 'url') === __('submit04')) {`

It usually is not a good idea to use language specific values for comparisons in the logic. Here `deepSanitizeInput($_POST['submit'], 'url')` elevates to `Besttigen` (removing the umlaut `ä`)

**Comment by endelwar** [comment]
> It usually is not a good idea to use language specific values for comparisons in the logic

indeed. All `<input type="submit">` must be converted to `<button type="submit">`

**Comment by stefaweb** [comment]
We have more code to change. Found others case with loc encoded in and one not translated.

```
mcp_rules_update.php:    echo '  <td align="center"><br><input type="submit" value="' . __('input26') . '"><br><br></td>' . "\n";
msre_edit.php:    echo '<input type="SUBMIT" name="submit" value="' . __('submit04') . '">' . "\n";
msre_edit.php:    TRH_Single('<input type="submit" name="submit" value="Save Changes">', 'colspan="' . MSRE_COLUMNS . '"');
sa_rules_update.php:    echo '<input type="submit" value="' . __('input13') . '"><br><br>';
user_manager.php:        echo '<tr><td class="heading">' . __('action_0212') . '</td><td><input type="reset" value="' . __('reset12') . '">&nbsp;&nbsp;<input type="submit" value="' . __('update12') . '"></td></tr>' . "\n";

```

**Comment by stefaweb** [comment]
Are these a problem?

```
detail.php:        if ($fieldn === __('receivedfrom04')) {
detail.php:        if ($fieldn === __('receivedvia04')) {
detail.php:        if ($fieldn === __('report04')) {
detail.php:        if ($fieldn === __('from04')) {
detail.php:        if ($fieldn === __('to04')) {
detail.php:        if ($fieldn === __('subject04')) {
detail.php:        if ($fieldn === __('spamrep04')) {
detail.php:        if ($fieldn === __('size04')) {
detail.php:        if ($fieldn === __('msgheaders04')) {
detail.php:        if ($fieldn === __('saautolearn04')) {
detail.php:        if ($fieldn === __('spam04') && !DISTRIBUTED_SETUP) {
detail.php:        if ($row[$f] === $yes && $fieldn === __('hscospam04')) {
detail.php:            if ($fieldn === __('mcprep04')) {
detail.php:        if ($row[$f] === $yes && $fieldn === __('listedrbl04')) {
```

**Comment by Skywalker-11** [comment]
Not necessary a problem. It only is a problem if the value comes from the client side. Nevertheless it is not a good practice to do so.

If we would like to enable the users to choose the language it has to be changed.

**Comment by stefaweb** [comment]
> If we would like to enable the users to choose the language it has to be changed.

Good idea for v2.

**Comment by Skywalker-11** [comment]
Should be fixed by now. @saxos1983 @spec1re can you verify that it's workingor does the problem still exist?

**Comment by saxos1983** [comment]
Thanks for the info. I'm on holiday but I will try to check that at the end of the next week.
Regards

**Comment by spec1re** [comment]
With the latest dev build, SA learning and releasing IS working fine here.

**Comment by Skywalker-11** [comment]
@saxos1983 did you test this?

**Comment by saxos1983** [comment]
Hi, sorry for the delay.
I switched back to German 'de' in conf.php and the SA Learning is still working as expected (like in English).

Thanks.
