### ISSUE TITLE
Uncaught exception 'mysqli_sql_exception'

### ISSUE THREAD

**Issue by Gusta-BH** [mailwatch/MailWatch#733]
Hello,

I'm getting the error described below when accessing the options under "Search and Report":

2017/04/05 10:50:10 [error] 658#0: *1113 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'mysqli_sql_exception' with message 'Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mailscanner.maillog.to_address' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by' in /srv/www/my.server.com/public_html/mailscanner_lLKgfdy98765edfghjnbfdshd1298765ybncgf/functions.php:948
Stack trace:
#0 /srv/www/my.server.com/public_html/mailscanner_lLKgfdy98765edfghjnbfdshd1298765ybncgf/functions.php(948): mysqli->query('\n SELECT\n  SUBS...')
#1 /srv/www/my.server.com/public_html/mailscanner_lLKgfdy98765edfghjnbfdshd1298765ybncgf/functions.php(3950): dbquery('\n SELECT\n  SUBS...')
#2 /srv/www/my.server.com/public_html/mailscanner_lLKgfdy98765edfghjnbfdshd1298765ybncgf/rep_top_recipient_domains_by_volume.php(83): printGraphTable('./images/cache/...', '\n SELECT\n  SUBS...', 'Top 10 Recipien...', Array, Array, Array, Array)
#3 {main}
  thrown in /srv/www/my.server.com/public_html/mailscann" while reading upstream, client: 200.199.131.221, server: my.server.com, request: "GET /mailscanner_lLKgfdy98765edfghjnbfdshd1298765ybncgf/rep_top_recipient_domains_by_volume.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "my.server.com", referrer: "https://my.server.com/mailscanner_lLKgfdy98765edfghjnbfdshd1298765ybncgf/reports.php"

Options Accessed:

Total Messages by Date
Top Sender Domains by Quantity
Top Sender Domains by Volume
Top Recipient Domains by Quantity
Top Recipient Domains by Volume

OS: Debian 8.7.1

Software Versions:

MailWatch Version: 1.2.2
MailScanner Version: 5.0.4
ClamAV Version: 0.99.2 
SpamAssassin Version: 3.4.0 
PHP Version: 5.6.30
MySQL Version: 5.7.17
NGINX: 1.10.3

The pages of the above options are interrupted in half, not showing the information and not loading the end of the page.

**Comment by asuweb** [comment]
If you run the follwing in the mysql command line, this will most likely fix the issue:

`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`

**Comment by Gusta-BH** [comment]
Thank you!

Solved problem.

Closing...

**Comment by endelwar** [comment]
Reopening as this have to be addressed: `ONLY_FULL_GROUP_BY` is standard in mysql 5.7.
We have 2 path:
- change sql_mode at runtime
- rewrite query to follow `ONLY_FULL_GROUP_BY` syntax

**Comment by asuweb** [comment]
@endelwar - yes, I see that now.  Strange it's only been reported now - can't be only one user using a version > 5.7.5

**Comment by stefaweb** [comment]
> rewrite query to follow ONLY_FULL_GROUP_BY syntax

MariaDB compatible ?

**Comment by asuweb** [comment]
It's not a default setting in MariaDB - it seems to have been introduced as standard in MySQL 5.7.5 or greater.

**Comment by endelwar** [comment]
> can't be only one user using a version > 5.7.5

Happened to me on my dev machine working on other projects, but I changed sql_mode  in my.cnf, and forgot about that

**Comment by stefaweb** [comment]
The sql engines diverge more and more. Not good.
Hope. Would not that end up as with browsers.   😀

**Comment by endelwar** [comment]
Implemented in f4e4b889dbcb4eb07f45df99924579e462a6011c

**Comment by Gusta-BH** [comment]
Unfortunately, for some reason, the above command only worked until the MySQL (or server) reboot, having to be repeated after each reboot. It looks like MySQL 5.7 restores the default option "sql_mode = ONLY_FULL_GROUP_BY" after each reboot. Correct me if you're wrong.

I also tested the [f4e4b88](https://github.com/mailwatch/MailWatch/commit/f4e4b889dbcb4eb07f45df99924579e462a6011c) implement, but it did not work for me.

For the tests that I performed, the command "SET GLOBAL sql_mode = (SELECT REPLACE (@@ sql_mode, 'ONLY_FULL_GROUP_BY', ''));" It can only be executed and it has effect with super privileges (root), being unable to execute it with the user of the database of MailWatch (without super privileges).

Regarding the command "SET sql_mode = (SELECT REPLACE (@@ sql_mode, 'ONLY_FULL_GROUP_BY', ''));" And which is included in the f4e4b88 implement, it can be executed but has no effect on the MailWatch database. Maybe that's why the implement did not work for me.

The solution I found was to disable the "ONLY_FULL_GROUP_BY" option by my.conf.

**Comment by Skywalker-11** [comment]
Can you give use the full sql query that causes the error?
I can be done by adding `error_log($sql);` in rep_top_recipient_by_volume at line 81 before `printGraphTable`. The query then will be logged in the webserver log

**Comment by Gusta-BH** [comment]
I have the following error, even with the f4e4b88 fix:

2017/04/09 16:27:16 [error] 1238#0: *921 FastCGI sent in stderr: "PHP message: 
 SELECT
  REPLACE(to_address,",",",\n") as name,
  COUNT(*) as count,
  SUM(size) as size
 FROM
  maillog
 WHERE
  from_address <> "" 		-- Exclude delivery receipts
 AND
  from_address IS NOT NULL     	-- Exclude delivery receipts
AND (1=1)

 GROUP BY
  to_address
 ORDER BY
  size DESC
 LIMIT 10" while reading upstream, client: 123.456.789.101, server: mail.test.com, request: "GET /mailscanner_098765sdERYUIJVC7545/rep_top_recipients_by_volume.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "mail.test.com", referrer: "https://mail.test.com/mailscanner_098765sdERYUIJVC7545/reports.php"
