### ISSUE TITLE
Options in messages operations do not select all the lines when clicking S/H/F/R

### ISSUE THREAD

**Issue by jch2os14** [mailwatch/MailWatch#738]
### Issue summary
See the subject.

### Steps to reproduce
1. Go to message operation screen
2. click S/H/F/R under options on the top left

### Expected result
Every line should have the option you selected selected

### Actual result
Only the top line gets selected

### Version and method
 - MailWatch Version: 1.2.2
 - Install type: tarball
 - Updated from an older MailWatch or fresh install: Upgrade from 1.2.1

### Server configuration
 - Operation System: Ubuntu
 - PHP version: 7.1
 - Database: MySQL
 - Mail Server: Postfix
 - Used web server: Apache

### Client configuration 
 - Operation System: Windows
 - Browser: Chrome

**Comment by Skywalker-11** [comment]
same as #726 
should be fixed in develop by #729

**Comment by jch2os14** [comment]
thanks, wget
https://raw.githubusercontent.com/Skywalker-11/1.2.0/f68c4d6fc51e7f9398ce468400adac7aa1459ab1/mailscanner/functions.php
in my /var/www/html/mailscanner folder fixed it right up!

**Comment by Skywalker-11** [comment]
ok, then close this issue
