### ISSUE TITLE
Message ID 'XXXXXXX.XXXXX' not found!

### ISSUE THREAD

**Issue by Gusta-BH** [mailwatch/MailWatch#739]
Dear,

I'm noticing that although all messages are logged in MailWatch, some are not having their IDs correlated correctly, displaying the following error: "Message ID 'XXXXXXX.XXXXX' not found!" The error happens when I try to access the message information through MailWatch. Highlighted that I am getting all messages normally.

At first I thought it was a bug with MailScanner, but since I'm getting all the messages normally (including those that MailWatch reports with the error "Message ID 'XXXXXXX.XXXXX' not found!"), I was able to check for message headers that all Are being verified by MailScanner. Therefore, the messages have been verified by MailScanner, but for some reason, they are not having their IDs correlated by MailWatch.

OS: Debian 8.7.1

Mail server: Postfix

Software Versions:

MailWatch Version: 1.2.2
MailScanner Version: 5.0.4
ClamAV Version: 0.99.2
SpamAssassin Version: 3.4.0
PHP Version: 5.6.30
MySQL Version: 5.7.17
NGINX: 1.10.3

**Comment by shawniverson** [comment]
Hello,

Can you tell me what the length of your message ID is before the period and
after?  Is it 7 and 5?

**Comment by Gusta-BH** [comment]
Yes.

Looking, it looks like there is a problem with messages with IDs of length 7 and 5.

AD2D7D25.AD6E3 - found
0892E5B.A1D7E - not found
94B795B.A23BE - not found
A2E2E5B.AEE86 - not found
1F0F25B.AA958 - not found
E26FD5B.A50F7 - not found
D08F667.A088F - not found
D00BD67.A07DD - not found
29001301.A4554 - found
34DA467.A0793 - not found
3AC81301.A02B6 - found
5F3E4301.A5B3B - found
6B92267.A206B - not found

**Comment by shawniverson** [comment]
Preparing a PR to resolve this.

**Comment by Gusta-BH** [comment]
I'll apply this fix in functions.php.
