### ISSUE TITLE
Fonts not rendering in all fields

### ISSUE THREAD

**Issue by shawniverson** [mailwatch/MailWatch#742]
### Issue summary
https://forum.efa-project.org/viewtopic.php?p=8848

### Steps to reproduce
1.  Load latest develop of MailWatch (commit a2c71e302997337ab50aec7adff1e0b4c93ed09c)
2.  Receive mail in various languages
3. 

### Expected result
Fonts should render in all fields

### Actual result
Subject field, for example, is not rendering, although the message header is.

### Version and method
 - MailWatch Version: [ develop ]
 - Install type: [ GitHub checkout ]
 - Updated from an older MailWatch or fresh install: [ Upgrade ] from version [ 1.2.0-RC4 ]

### Server configuration
 - Operation System: [ CentOS ] version [ 6.9 ]
 - PHP version: [ 5.3 ]
 - Database: [ MariaDB ] version [ 10.1 ]
 - Mail Server: [ Postfix ]
 - Used web server: [ Apache ] version [ 2.4 ]

**Comment by pdwalker** [comment]
I'm having the same problem.  Without investigating yet, it looks like a reversion of a previous change to enable multilanguage display.

**Comment by Skywalker-11** [comment]
Can you give us the header of such a mail? Especially the subject part if the header.

**Comment by pdwalker** [comment]
`X-Greylist: whitelisted by SQLgrey-1.8.0
Received: from mail6.bemta12.messagelabs.com (mail6.bemta12.messagelabs.com [216.82.250.247])
        (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
        (No client certificate requested)
        by ourmailserver.example.com (Postfix) with ESMTPS id 040CB18005D
        for <user@example.com>; Tue, 25 Apr 2017 16:03:47 +0800 (HKT)
Received: from [216.82.249.131] by server-11.bemta-12.messagelabs.com id 31/75-01721-2E20FF85; Tue, 25 Apr 2017 08:03:46 +0000
X-Brightmail-Tracker: H4sIAAAAAAAAA+NgFjrCIsWRWlGSWpSXmKPExsVStq/IU/cB0/8
  Ig18LdS22TXvB4sDosWnBB6YAxijWzLyk/IoE1oy5O7+xFzy4w1HxalobYwPjvE0cXYycHBIC
  UhIvjn9m6WLk4BASqJLY99cfJCwiICMxd/ZjVhCbTUBa4vyMnYwgtrDAaiaJ853VIDavgKnEv
  HkzwGpYBFQlnnU9YQQZIwFk//3KDDG9RmL/6S8sEOWCEidnPgHbxCwQI7Fnd8oERu5ZSDKzED
  IgYWYBLYklTf/ZIWxtiWULXzNDlGhKHLushCy8gJFtFaNGcWpRWWqRrpGZXlJRZnpGSW5iZo6
  uoaGRXm5qcXFiempOYlKxXnJ+7iZGYJjVMzAw7mBc1eh1iFGSg0lJlLd+8r8IIb6k/JTKjMTi
  jPii0pzU4kOMMhwcShK8CYz/I4QEi1LTUyvSMnOAAQ+TluDgURLhPQ+S5i0uSMwtzkyHSJ1i9
  Oa4t+b3eyaOBetA5J6NIHLVJhB5Cky+AJFCLHn5ealS4ryVICMEQEZklObBLYBF7iVGWSlhXk
  YGBgYhnoLUotzMElT5V4ziHIxKwrw3QKbwZOaVwN3xCuhEJqATp9r/ATmxJBEhJdXAqPVlm2P
  QXdu6SdMfmgdNkN16R1X0LeM9T4ljzHvuv4oLlhKZYXrqr/LnW1PXLtubLlW9dOvuoJ6P13N6
  5diq0iZ3C9oEJpd6t+vLra1bts2RJzbzxHaTwC9lUQdXcHudOaMRnPBDO1LGJuWka7S+5azVf
  453K70Pc4zNTw8WDn00LyD2hO4aJZbijERDLeai4kQAqBr1D9cCAAA=
X-Env-Sender: maxine.qiu@uosfsa.com
X-Msg-Ref: server-4.tower-28.messagelabs.com!1493107416!38012864!1
X-Originating-IP: [118.190.114.73]
X-Spam-Flag: YES
X-SpamInfo: spam detected heuristically
X-SpamReason: Yes, hits=50.0 required=7.0 tests=surbl:
  U291cmNlOiAgSEVMTyAoRCkg[dW9zZnNhLmNvbQ==],U291cmNlOiAgSEVMTyAoRCkgURL
  signature: dW9zZnNhLmNvbQ==
X-StarScan-Received:
X-StarScan-Version: 9.4.12; banners=-,-,-
X-VirusChecked: Checked
Received: (qmail 23909 invoked from network); 25 Apr 2017 08:03:39 -0000
Received: from unknown (HELO mail.uosfsa.com) (118.190.114.73)
  by server-4.tower-28.messagelabs.com with DHE-RSA-AES256-SHA encrypted SMTP; 25 Apr 2017 08:03:39 -0000
X-Footer: dW9zZnNhLmNvbQ==
Received: from [36.62.29.242] ([36.62.29.242])
        by mail.uosfsa.com (Kerio Connect 8.0.2);
        Tue, 25 Apr 2017 12:41:33 +0800
To: undisclosed-recipients:;
From: maxine.qiu@uosfsa.com
Subject: =?utf-8?Q?Fw=3A_=E5=8A=B3=E5=8A=A8=E5=90=88=E5=90=8C=E5=85=A8?=
        =?utf-8?Q?=E7=A8=8B=E7=B2=BE=E7=BB=86=E5=8C=96=E7=AE=A1=E7=90=86?=
        =?utf-8?Q?=E4=B8=8E=E7=A6=BB=E8=81=8C=E9=A3=8E=E9=99=A9=E6=8E=A7?=
        =?utf-8?Q?=E5=88=B6=E6=93=8D=E4=BD=9C=E5=AE=9E=E5=8A=A1=E6=8A=80?=
        =?utf-8?Q?=E5=B7=A7?=
Message-ID: <20170425044133.6bc58579@mail.uosfsa.com>
Date: Tue, 25 Apr 2017 04:41:33 +0000
X-Mailer: Kerio Connect 8.0.2 WebMail
X-User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
        Chrome/50.0.2661.102 Safari/537.36
MIME-Version: 1.0
Content-Type: multipart/alternative;
        boundary="-----------f6a6b6b0655e3a26b21e5529642dcbc8"

This is a multi-part message in MIME format.
`

**Comment by pdwalker** [comment]
It was previously rendering correctly in 1.2.0 RC4.  I am currently running 1.2.3-dev.

**Comment by stefaweb** [comment]
Could you check if Subject is well encoded in the database?

**Comment by Skywalker-11** [comment]
I just tested with current develop and postfix and it is working fine:
![image](https://cloud.githubusercontent.com/assets/11180862/25395914/00a43f76-29e3-11e7-845a-2a3b77467a7b.png)

![image](https://cloud.githubusercontent.com/assets/11180862/25395884/e1ccf53e-29e2-11e7-8d17-30869dcf2f42.png)

**Comment by Skywalker-11** [comment]
Here's the script that I used to generate the mail you see above
```
#!/bin/sh
( echo "HELO domain.de"
sleep 2
echo "MAIL FROM:bla@test.example.com"
sleep 2
echo "RCPT TO:test@example.com"
sleep 2
echo DATA
sleep 2
echo "Subject: =?utf-8?Q?Fw=3A_=E5=8A=B3=E5=8A=A8=E5=90=88=E5=90=8C=E5=85=A8?=
        =?utf-8?Q?=E7=A8=8B=E7=B2=BE=E7=BB=86=E5=8C=96=E7=AE=A1=E7=90=86?=
        =?utf-8?Q?=E4=B8=8E=E7=A6=BB=E8=81=8C=E9=A3=8E=E9=99=A9=E6=8E=A7?=
        =?utf-8?Q?=E5=88=B6=E6=93=8D=E4=BD=9C=E5=AE=9E=E5=8A=A1=E6=8A=80?=
        =?utf-8?Q?=E5=B7=A7?="
sleep 2
echo "Inhalt der Test-Mail!"
sleep 2
echo "."
sleep 2
echo QUIT
```

**Comment by Skywalker-11** [comment]
In addition to the comment of @stefaweb please check if the encoding of the database is utf8mb4 or still only utf8. Run the following in mysql:
```
show create database mailscanner;
use mailscanner;
show create table maillog;
``` 
They should show `[...] DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci` and `[...] DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci` 
If that is not the case please run the upgrade.php to use utf8mb4 encoding.

**Comment by pdwalker** [comment]
ok, here are the results of "show create database mailscanner" and "show create table maillog" 

    Welcome to the MariaDB monitor.  Commands end with ; or \g.
    Your MariaDB connection id is 13689
    Server version: 10.1.22-MariaDB MariaDB Server
    
    Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.
    
    Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
    
    MariaDB [(none)]> use mailscanner;
    Reading table information for completion of table and column names
    You can turn off this feature to get a quicker startup with -A
    
    Database changed
    MariaDB [mailscanner]> show create database mailscanner;
    +-------------+----------------------------------------------------------------------------------------------------+
    | Database    | Create Database                                                                                    |
    +-------------+----------------------------------------------------------------------------------------------------+
    | mailscanner | CREATE DATABASE `mailscanner` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */ |
    +-------------+----------------------------------------------------------------------------------------------------+
    
    MariaDB [mailscanner]> show create table maillog;
      [snip]
    ) ENGINE=InnoDB AUTO_INCREMENT=41641 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci |
      [snip]

And here is the subject - it's encoded properly.
    
    MariaDB [mailscanner]> select from_address,subject from maillog where from_address = 'maxine.qiu@uosfsa.com';
    +-----------------------+------------------------------------------------------------------------------+
    | from_address          | subject                                                                      |
    +-----------------------+------------------------------------------------------------------------------+
    | maxine.qiu@uosfsa.com | Fw: 劳动合同全程精细化管理与离职风险控制操作实务技巧                         |
    
So, it looks like there is a problem in my copy of mailwatch somewhere.  I'll see if I can find where the problem really is.

Thanks for the help in tracking this down.

**Comment by Skywalker-11** [comment]
Can you try to send a mail with the script above to see if it is only related to the subject or also other parts of a mail?
You should replace example.org with something meaningful for your environment.

Thanks in advance.

**Comment by pdwalker** [comment]
Yes, I've used your script to create the same test message.  It's all good on the database side.

I think the problem might be with the database connection not actually using UTF8*, but instead latin1, thus stripping out the utf8 data.

Confirming...

**Comment by pdwalker** [comment]
My apologies Gentlemen.

The problem was because the connection to mysql was using a latin1 encoding instead of the utf8mb4 encoding.

The fix appears to be to add the following to the [mysqld] section of my.cnf and restart the database server

    collation-server = utf8mb4_unicode_ci
    init-connect='SET NAMES utf8mb4'
    character-set-server = utf8mb4

Your questions and suggestions helped me figure it out.  Thanks.

This issue is now closed.

**Comment by shawniverson** [comment]
Closing since this is a config issue with MariaDB and not a MailWatch issue.

**Comment by stefaweb** [comment]
@shawniverson 

Something wrong somewhere.
Normally, you do not have to do a SET NAMES in my.cnf. MailWhatch do this automaticily.

**Comment by pdwalker** [comment]
Easy enough to test.  I could comment out the second line and see how it behaves.

**Comment by stefaweb** [comment]
If you used git to upload the code. Delete the repository and get a fresh copy of mailwatch and try again. Or do a diff to check.

**Comment by shawniverson** [comment]
I can confirm this issue on the latest develop, just tried it.  However, @pdwalker's settings to MariaDB do make the problem disappear, even though it does not explain why they would be needed.

**Comment by Skywalker-11** [comment]
Can you validate that `self::$link->server_version >= 50503` elevates to true in database.php

**Comment by pdwalker** [comment]
(writing down my thoughts and observations as I have them)

confirmed.

it evaluates to true and the value of server_version is 50505 and $charset is set to utf8mb4

however self::$link->error contains the following value: Can't initialize character set utf8mb4 (path: /usr/share/mysql/charsets/)

    [root@efa charsets]# ls /usr/share/mysql/charsets
    armscii8.xml  cp1257.xml  geostd8.xml  keybcs2.xml  latin5.xml    swe7.xml
    ascii.xml     cp850.xml   greek.xml    koi8r.xml    latin7.xml
    cp1250.xml    cp852.xml   hebrew.xml   koi8u.xml    macce.xml
    cp1251.xml    cp866.xml   hp8.xml      latin1.xml   macroman.xml
    cp1256.xml    dec8.xml    Index.xml    latin2.xml   README

So no character set definition there, so I guess it is compiled into the executable?
https://dev.mysql.com/doc/refman/5.7/en/cannot-initialize-character-set.html

    MariaDB [(none)]> show charset;
    +----------+-----------------------------+---------------------+--------+
    | Charset  | Description                 | Default collation   | Maxlen |
    +----------+-----------------------------+---------------------+--------+
    [snip]
    | utf8mb4  | UTF-8 Unicode               | utf8mb4_general_ci  |      4 |
    [snip]
    +----------+-----------------------------+---------------------+--------+
    40 rows in set (0.00 sec)

So, it looks like the utf8mb4 is not supported unless it is explicitly asked for.  I wonder if that's because of an issue with the us using an older version of mysqli?

    [root@efa mailscanner]# yum list |grep mysqli
    php-pear-MDB2-Driver-mysqli.noarch         1.5.0-0.8.b4.el6             epel

**Comment by Skywalker-11** [comment]
Is there any reason that you don't use php-mysqlnd package?

**Comment by shawniverson** [comment]
I cannot find a php-mysqlnd package for CentOS 6.9 in Base or EPEL?

**Comment by endelwar** [comment]
Can this oink be useful? http://rpm.pbone.net/index.php3?stat=3&search=rh-php56-php-mysqlnd&srodzaj=3

**Comment by shawniverson** [comment]
@endelwar I'm not sure that is going to work.  It looks like it is for PHP 5.6, and CentOS 6.9 is using 5.3.

**Comment by shawniverson** [comment]
P.S.  I am fine with setting it in MariaDB, if that is what is needed for
PHP 5.3 implementations :P

On Wed, Apr 26, 2017 at 1:27 PM, Manuel Dalla Lana <notifications@github.com

**Comment by pdwalker** [comment]
Yeah, given the versions of the software older software involved, it's not really an issue with MailWatch and more an issue of the supporting libraries and mysql/mariadb/perconadb configurations.  

I think this issue can be closed.
