### ISSUE TITLE
Allow release of false positive virus from quarantine

### ISSUE THREAD

**Issue by LucianoCavalheiro** [mailwatch/MailWatch#745]
### Issue summary
I've configured Mailscanner to keep infected messages in quarantine to be able to deal more quickly with false positives. However, while I can release spam/nonspam messages, it fails silently when I try to release a message blocked as "Bad Content".

### Steps to reproduce
1. Enable quarantine of virus files in MailScanner
2. Send a file with legitimate attachment whose extension is not allowed by Mailscanner policy
3. Try to release the message in (detail.php)

### Expected result
Message should be delivered to original or alternate destination address.

### Actual result
Operation returns success but no message is actually delivered.

### Version and method
 - MailWatch Version: 1.2.0
 - Install type: EFA
 - Updated from an older MailWatch or fresh install: Fresh install

### Server configuration
 - Operation System: CentOS
 - PHP version: 5.3
 - Database: MySQL
 - Mail Server: Postfix
 - Used web server: Apache

### Client configuration
Any

### Possible Cause
It seems the problem is with quarantine_list_items() vs quarantine_release() in mailscanner/functions.php. The latter requires the quarantined item to have type "message/rfc822" to execute the release operation. However, the former uses "file -bi" to detected the type of the quarantined item for everything except spam/nonspam/mcp messages, which returns "text/x-mail" for message files. Since both things do not match, quanrantine_release() ignores the message file.

One would need to fix either  quarantine_list_items() or quarantine_release(). Which one is preferable?

**Comment by Skywalker-11** [comment]
@LucianoCavalheiro can you provide an example of an affected message?

**Comment by Skywalker-11** [comment]
@LucianoCavalheiro any update on this?

**Comment by detm54** [comment]
Hey guys, is there any kind of meantime solution or workaround for those two functions to get bad content mails released from quarantine?

**Comment by endelwar** [comment]
@detm54 can you provide an example of an affected message?

**Comment by detm54** [comment]
Thanks for your quick response!  What exactly do you need?

By default we are denying all attachments that contain archives or Microsoft office documents. These mails are handled differently from regular spam mails, so contenttype changes to something "not-rfc822" which can't be handled by quarantine_release().

![unbenannt](https://user-images.githubusercontent.com/26415550/32542391-b9c0c842-c472-11e7-89f5-b6e89507e3c2.JPG)
