### ISSUE TITLE
Not field "email from" in some message on page "Recent messages"

### ISSUE THREAD

**Issue by rebirther** [mailwatch/MailWatch#748]
Hello.
Not field "email from" in some message on page "Recent messages".
Most often this is Mailer-Daemon. But it happens with other senders.

Yesterday I updated Mailwatch to the latest version 1.2.2 (not upgrade, but a fresh install). Zip install. 

My server: Debian 7, Mysql 5.6, PHP 5.4, Postfix, Apache. 
Use XML-RPC (1 server DB+Mailwatch, 2 server Full Mail Stack(Postfix+Mailscanner 5) + Mailwatch).

Use client browser: Linux Mint (latest), Chromium (latest).

I also apply screenshot.
![from](https://cloud.githubusercontent.com/assets/23431941/24993087/022ff648-204f-11e7-8ad3-613b641a2e09.png)

**Comment by stefaweb** [comment]
Check if they are bounce messages. If not envelope-from in the header, this is normal to have the From: empty in GUI. If, envelope-from exist in header (go to detail), please post here the complete header of the message and the corresponding log from the mailer.
We plan to use the From: from header to print in GUI if no envelope-from in futur version of Mailwatch.

**Comment by rebirther** [comment]
Yes, in those that the screenshot "envelope-from" no. And they look like a bounce.

But here's another letter, do not exactly bounce:

Received: from ext2.msk-relay.otrs.hostcomm.ru (ext2.msk-relay.otrs.hostcomm.ru [89.104.90.14])
     by mailscanner2.flynet.pro (Postfix) with ESMTPS id DD2DB20FB2
     for <support@flynet.pro>; Thu, 13 Apr 2017 06:39:30 +0700 (+07)
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed; d=nic.ru; s=otrs;
     h=In-Reply-To:From:To:Message-ID:Date:Subject:MIME-Version:Content-Transfer-Encoding:Content-Type; bh=RNeH94wiKAqpxVgzvat3dsB8pWuzfrKfQWwnXsIP2LI=;
     b=yqxNRylSfgAsiySWyhzYCRthOI5EIu82wK6p21WFc5K7TXrY2IB/M5GXpQEvzbZxLqB52RZxDCMVGWESWQwkpQlnMLbiQJT/emrMu4KPlfY31wD++BddGL9eVnZNGtdqfSwHSJppALlwh8WRA7xKU/V0QGPSJIY8Qoi/tY7w7No=;
Received: from otrs1.int.nic.ru ([10.14.7.239])
     by msk-relay.otrs.hostcomm.ru with esmtp (Exim)
     id 1cyRrG-000LtW-3u
     for support@flynet.pro; Wed, 12 Apr 2017 23:39:30 +0000
Received: from otrs by otrs1.int.nic.ru with local (Exim)
     id 1cyRrG-0001sT-2s
     for support@flynet.pro; Wed, 12 Apr 2017 23:39:30 +0000
Content-Type: text/plain; charset="utf-8"
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0
Subject: [Ticket#2017041310004763] [ID: 716118] Домен METALLTEX.RU:
срок регистрации 
заканчивае [...]
Date: Wed, 12 Apr 2017 23:39:30 +0000
Precedence: bulk
X-Loop: yes
Auto-Submitted: auto-generated
Message-ID: <1492051169.510078.721590091.31575657.1@ru>
To: support@flynet.pro
From: RU-CENTER NCC <info@nic.ru>
In-Reply-To: <support_1452209_YPgBKSkm9i10fAGk@bill.flynet.pro>

Log:
Apr 13 06:39:30 mailscanner2 postfix/smtpd[4532]: DD2DB20FB2: client=ext2.msk-relay.otrs.hostcomm.ru[89.104.90.14]
Apr 13 06:39:30 mailscanner2 postfix/cleanup[4637]: DD2DB20FB2: hold: header Received: from ext2.msk-relay.otrs.hostcomm.ru (ext2.msk-relay.otrs.hostcomm.ru [89.104.90.14])??by mailscanner2.flynet.pro (Postfix) with ESMTPS id DD2DB20FB2??for <support@flynet.pro>; Thu, 13 Apr 2 from ext2.msk-relay.otrs.hostcomm.ru[89.104.90.14]; from=<> to=<support@flynet.pro> proto=ESMTP helo=<ext2.msk-relay.otrs.hostcomm.ru>
Apr 13 06:39:30 mailscanner2 postfix/cleanup[4637]: DD2DB20FB2: message-id=<1492051169.510078.721590091.31575657.1@ru>
Apr 13 06:39:50 mailscanner2 MailScanner[4195]: Requeue: DD2DB20FB2.A3D4A to DF71520F6F
Apr 13 06:39:50 mailscanner2 MailScanner[4195]: MailWatch: Logging message DD2DB20FB2.A3D4A to SQL

**Comment by stefaweb** [comment]
If no envelope-from, nothing printed.

MailScanner (and MailWatch) only use envelope-from currently.

**Comment by rebirther** [comment]
So this mail provider does not comply with RFC?

**Comment by stefaweb** [comment]
> So this mail provider does not comply with RFC?

A lot of mail are not RFC compliant... For this reason, it is very complicated to analyze a header to catch the From: with 100% success. I've wrote the function getFROMheader() for that but currently its only used in Exim queue code.

**Comment by rebirther** [comment]
Ok, thanks. Can close.

**Comment by stefaweb** [comment]
> Ok, thanks. Can close.

You should.
