### ISSUE TITLE
Quarantine Report links are being html encoded

### ISSUE THREAD

**Issue by asuweb** [mailwatch/MailWatch#756]
### Issue summary
Some URL parameters in Quarantine reports (both view and release) are being html encoded which breaking functionality.  The `&` is being encoded as `&amp;`

The URLs are correct in the email, but are being modified in the browser / mailwatch.  This is a new bug, it was working fine on v.12.2-dev

Example: `viewmail.php?token=92cba655afd75ae66d38ca9f46802daa42fd9e63&amp;id=C5B2FFF07B.A439F`
### Version and method
 - MailWatch Version: 1.2.3-dev
 - Install type: GitHub checkout]
 - Updated from an older MailWatch or fresh install: [ Upgrade ] (v1.2.2-dev)

**Comment by endelwar** [comment]
I can confirm, there is a `&amp;` in new Quarantine_Report code, I'm going to fix it in the refactoring I'm doing

**Comment by asuweb** [comment]
I've provided a workaround for this in #768

**Comment by stefaweb** [comment]
Seems already done or not the same?

https://github.com/mailwatch/MailWatch/commit/14770dfb8556f6fa5201e0b5883cd4498298bfa0

**Comment by asuweb** [comment]
No, that fix didn't work for me.  It seems some email clients will automatically encode the `&` when clicking the links, so I provided a workaround which works for both `&` and `&amp;` in the URL

**Comment by asuweb** [comment]
Workaround in #768 merged 

Closed

**Comment by stefaweb** [comment]
Problem when I run /usr/local/bin/mailwatch_quarantine_report.php after last PR.

Error: Cannot find functions.php file in "/opt/mailwatch/mailscanner/functions.php": edit /usr/local/bin/mailwatch_quarantine_report.php and set the right path on line 34

**Comment by asuweb** [comment]
There were no changes which affect the paths to files.  Have you got the correct path set?

**Comment by stefaweb** [comment]
In file, I found this after upgraded to last PR.
$pathToFunctions = '/opt/mailwatch/mailscanner/functions.php';

**Comment by stefaweb** [comment]
Same in GitHub.

**Comment by asuweb** [comment]
Yes, it seems to have been induced following that commit, but I don't know how, as it's wasn't like that on mine before.

**Comment by asuweb** [comment]
fixed in #769

It looks like @endelwar's directory structure, but not sure how it made it into the commit.
