### ISSUE TITLE
Send quarantine report now

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#757]
With last develop.

Don't see the button "Send quarantine report now"?

![capture d ecran 2017-04-19 a 16 37 15](https://cloud.githubusercontent.com/assets/12907102/25185810/9d4209f4-251e-11e7-85bf-ef98717d1741.png)

Line 661 in user_manager.php:

`        echo ' <tr><td class="heading">' . __('quarrep12') . '</td><td><input type="checkbox" name="quarantine_report" value="on" ' . $quarantine_report . '> <span style="font-size:90%">' . __('senddaily12') . '</span> <button type="submit" name="action" value="sendReportNow">' . __('sendReportNow12') . '</button></td></tr>' . "\n";`

**Comment by Skywalker-11** [comment]
It's only for normal users when they already have an account. Not for new users 😄

**Comment by stefaweb** [comment]
Same with existing user!   😀

![capture d ecran 2017-04-19 a 17 16 20](https://cloud.githubusercontent.com/assets/12907102/25187701/1f1656ba-2524-11e7-901d-be5f4c16d83f.png)

**Comment by Skywalker-11** [comment]
The user can do it himself. Admins can't do it for him 😁

**Comment by stefaweb** [comment]
Oua!

Finally found it.

![capture d ecran 2017-04-19 a 17 43 40](https://cloud.githubusercontent.com/assets/12907102/25188902/dbe98e80-2527-11e7-997e-ed6521ac5bed.png)

Will be better to have the short version "Send now" for the button (don't need to write quarantine report. We already are on the quarantine report line).

No way to have this for admin and admin-user?
In the real life no all user have an account.

**Comment by Skywalker-11** [comment]
Less work for the admins 😁 . But I'm working on it

**Comment by stefaweb** [comment]
More work for the domain-admin, less for the admin.   😉

I've done a PR for new words for sendReportNow12

**Comment by Skywalker-11** [comment]
#760 enables this for admins

**Comment by stefaweb** [comment]
Done.
