### ISSUE TITLE
Incompatibility with php 7

### ISSUE THREAD

**Issue by Skywalker-11** [mailwatch/MailWatch#763]
With PHP 7 the function `dl` is disabled by default (see [http://php.net/manual/en/function.dl.php](http://php.net/manual/en/function.dl.php))

In lib/xmlrpc/xmlrpc.inc which is included by functions.php on every page we use this function to load the xml library with the `dl` function. This results in HTML 500 Error:
```
PHP Fatal errror: Uncaught Error: Call to undefined function dl() in PATH_TO_MW/mailscanner/lib/xmlrpc/xmlrpc.inc:43
Stack trace:
0 PATH_TO_MW/mailscanner/functions.php(148): require_once()
1 PATH_TO_MW/mailscanner/status.php(32): require_once('PATH_TO_MW/mailscanner...')
2 {main}
thrown in PATH_TO_MW/mailscanner/lib/xmlrpc/xmlrpc.inc on line 43
```

It requires either to install the package `php-xml` so that the php extension is always loaded and `dl`is not required or to set `enable_dl = On` in php.ini. What shall we recommend? It has to be added to the docs.

**Comment by stefaweb** [comment]
I vote for php-xml package.

**Comment by theplayer777** [comment]
I have the same issue with PHP 5.6, even after installing php-xml and enabling dl in php.ini... any idea?

**Comment by endelwar** [comment]
I'm for a check for `xml_parser_create` function existence before include of xmlrpc lib and a related error (also in upgrade.php) if rpc is enabled and xml functions are missing

**Comment by endelwar** [comment]
@theplayer777 can you run the following code and verify that xml functions are enabled? copy/past in a test.php file and run it with `php test.php` and in your browser.

```php
<?php
	if(!function_exists('xml_parser_create'))
	{
		echo 'xml not enabled';
	} else {
		echo 'all ok';
	}
```
