### ISSUE TITLE
feature request: html hover in the mailwatch web ui

### ISSUE THREAD

**Issue by pdwalker** [mailwatch/MailWatch#765]
This is a minor ui feature request

It'd be nice to use the the :hover attribute to provide a visual clue as to what line you are looking at in the mail list.

The change is trivial, editing the style.css and adding in something like the following in style.css:

    table.mail tr:hover td {
            background: white;
            color: blue !important;
    }
    table.mail tr.whitelisted:hover td { background: #CCEECC; }
    table.mail tr.spam:hover td { background: #F5DDDD; }
    table.mail tr.highspam:hover td { background: #FFAAAA; }
    table.mail tr.blacklisted:hover td { background: #888888; }
    table.mail tr.infected:hover td { background: #ff8888; }

(I've not covered all the attributes, like mcp, not scanned, just because I'm being lazy)

It just provides a subtle visual clue as to which line your mouse is pointing at which can make it easier reading the data on a wide screen.  

The colors selected should be a subtle change of the original background color.  The above colors were chosen to match the EFA color scheme and would not be appropriate for the default MailWatch color scheme.

**Comment by asuweb** [comment]
The easiest way to implement this is with css3 (with the caveat that older browsers will fail gracefully and simply not display the hover effects)

```
table.mail tr:hover { filter: invert(0.1); }
```

**Comment by pdwalker** [comment]
@asuweb that's a far more elegant solution than mine.

**Comment by asuweb** [comment]
This can be closed now
