### ISSUE TITLE
Send quarantaine report

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#766]
When we click on "Send now", we got this message:

![capture d ecran 2017-04-28 a 09 30 26](https://cloud.githubusercontent.com/assets/12907102/25518804/86231334-2bf5-11e7-84a5-9774238a5842.png)

Add a new line between the message and New user will be better. OR, we can center the message.

**Comment by Skywalker-11** [comment]
This message is shown in the same way like the other messages on that page. If we change this we should change the others too.

**Comment by stefaweb** [comment]
Could you try centered (for all messages)?
It's prettier to see and the message gets better.

![capture d ecran 2017-04-28 a 09 50 38](https://cloud.githubusercontent.com/assets/12907102/25519538/832aaa18-2bf8-11e7-8d36-8f711221d06f.png)

**Comment by stefaweb** [comment]
Seems ok.

Green message very big. ;-)

**Comment by Skywalker-11** [comment]
Just copied the design that was there ;-)
