### ISSUE TITLE
How to debug custom Mailscanner perl scripts that not works anymore

### ISSUE THREAD

**Issue by picov** [mailwatch/MailWatch#774]
### Issue summary
I've upgraded from 1.2.0 to 1.2.2 and now, after upgrade.php and coping custom perl scripts into proper location I'm unable to log nothing to MySQL DB (MailWatchConf.pm is configured according to conf.php).

When I enable in MailScanner.conf the option 
"Always Looked Up Last = &MailWatchLogging"
(or Is Definitely Not Spam = &SQLWhitelist or Is Definitely Spam = &SQLBlacklist)
I got this repeated error in system log
"MailScanner: Process did not exit cleanly, returned 255 with signal 0"
and all emails stop to be delivered (email queue grows forever).

There is a way to debug why the custom perl scripts are causing  this problem?

MailScanner --lint say:
...
Config: calling custom end function MailWatchLogging
Attempt to free unreferenced scalar: SV 0x1c3a5a0, Perl interpreter: 0x17ab010, line 1 during global destruction.

perl --version
This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi

### Version and method
 - MailWatch Version: 1.2.2 stable 
- MailScanner Version: 5.0.3
 - Install type: Zip/tarball install
 - Updated from an older MailWatch or fresh install:  Upgrade from 1.2.0 to 1.2.2

### Server configuration
 - Operation System: CentOS 6.9
 - PHP version: 5.6.30
 - Database:  MySQL version 5.5.54 
 - Mail Server: Postfix  
 - Used web server: Apache

**Comment by Skywalker-11** [comment]
You can add 
`MailScanner::Log::WarnLog("MailWatch: Debug 1");`
`MailScanner::Log::WarnLog("MailWatch: Debug 2");` etc.  
in the code to see what is the last code line that was processed. The output of the messages happens in mail.log.

If you want to see the content of a variable uncomment `#use Data::Dumper;` at the beginning of the file and use `    #MailScanner::Log::WarnLog("MailWatch: Debug-Dump: %s", Dumper($WHATEVER_VAR));` where `$WHATEVER_VAR` is the variable to dump to the mail.log.

**Comment by picov** [comment]
Hi,
thank you for quick reply.
I've added a logging line at the beginning of every sub.

When I run MailScanner --lint I see this:
...
Config: calling custom init function MailWatchLogging
MailWatch: Debug iInitMailWatchLogging CALLED at /usr/share/MailScanner/perl/custom/MailWatch.pm line 78.
MailWatch: Debug InitConnection CALLED at /usr/share/MailScanner/perl/custom/MailWatch.pm line 117.
MailWatch: Debug CheckSQLVersion CALLED at /usr/share/MailScanner/perl/custom/MailWatch.pm line 101.
MailWatch: Started MailWatch SQL Logging child

Checking version numbers...
Version number in MailScanner.conf (5.0.3) is correct.
...
Checking for SpamAssassin errors (if you use it)...
MailWatch: Debug ListenForMessages CALLED at /usr/share/MailScanner/perl/custom/MailWatch.pm line 165.
Using SpamAssassin results cache
Connected to SpamAssassin cache database
Use of uninitialized value $ns in pattern match (m//) at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/DnsResolver.pm line 201.
SpamAssassin reported no errors.
Connected to Processing Attempts Database
Created Processing Attempts Database successfully
...
Found these virus scanners installed: clamav
Virus Scanner test reports:
ClamAV said "eicar.com contains Eicar-Test-Signature"
...
Config: calling custom end function MailWatchLogging
MailWatch: Debug EndMailWatchLogging CALLED at /usr/share/MailScanner/perl/custom/MailWatch.pm line 254.
MailWatch: Debug ExitLogging CALLED at /usr/share/MailScanner/perl/custom/MailWatch.pm line 156.
Attempt to free unreferenced scalar: SV 0x13b5028, Perl interpreter: 0x1297010, <CLIENT> line 1 during global destruction.
Attempt to free unreferenced scalar: SV 0x32d5ee0, Perl interpreter: 0x1297010, <CLIENT> line 1 during global destruction.
Attempt to free unreferenced scalar: SV 0x13b4c80, Perl interpreter: 0x1297010, <CLIENT> line 1 during global destruction.
Attempt to free unreferenced scalar: SV 0x32d6090, Perl interpreter: 0x1297010, <CLIENT> line 1 during global destruction.
Attempt to free unreferenced scalar: SV 0x13b4f98, Perl interpreter: 0x1297010, <CLIENT> line 1 during global destruction.
Attempt to free unreferenced scalar: SV 0x32d60c0, Perl interpreter: 0x1297010, <CLIENT> line 1 during global destruction.

So it seems that the sub MailWatchLogging is never called because at the first line of that sub I've added:
MailScanner::Log::WarnLog("MailWatch: Debug MailWatchLogging CALLED");

If MailScanner is run normally the only message in maillog is:
"Config: calling custom init function MailWatchLogging"
(so no DEBUG messages appears?!)

**Comment by Skywalker-11** [comment]
In which path have you put MailWatch.pm etc.? 
Can you do the following: service mailscanner restart && tail mail.log` and post the output here?

**Comment by picov** [comment]
MailWatch.pm (and other perl script sim links) are inside:
/usr/share/MailScanner/perl/custom/

The log is:
May  4 18:25:02 mailserver MailScanner[27656]: MailScanner Email Processor version 5.0.3 starting...
May  4 18:25:02 mailserver MailScanner[27656]: Reading configuration file /etc/MailScanner/MailScanner.conf
May  4 18:25:02 mailserver MailScanner[27656]: Reading configuration file /etc/MailScanner/conf.d/README
May  4 18:25:02 mailserver MailScanner[27656]: Read 1501 hostnames from the phishing whitelist
May  4 18:25:02 mailserver MailScanner[27656]: Read 15473 hostnames from the phishing blacklists
May  4 18:25:02 mailserver MailScanner[27656]: Config: calling custom init function MailWatchLogging
May  4 18:25:02 mailserver MailScanner[27656]: Using SpamAssassin results cache
May  4 18:25:02 mailserver MailScanner[27656]: Connected to SpamAssassin cache database
May  4 18:25:02 mailserver MailScanner[27656]: Enabling SpamAssassin auto-whitelist functionality...
May  4 18:25:04 mailserver MailScanner[27610]: Requeue: 2FB4240244.ABA29 to 124A840264
May  4 18:25:04 mailserver MailScanner[27610]: Uninfected: Delivered 1 messages
May  4 18:25:05 mailserver MailScanner[27610]: Deleted 1 messages from processing-database
May  4 18:25:06 mailserver MailScanner[27656]: Connected to Processing Attempts Database
May  4 18:25:06 mailserver MailScanner[27656]: Found 2 messages in the Processing Attempts Database
May  4 18:25:06 mailserver MailScanner[27656]: Using locktype = flock
May  4 18:25:07 mailserver MailScanner[27663]: MailScanner Email Processor version 5.0.3 starting...
May  4 18:25:07 mailserver MailScanner[27663]: Reading configuration file /etc/MailScanner/MailScanner.conf
May  4 18:25:07 mailserver MailScanner[27663]: Reading configuration file /etc/MailScanner/conf.d/README
May  4 18:25:07 mailserver MailScanner[27663]: Read 1501 hostnames from the phishing whitelist
May  4 18:25:07 mailserver MailScanner[27663]: Read 15473 hostnames from the phishing blacklists
May  4 18:25:07 mailserver MailScanner[27663]: Config: calling custom init function MailWatchLogging
May  4 18:25:07 mailserver MailScanner[27663]: Using SpamAssassin results cache
May  4 18:25:07 mailserver MailScanner[27663]: Connected to SpamAssassin cache database
May  4 18:25:08 mailserver MailScanner[27663]: Expired 1 records from the SpamAssassin cache
May  4 18:25:08 mailserver MailScanner[27663]: Enabling SpamAssassin auto-whitelist functionality...
May  4 18:25:11 mailserver MailScanner[27663]: Connected to Processing Attempts Database
May  4 18:25:11 mailserver MailScanner[27663]: Found 2 messages in the Processing Attempts Database
May  4 18:25:11 mailserver MailScanner[27663]: Using locktype = flock
May  4 18:25:12 mailserver MailScanner[27668]: MailScanner Email Processor version 5.0.3 starting...
May  4 18:25:12 mailserver MailScanner[27668]: Reading configuration file /etc/MailScanner/MailScanner.conf
May  4 18:25:12 mailserver MailScanner[27668]: Reading configuration file /etc/MailScanner/conf.d/README
May  4 18:25:12 mailserver MailScanner[27668]: Read 1501 hostnames from the phishing whitelist
May  4 18:25:12 mailserver MailScanner[27668]: Read 15473 hostnames from the phishing blacklists
May  4 18:25:12 mailserver MailScanner[27668]: Config: calling custom init function MailWatchLogging
May  4 18:25:12 mailserver MailScanner[27668]: Using SpamAssassin results cache
May  4 18:25:12 mailserver MailScanner[27668]: Connected to SpamAssassin cache database
May  4 18:25:12 mailserver MailScanner[27668]: Enabling SpamAssassin auto-whitelist functionality...


There is any reason of why I don't see the debug messages that I see using MailScanner --lint ?

**Comment by Skywalker-11** [comment]
It is normal that the part in MailWatchLogging does not occure because it is not tested when using MailScanner --lint. But it should be printed to mail.log if run by the service.

Also it looks like MailWatch does not correctly fork the process for MailWatch-Logging. It should look like this:
``` 
May  4 18:04:15 mail MailScanner[78063]: Read 15230 hostnames from the phishing blacklists
May  4 18:04:15 mail MailScanner[78063]: Config: calling custom init function MailWatchLogging
May  4 18:04:15 mail MailScanner[78063]: MailWatch: Started MailWatch SQL Logging child
May  4 18:04:15 mail MailScanner[78063]: Using SpamAssassin results cache
``` 

If you place a debug message at the beginning of InitMailWatchLogging in MailWatch.pm (before the line with `= fork();`) and restart the service is that message printed to the mail.log?

**Comment by picov** [comment]
I've already added the log line in that point but the message do not appears in maillog (only in MailScanner --lint as you can see).

sub InitMailWatchLogging {
# DEBUG
MailScanner::Log::WarnLog("MailWatch: Debug InitMailWatchLogging CALLED");
    my $pid = fork();
....

**Comment by picov** [comment]
I've enabled debug mode is MailScanner and the log end with:

22:21:44 Undefined subroutine &MailScanner::CustomConfig::MailWatchLogging called at /usr/share/MailScanner/perl/MailScanner/Config.pm line 170.
MailScanner failed to start ... doh!

**Comment by Skywalker-11** [comment]
One last try: What's the output of `perl -wc /etc/MailScanner/custom/MailWatch.pm`? 
Output should be like
`Useless use of private variable in void context at /etc/MailScanner/custom/MailWatch.pm line 316.
/etc/MailScanner/custom/MailWatch.pm syntax OK
`

**Comment by picov** [comment]
> perl -wc /etc/MailScanner/custom/MailWatch.pm
Useless use of private variable in void context at /etc/MailScanner/custom/MailWatch.pm line 335.
/etc/MailScanner/custom/MailWatch.pm syntax OK

**Comment by picov** [comment]
Hi,
the problem seems related to my MailScanner installation because I've tried to use another custom script provided with MailScanner (SpamWhitelist.pm) and the error is the same (for some reasons the script function that is called result undefined):  

00:04:04 Have a batch of 7 messages.
00:04:04 Insecure dependency in open while running with -T switch at /usr/local/lib64/perl5/IO/File.pm line 185, <$fh> line 66.
00:04:04 Insecure dependency in open while running with -T switch at /usr/local/lib64/perl5/IO/File.pm line 185, <$fh> line 167.
00:04:04 Insecure dependency in open while running with -T switch at /usr/local/lib64/perl5/IO/File.pm line 185.
00:04:05 Insecure dependency in open while running with -T switch at /usr/local/lib64/perl5/IO/File.pm line 185.
00:04:05 Insecure dependency in open while running with -T switch at /usr/local/lib64/perl5/IO/File.pm line 185.
00:04:05 Insecure dependency in open while running with -T switch at /usr/local/lib64/perl5/IO/File.pm line 185, <$fh> line 4.
00:04:05 Insecure dependency in open while running with -T switch at /usr/local/lib64/perl5/IO/File.pm line 185.
00:04:05 Insecure dependency in open while running with -T switch at /usr/local/lib64/perl5/IO/File.pm line 185, <$fh> line 1.
00:04:05 Insecure dependency in open while running with -T switch at /usr/local/lib64/perl5/IO/File.pm line 185.
00:04:05 Insecure dependency in open while running with -T switch at /usr/local/lib64/perl5/IO/File.pm line 185, <$fh> line 30.
00:04:06 Insecure dependency in open while running with -T switch at /usr/local/lib64/perl5/IO/File.pm line 185.
00:04:06 Insecure dependency in open while running with -T switch at /usr/local/lib64/perl5/IO/File.pm line 185.
00:04:06 Insecure dependency in open while running with -T switch at /usr/local/lib64/perl5/IO/File.pm line 185.
00:04:06 Insecure dependency in open while running with -T switch at /usr/local/lib64/perl5/IO/File.pm line 185.
00:04:06 Insecure dependency in open while running with -T switch at /usr/local/lib64/perl5/IO/File.pm line 185.
00:04:06 Insecure dependency in open while running with -T switch at /usr/local/lib64/perl5/IO/File.pm line 185, <$fh> line 19.
00:04:07 Undefined subroutine &MailScanner::CustomConfig::SpamWhitelist called at /usr/share/MailScanner/perl/MailScanner/Config.pm line 170.

**Comment by Skywalker-11** [comment]
Can you test if it is a permission problem eg. the user MailScanner is running with does not have read permissions for the perl files? If that is not the problemmay @asuweb has an idea.

**Comment by picov** [comment]
MailScanner run as postfix user and I've set 777 permission to .pm files
