### ISSUE TITLE
MSRE duplicating entire ruleset text

### ISSUE THREAD

**Issue by darren4294** [mailwatch/MailWatch#776]
### Issue summary
After upgrade from RC1 to version 1.22 using the MSRE would double all of the entries in whatever ruleset was being edited after save changes is clicked.
EG. 
From: user@example.com yes
then adding: From: another@example.com yes would give you
From: user@example.com yes
From: user@example.com yes
From: another@example.com yes

### Steps to reproduce
1. Under add new rule Choose condition from drop 
2. add email address, domain, whatever
3. click save changes.  appends all records plus the one just added to the end of the ruleset.

### Expected result
Should only add text in "Add new rule" fields.

### Actual result
appears to be taking all of the fields under "edit ruleset" plus the "add new rule" fields and append to the ruleset instead of replacing.

### Version and method
 - MailWatch Version: [ stable 1.2.2 ]
 - Install type: [ Zip/tarball install ]
 - Updated from an older MailWatch or fresh install: [ Upgrade ] (from 1.20 RC1 [ 1.22 ])

### Server configuration
 - Operation System: [ CentOS ] version [ 6.9 ]
 - PHP version: [ 5.6 ]
 - Database: [ MYsql ] version [ 5.6.36 ]
 - Mail Server: [ Sendmail ]
 - Used web server: [ Apache ] version [ 2.2.15 ]

### Client configuration 
 - Operation System: [ Windows 10 ] version [ 1607 ]
 - Browser: [ Chrome 57.0.2987.133 ]

**Comment by shawniverson** [comment]
Known issue.  Fix is in develop branch.

**Comment by darren4294** [comment]
Awesome! Great job with this!
