### ISSUE TITLE
Emoji charachters in subject crash database logging

### ISSUE THREAD

**Issue by armorharmer** [mailwatch/MailWatch#779]
### Issue summary
It seems that the problem is when someone puts emoji characters into subject. Mailwatch will stop writing to database. 

Logs will only say something like this:
May  6 14:13:58 mailsecurity MailScanner[64217]: Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xF0\x9F\x92\x9F O...' for column 'subject' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 189, <CLIENT> line 76.

I fixed it by changing:
from: my $subject = fix_latin($message->{utf8subject});
to: my $subject = $message->{subject};

in /usr/share/MailScanner/perl/custom/MailWatch.pm file.

But now I can see only question marks instead of utf8 characters, altough the mails are being logged into db.

### Steps to reproduce
1. Send mail with emojis in subject (something like this: 😀 😃 😄 😁 😆 😅 😂 )

### Expected result
Mail should be written into DB

### Actual result
Mailwatch stops writing to the database

### Version and method
 - MailWatch Version: [ stable 1.2.2 ]
 - Install type: [ Zip/tarball install ]
 - Updated from an older MailWatch or fresh install: [ Fresh instal ]

### Server configuration
 - Operation System: [ CentOS 6.9 ]
 - PHP version: [ 5.6 ]
 - Database: [ MySQL 5.74 ]
 - Mail Server: [ Postfix ]
 - Used web server: [ Apache 2.2 ]

### Client configuration 
 - Operation System: [ Arch Linux ]
 - Browser: [ Firefox ]

**Comment by armorharmer** [comment]
As I said:
"But now I can see only question marks instead of utf8 characters, altough the mails are being logged into db."
You are correct, but that is the only way that I found that doesn't prevent writing to DB.

**Comment by stefaweb** [comment]
Could you post the complete Subject before encoding?
The one, you got in MTA log.

**Comment by armorharmer** [comment]
May  8 10:14:37 mailscanner MailScanner[13892]: MailWatch: Logging message 89DE140912.A7DB2 to SQL
Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xF0\x9F\x98\x80 \xF0...' for column 'subject' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 189, <CLIENT> line 144.
) at /usr/share/MailScanner/perl/MailScanner/Config.pm line 1053

I cannot see the subject in MTA, I can only see error above.

This mail was sent with the subject "😀 😃 😄 😁 😆 😅 😂"

**Comment by stefaweb** [comment]
😀 😃 😄 😁 😆 😅 😂 works fine on my test server with last develop version.

I got this in MTA log: `T="\360\237\230\200 \360\237\230\203 \360\237\230\204 \360\237\230\201 \360\237\230\206 \360\237\230\205 \360\237\230\202"`

90% of chance that the problem comes from your server version/config or from MTA client encoding at start.

**Comment by armorharmer** [comment]
Here's info from my Mailwatch:

MailWatch Version: 1.2.2
MailScanner Version: 5.0.3
ClamAV Version: 0.99.2
SpamAssassin Version: 3.3.1
PHP Version: 5.6.30
MySQL Version: 5.7.18

MTA client? Is that MUA? I've tried different sources, webmail and also Thunderbird. But if that is the problem, than it's not good that MUA encoding could crash mailwatch.

**Comment by armorharmer** [comment]
https://github.com/mailwatch/MailWatch/issues/238 , same issue?

**Comment by stefaweb** [comment]
And what is your MTA?
MUA problem is just a possibility.

**Comment by armorharmer** [comment]
My MTA is postfix.  If you missed my post above yours, https://github.com/mailwatch/MailWatch/issues/238 could be the same issue?

**Comment by stefaweb** [comment]
To know that, we need to have your postfix log (and the complete queue file).

**Comment by armorharmer** [comment]
Here's queue file:

CO           2720             709               1               0            2720T^Q1494233038 183877A^Vcreate_time=1494233038A^Vrewrite_context=remoteS^[test@gmail.comA(log_client_name=mail-qk0-f169.google.comA!log_client_address=209.85.220.169A^Ulog_client_port=33959A;log_message_origin=mail-qk0-f169.google.com[209.85.220.169]A&log_helo_name=mail-qk0-f169.google.comA^Wlog_protocol_name=ESMTPA$client_name=mail-qk0-f169.google.comA,reverse_client_name=mail-qk0-f169.google.comA^]client_address=209.85.220.169A^Qclient_port=33959A"helo_name=mail-qk0-f169.google.comA^Sprotocol_name=ESMTPA^Uclient_address_type=2A*dsn_orig_rcpt=rfc822;andros@test.infoO^Uandros@test.infoR^Uandros@test.infoM^@NSReceived: from mail-qk0-f169.google.com (mail-qk0-f169.google.com [209.85.220.169])N?      by mailscanner.test.com (Postfix) with ESMTP id 2E2C240953ND    for <andros@test.info>; Mon,  8 May 2017 10:43:58 +0200 (CEST)NEReceived: by mail-qk0-f169.google.com with SMTP id k74so46136565qke.1NJ        for <andros@test.info>; Mon, 08 May 2017 01:43:58 -0700 (PDT)N5DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;N         d=gmail.com; s=20161025;N7        h=mime-version:from:date:message-id:subject:to;N8        bh=XJHhKXXxzvRsIGVD1ai9U4NSYtnLeIi9YNhqW099UP0=;NL        b=RtkbVyolUEubNOsEj72V7Bizu1962RIbbme+4YF4Cfl2GH/qVTARpZv9dFqYdzAEENNM         P6OJDJrU3dHMTKGMBKpH3WmqFH0U1wyrI882cePTlkDLH+lycqs980iO4N0kzYd+p3ReNM         zZL2gjwA4FCpRrYvLRsOiXmQKJ/pCYfNp+BN1ZgUB35Wv/Idtc1pAgY4aB+LdhB2cMXlNM         FkMMUGhlCkkGwzAsmPTUXszFURdzisPlj1+TSzUKbo5K5wVKykXPYJgRp65Jg3TytbqjNM         DN5Cu2u3VsnHPEoHCzJXsr+SRijBu7VAsAnuS5ndfth+DLG5uH8r5LgAPqqE596orQb+N^O         P2zQ==N>X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;N         d=1e100.net; s=20161025;NJ        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;N8        bh=XJHhKXXxzvRsIGVD1ai9U4NSYtnLeIi9YNhqW099UP0=;NL        b=IQNiK5f6sQlJG6tUqCTl6Xk3DreVpYRWAShzO+rh5eeGRN4+UNIDZVCeNSe+lErd6WNM         A/L2peJ79R5tSZZUHOinwqY7vPCYYUTkKQ5x8yOdsC0/L8fydVCjqF/7IIUPdmZz6joCNM         Dw+tPg6YxhQWyVbmtqdzxzcs/HlBfXU1OggpDWX2RzA8OSDjxA0pejgs9DRGGNMZ7CcCNM         xPZoWgLS8IcyUPXmJo4j2dbpdxdEDkaihrjCvh6kut02wAhhWY1m1EQ+09FjTEy2AffxNM         pt/5x8YCmgYpzKXV5Xvu7nltQU9WX5JElm+6d0/1gBri4WVEWZRgSbdskFH3bXdfPomON^O         Z4Ww==NLX-Gm-Message-State: AODbwcD7EWZg055Kf+GA41OtsmYPRWYS+ogsYz6SovyDZOj54+N0fUGHN!        iDJAVR58jtU5cBQQ5oEKD7q66E2JitEpNNX-Received: by 10.55.137.133 with SMTP id l127mr23224150qkd.113.1494233037080;N& Mon, 08 May 2017 01:43:57 -0700 (PDT)N^QMIME-Version: 1.0NJReceived: by 10.140.93.203 with HTTP; Mon, 8 May 2017 01:43:56 -0700 (PDT)N6From: Mango Baobab <mangobaobab@gmail.com>N$Date: Mon, 8 May 2017 10:43:56 +0200NPMessage-ID: <CALBvqar9xWFNaEW3FbithBRwA5GHfB5mYUiD-USxo9-7=6LTHw@mail.gmail.com>NESubject: =?UTF-8?B?8J+YgCDwn5iDIPCfmIQg8J+YgSDwn5iGIPCfmIUg8J+Ygg==?=N^YTo: andros@test.infoNJContent-Type: multipart/alternative; boundary=94eb2c07259e630f52054eff3db1N^@N^^--94eb2c07259e630f52054eff3db1N'Content-Type: text/plain; charset=UTF-8N!Content-Transfer-Encoding: base64N^@N08J+YgCDwn5iDIPCfmIQg8J+YgSDwn5iGIPCfmIUg8J+Ygg0KN^^--94eb2c07259e630f52054eff3db1N&Content-Type: text/html; charset=UTF-8N!Content-Transfer-Encoding: base64N^@NLPGRpdiBkaXI9Imx0ciI+PGRpdj48ZGl2PvCfmIAg8J+YgyDwn5iEIPCfmIEg8J+YhiDwn5iFIPCfN mII8L2Rpdj48L2Rpdj48L2Rpdj4NCg==N --94eb2c07259e630f52054eff3db1--X^@E^@


NOTE: while I was viewing queue file I got this message prompted to ma CLI:

Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xF0\x9F\x98\x80 \xF0...' for column 'subject' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 189, <CLIENT> line 74.
) at /usr/share/MailScanner/perl/MailScanner/Config.pm line 1053

Here's my Postfix log:

May  8 10:43:57 mailscanner postfix/smtpd[16358]: connect from mail-qk0-f169.google.com[209.85.220.169]
May  8 10:43:58 mailscanner postfix/smtpd[16358]: 2E2C240953: client=mail-qk0-f169.google.com[209.85.220.169]
May  8 10:43:58 mailscanner postfix/cleanup[16361]: 2E2C240953: hold: header Received: from mail-qk0-f169.google.com (mail-qk0-f169.google.com [209.85.220.169])??by mailscanner.nc-cloud.com (Postfix) with ESMTP id 2E2C240953??for <andros@test.info>; Mon,  8 May 2017 10:43 from mail-qk0-f169.google.com[209.85.220.169]; from=<mangobaobab@gmail.com> to=<andros@test.info> proto=ESMTP helo=<mail-qk0-f169.google.com>
May  8 10:43:58 mailscanner postfix/cleanup[16361]: 2E2C240953: message-id=<CALBvqar9xWFNaEW3FbithBRwA5GHfB5mYUiD-USxo9-7=6LTHw@mail.gmail.com>
May  8 10:43:58 mailscanner postfix/smtpd[16358]: disconnect from mail-qk0-f169.google.com[209.85.220.169]
May  8 10:43:58 mailscanner MailScanner[16300]: New Batch: Scanning 1 messages, 3433 bytes
May  8 10:43:58 mailscanner MailScanner[16300]: Virus and Content Scanning: Starting
May  8 10:44:19 mailscanner MailScanner[16300]: Requeue: 2E2C240953.A3870 to 0594940987
May  8 10:44:19 mailscanner postfix/qmgr[83169]: 0594940987: from=<mangobaobab@gmail.com>, size=2720, nrcpt=1 (queue active)
May  8 10:44:19 mailscanner MailScanner[16300]: Uninfected: Delivered 1 messages
May  8 10:44:19 mailscanner MailScanner[16300]: Deleted 1 messages from processing-database
May  8 10:44:19 mailscanner MailScanner[16300]: MailWatch: Logging message 2E2C240953.A3870 to SQL
May  8 10:44:19 mailscanner postfix/smtp[16397]: 0594940987: to=<andros@test.info>, relay=XX.XXX.XXX.XXX[XX.XXX.XXX.XXX]:25, delay=21, delays=21/0.01/0.1/0.29, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 6F3431DF351)
May  8 10:44:19 mailscanner postfix/qmgr[83169]: 0594940987: removed
May  8 10:47:18 mailscanner postfix/anvil[15591]: statistics: max connection rate 1/60s for (smtp:109.245.208.118) at May  8 10:41:24
May  8 10:47:18 mailscanner postfix/anvil[15591]: statistics: max connection count 1 for (smtp:109.245.208.118) at May  8 10:41:24
May  8 10:47:18 mailscanner postfix/anvil[15591]: statistics: max cache size 1 at May  8 10:41:24

**Comment by stefaweb** [comment]
Could you quote the log and queue file? Edit your post.

Like this `dfdsfdfdsg`

**Comment by armorharmer** [comment]
You mean code?
Done.

**Comment by stefaweb** [comment]
Sorry 'code' as well.
The header seems broken. Try to redo a paste with code directly.

Sorry, I'm a Exim user. No way to have the Subject: in Postfix log?

**Comment by stefaweb** [comment]
I tried here with 

`=?UTF-8?B?8J+YgCDwn5iDIPCfmIQg8J+YgSDwn5iGIPCfmIUg8J+Ygg==?=
`

Works.

**Comment by armorharmer** [comment]
I'm an Exim user too! 

Here's fixed Header from Postfix log:

```
May  8 10:43:58 mailscanner postfix/smtpd[16358]: 2E2C240953: client=mail-qk0-f169.google.com[209.85.220.169]
May  8 10:43:58 mailscanner postfix/cleanup[16361]: 2E2C240953: hold: header Received: from mail-qk0-f169.google.com (mail-qk0-f169.google.com [209.85.220.169])??by mailscanner.test.com (Postfix) with ESMTP id 2E2C240953??for <andros@test.info>; Mon,  8 May 2017 10:43 from mail-qk0-f169.google.com[209.85.220.169]; from=<mangobaobab@gmail.com> to=<andros@test.info> proto=ESMTP helo=<mail-qk0-f169.google.com>
May  8 10:43:58 mailscanner postfix/cleanup[16361]: 2E2C240953: message-id=<CALBvqar9xWFNaEW3FbithBRwA5GHfB5mYUiD-USxo9-7=6LTHw@mail.gmail.com>
May  8 10:43:58 mailscanner postfix/smtpd[16358]: disconnect from mail-qk0-f169.google.com[209.85.220.169]
```

**Comment by armorharmer** [comment]
OK, so it's working for you. Maybe something related to Postfix?

https://github.com/mailwatch/MailWatch/issues/238 , did you see this?

**Comment by stefaweb** [comment]
Try this:

```
    # Get rid of control chars and fix chars set in Subject
    my $subject = $message->{utf8subject};
    $subject =~ s/\n/ /g;  # Make sure text subject only contains 1 line (LF)
    $subject =~ s/\t/ /g;  # and no TAB characters
    $subject =~ s/\r/ /g;  # and no CR characters
    $subject =~ fix_latin($subject);
```

I'm not sure if the syntax is right.

**Comment by armorharmer** [comment]
The syntax seems right but I got the same error: 

Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xF0\x9F\x98\x80 \xF0...' for column 'subject' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 189, <CLIENT> line 216.
) at /usr/share/MailScanner/perl/MailScanner/Config.pm line 1053

**Comment by stefaweb** [comment]
Sorry, no more idea.
May be the problem is not in MailWatch.pm but in MySQL 5.6. I'm using MariaDB.

**Comment by armorharmer** [comment]
stefaweb, thank you for your help.
I will try with MariaDB when I got some free time.

**Comment by endelwar** [comment]
@armorharmer did you run the upgrade.php script after install? Seem like that tables are not in utf8mb4 format.
If after running it you get the same error try to force utf8mb4 charset in `my.cnf`

```
[client]
default-character-set = utf8mb4

[mysql]
default-character-set = utf8mb4

[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
```

**Comment by armorharmer** [comment]
@endelwar thank you for your answer. I didn't run upgrade.php. Yes you are correct, the tables are not in utf8mb4, but I converted Subject column to be. And I also have 

[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

after that I could read utf8 characters in mailwatch, but after some time if someone sends me emoji character, mailwatch is not longer writing to the db and after that I've changed next line
from: my $subject = fix_latin($message->{utf8subject});
to: my $subject = $message->{subject};

**Comment by stefaweb** [comment]
If you restart mailscanner after an "emoji crash", does mailwatch logs goes back?

**Comment by armorharmer** [comment]
Yes, but service stop doesn't work, because one of the PIDs is still active. Killall does it.
I also have DOS problem: 

Clients got this:
MailScanner was attacked by a Denial Of Service attack, and has therefore deleted this part of the message. Please contact your e-mail providers for more information if you need it, giving them the whole of this report

and maillog says:
MailScanner[4953]: Content Checks: Detected and have disarmed KILLED tags in HTML message in 34A10A70.A496E from soandso@foo.com

but that is MailScanner issue as far as I can say...

**Comment by stefaweb** [comment]
"MailScanner was attacked by a Denial Of Service attack" already saw this but I've forgotten the reason. Look at Google.

**Comment by armorharmer** [comment]
Found the solution. It seems that it's related to spam assassin timeout...

**Comment by armorharmer** [comment]
Having the problem again, even when I removed fix_latin and utf8:

```
mailsecurity MailScanner[46464]: Could not use Custom Function code MailScanner::CustomConfig::InitMa
ilWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execut
e failed: Incorrect string value: '\xE8un pr...' for column 'subject' at row 1 at /usr/share/MailScanner/perl/custom/
MailWatch.pm line 189, <CLIENT> line 1171.
```

Please help.

**Comment by endelwar** [comment]
Which version of `DBD::mysql`are you running? Version prior to 4.042 have some problems with utf8

**Comment by armorharmer** [comment]
```
DBD::mysql
-------------------------------------------------------------------------
	(no description)
	M/MI/MICHIELB/DBD-mysql-4.042.tar.gz
	/usr/lib64/perl5/DBD/mysql.pm
	Installed: 4.013
	CPAN:      4.042  Not up to date
	Patrick Galbraith (CAPTTOFU)
	patg@patg.net

```

**Comment by asuweb** [comment]
run `cpan -i DBD::mysql` to upgrade it

**Comment by endelwar** [comment]
utf8mb4 support was added in 4.032_02 (development version) on 2015-06-15 (stable 4.032 version released on 2015-07-20): before 4.032_02 there is **no support for emoji** in DBD::mysql

**Comment by armorharmer** [comment]
Guys, I did this, and it seems that it's working! Thanks a lot! 
I did the DBD::mysql upgrade and also downloaded mailwatch pm scripts from GIT, where I put db connection settings in MailWatch.pm instead of MailWatchConf.pm where they were before.

Again, @endelwar thank you very much and have a nice day!

**Comment by stefaweb** [comment]
Please close the issue.

**Comment by endelwar** [comment]
I've updated online docs to remember this version constrain http://docs.mailwatch.org/install/getting-started.html

**Comment by stefaweb** [comment]
@endelwar 
With Debian Jessie, we have libdbd-mysql-perl 4.028-2. It works with MailWatch. But I don't know why as this is a old version (but Debian patched). Not found something about utf8 in changelog.

I've not found a way to update it to 4.032. 
Manual cpan update breaks all and no way to install it manually too (dependencies).

An idea?

**Comment by pdwalker** [comment]
endelwar, 

given my experience in https://github.com/mailwatch/MailWatch/issues/773, you might want to mention 5.4 as a minimum with full unicode support.
