### ISSUE TITLE
Issue using remote SMTP server to send mailwatch emails

### ISSUE THREAD

**Issue by asuweb** [mailwatch/MailWatch#792]
There is a bug where emails fail to send when using a remote mailserver to send MailWatch emails (quarantine reports etc)

The pear Mail package uses localhost as the HELO name in SMTP transactions unless specifically declared.  This results in mail being rejected on remote mail servers that conduct HELO checks.

The associated PR fixes this issue.

**Comment by asuweb** [comment]
Fixed in #793

**Comment by Skywalker-11** [comment]
can be closed
