### ISSUE TITLE
Problem to clean old mail with mailwatch_db_clean.php / reports and Exim

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#800]
With last develop.

Something seems wrong with develop version. May be the problem is there from a long time.

Running `mailwatch_db_clean.php` manually, don't purge old messages, or we have an error in reports or the database record is corrupted. 

![4c507a34-3ee7-11e7-9721-6c5634cc0c05](https://cloud.githubusercontent.com/assets/12907102/26305570/23cd4df4-3ef0-11e7-92e9-8593af47b913.png)

But I have in config.php: ` define('RECORD_DAYS_TO_KEEP', 60);`

In maillog, the oldest record look like this:

```
timestamp: 2017-03-23 20:10:54
date: 2017-01-22
time: 18:14:51
```
And in report, I got this (start with 22/01/17).
![422dd188-3ef0-11e7-87e8-2de9a8e3de27](https://cloud.githubusercontent.com/assets/12907102/26305654/7dc1d492-3ef0-11e7-8228-56475cb113c7.png)

Report print `date` but where is the true?

**Comment by stefaweb** [comment]
Problem in the database.

![capture d ecran 2017-05-22 a 13 25 22](https://cloud.githubusercontent.com/assets/12907102/26306058/363cb93c-3ef2-11e7-8d7c-40ca0dd51bf6.png)

**Comment by stefaweb** [comment]
The database.
If someone have an idea?

Start
![capture d ecran 2017-05-22 a 13 31 01](https://cloud.githubusercontent.com/assets/12907102/26307263/fce68f26-3ef3-11e7-9b5f-8484287c4770.png)

Change
![capture d ecran 2017-05-22 a 13 38 14](https://cloud.githubusercontent.com/assets/12907102/26307283/111ad0ce-3ef4-11e7-9d79-20c887ca2305.png)

**Comment by Skywalker-11** [comment]
If you look in mailwatch_db_clean.php you can see that nothing is deleted from maillog. Only mtalog is cleared

**Comment by Skywalker-11** [comment]
```
>show create table maillog;
........
CREATE TABLE `maillog` (
  `maillog_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
.......
```
So everytime the mail is beeing updated (creation, sa-learn, release, etc.) the timestamp will change to the current time and the mail will stay another 60 days in the db.

**Comment by stefaweb** [comment]
Done.

**Comment by Skywalker-11** [comment]
I think we should not close this yet but change the timestamp to only be set to CURRENT_TIMESTAMP on creation and not on update.

**Comment by Skywalker-11** [comment]
@endelwar was there a reason that we change the timestamp on update?

**Comment by endelwar** [comment]
`maillog.timestamp` is updated when a message is `quarantine_learn()`ed or managed by , I think that it is there for keeping track of last learn date/time, but actually this information is not used in code logic.
I think that `mailwatch_quarantine_maint.php` and `mailwatch_db_clean.php` should rely on `maillog.date` and `maillog.time` for `RECORD_DAYS_TO_KEEP` calculation.

**Comment by stefaweb** [comment]
This kind of lines?

```
mailwatch_db_clean.php:dbquery('DELETE LOW_PRIORITY FROM maillog WHERE timestamp < (NOW() - INTERVAL ' . RECORD_DAYS_TO_KEEP . ' DAY)');
mailwatch_quarantine_maint.php: $sql = "UPDATE maillog SET timestamp=timestamp, quarantined=1 WHERE id='$id'";
mailwatch_quarantine_maint.php: $sql = "UPDATE maillog SET timestamp=timestamp, quarantined = NULL WHERE id='$id'";
```

**Comment by Skywalker-11** [comment]
@endelwar at the moment we use that timestamp eg on detail.php to show the date on which the mail was received: [https://github.com/mailwatch/MailWatch/blob/master/mailscanner/detail.php#L76](https://github.com/mailwatch/MailWatch/blob/master/mailscanner/detail.php#L76). So on update that wouldn't be correct anymore

**Comment by Skywalker-11** [comment]
How shall we proceed with this?

**Comment by stefaweb** [comment]
I don't know what should be done but I am very concerned that this problem is solved. 😃

**Comment by endelwar** [comment]
Looking at the perl code that populate timestamp, date and time (https://github.com/mailwatch/MailWatch/blob/master/MailScanner_perl_scripts/MailWatch.pm#L300-L306) (spoiler: they all come from local server elaboration time) it doesn't make sense to update timestamp on every row editing, unless we want to keep somewhere a record of last editing of the row itself.
As usual two path:
- keep autoupdate on `timestamp` field and use it as a reminder of last interaction, and use `CONCAT(date, ' 0, time)` instead of `timestamp` in queries
- remove autoupdate on `timestamp` field, losing last interaction time, but without modify actual code

**Comment by Skywalker-11** [comment]
Third option: 
* remove autoupdate on timestamp and add new field last_update

That we  don't have to change anything but the sql schema for that two fields

**Comment by endelwar** [comment]
I like the third option!

**Comment by Skywalker-11** [comment]
done in that pr

**Comment by endelwar** [comment]
> That we don't have to change anything but the sql schema for that two fields

We should remove any instance of `UPDATE maillog SET timestamp=timestamp` (et similar) from code login and crontab scripts

**Comment by Skywalker-11** [comment]
lol that logic `set timestamp=timestamp` :grin:

**Comment by Skywalker-11** [comment]
done

**Comment by endelwar** [comment]
> lol that logic set timestamp=timestamp

yeah, because of the autoupdate field 😄

**Comment by stefaweb** [comment]
Ok to close?

**Comment by Skywalker-11** [comment]
Should be ok

**Comment by endelwar** [comment]
Found a bug on mysql 5.5: there can't be 2 fields with default CURRENT_TIMESTAMP.
I'm working on a fix

**Comment by stefaweb** [comment]
Hello!

The problem is back with 1.2.5.

![chart](https://user-images.githubusercontent.com/12907102/29653451-1aee6606-88aa-11e7-9216-5a450ce54699.png)
