### ISSUE TITLE
SA-Learn blocking apache server

### ISSUE THREAD

**Issue by Skywalker-11** [mailwatch/MailWatch#801]
When running sa-learn on an apache2 server it blocks all other navigation on the page.

Steps to reproduce:
1. Login
2. Go to Search and Reports>Message Operations
3. Select a batch of messages that you want to be learned by SA. Submit the form
4. While the learning is running try to navigate to an other page

**Comment by stefaweb** [comment]
Bug of the month!
😉

**Comment by shawniverson** [comment]
👏 👏
