### ISSUE TITLE
Minor improvements to mailwatch upgrade

### ISSUE THREAD

**Issue by th3penguinwhisperer** [mailwatch/MailWatch#803]
Hi,

Thanks for all the work and efforts that went to mailscanner.

I just updated from 1.2.0 to 1.2.2 on a FreeBSD system and it went successful.

I'd just like to propose some minor improvements.

While it was not that much work it would have been handy if $pathToFunctions could be specified in conf.php because now I always have a file that diverted from the git repository (for an update I do a git pull and put the necessary conf.php in place).

Also for sf_version.php it seems I need to specify a full path to make it work:
diff --git a/mailscanner/sf_version.php b/mailscanner/sf_version.php
index 2803b9e..d4072f6 100644
--- a/mailscanner/sf_version.php
+++ b/mailscanner/sf_version.php
@@ -73,7 +73,7 @@ if ($_SESSION['user_type'] !== 'A') {
     }
     echo '<br>' . "\n";
     echo 'SpamAssassin ' . __('version11') . ' ';
-    passthru("spamassassin -V | tr '\\\n' ' ' | cut -d' ' -f3");
+    passthru("/usr/local/bin/spamassassin -V | tr '\\\n' ' ' | cut -d' ' -f3");
     echo '<br>' . "\n";
     echo '<br>' . "\n";
     echo 'PHP ' . __('version11') . ' ' . $php_version . '<br>' . "\n";

As a last, when I did the database upgrade I had these 2 non-ok lines:
 - Convert table `mtalog_ids` to utf8mb4.............................. DO NOT EXISTS
 - Convert table `mtalog_ids` to InnoDB............................... DO NOT EXISTS

So I manually dived into the upgrade.sql and copy paste the SQL statement to create this table.
No biggy for me, but perhaps it's possible to have an incremental upgrade script of the database (maybe one SQL file per vesion increase and when upgrading only the necessary parts can be taken)?
Perhaps this was already a leftover/incorrect upgrade in a previous version.

**Comment by stefaweb** [comment]
> spamassassin

We can't hard code the path of spamassassin in sf_version.php because path change depending of the OS.
But we can add a constant with the full path of spamassassin in config.php may be.

**Comment by Skywalker-11** [comment]
I created a PR (see above) would this solve the problem with the path?

**Comment by Skywalker-11** [comment]
@th3penguinwhisperer did you do a new install for 1.2.0 or was it an upgrade?
If it was a new install there should be a table for `mtalog_ids`: [https://github.com/mailwatch/MailWatch/blob/v1.2.0/create.sqll#L182](https://github.com/mailwatch/MailWatch/blob/v1.2.0/create.sqll#L182)

**Comment by th3penguinwhisperer** [comment]
> But we can add a constant with the full path of spamassassin in config.php may be.
I can fully understand you can't hardcode it, that would be "bad practice" in my opinion. But indeed having a constant in the config would tackle this :)

I didn't do a new install. I had already 1.2.0 running and pulled the newest version. Then merged my own config with the 1.2.2 sample.

I have to say nice job on being so responsive!

**Comment by Skywalker-11** [comment]
@th3penguinwhisperer the problems you mentioned should be fixed in develop. So you can close this issue
