### ISSUE TITLE
Upgrade problem.

### ISSUE THREAD

**Issue by Lichengchang** [mailwatch/MailWatch#809]
Hi,
I upgrade Mailwatch from "1.2.0 - RC 4" to "1.2.2", appear error message :
![mg1](https://cloud.githubusercontent.com/assets/25293877/26434773/53e26976-413d-11e7-8bbd-6382e42fe8cd.png)

System info :
![mg2](https://cloud.githubusercontent.com/assets/25293877/26434805/75ee4b7a-413d-11e7-8321-ac542b9e8bb7.png)

Should anyone come up with any ideas I would appreciate.
Thank you.

**Comment by Skywalker-11** [comment]
Can you check if the `$pathToFunctions = ` in upgrade.php is pointing to the functions.php from 1.2.2 and not the 1.2.0-RC4 one? The file it points to should contain `function generateToken()` in line 4512 (see [https://github.com/mailwatch/MailWatch/blob/v1.2.2/mailscanner/functions.php#L4512](https://github.com/mailwatch/MailWatch/blob/v1.2.2/mailscanner/functions.php#L4512)

**Comment by Lichengchang** [comment]
Hi,

I replace $pathToFunctions to "/usr/local/src/MailWatch-1.2.2/mailscanner/functions.php"
![mg1](https://cloud.githubusercontent.com/assets/25293877/26612763/579b428a-45e9-11e7-8972-c308b604fdd0.png)

Try again still appear error message :
![mg2](https://cloud.githubusercontent.com/assets/25293877/26612837/eae0b11a-45e9-11e7-9860-b1ed89bf22a9.png)

**Comment by asuweb** [comment]
I'm assuming `conf.php` exists in the path /usr/local/src/MailWatch-1.2.2/mailscanner/conf.php?

**Comment by Lichengchang** [comment]
I change conf.php.example to conf.php then try again :

![mg1](https://cloud.githubusercontent.com/assets/25293877/26622119/ea000b24-461b-11e7-95ae-d0aa5e0ed166.png)

**Comment by asuweb** [comment]
Seems to be working now.  :)

**Comment by endelwar** [comment]
you should copy over your old conf.php if this is an upgrade

**Comment by Lichengchang** [comment]
In version 1.2.0 - RC 4 is normal :
![mg1](https://cloud.githubusercontent.com/assets/25293877/26709190/6f712b22-4783-11e7-8251-f88a7f68a838.png)

Upgrade to 1.2.2 is unusual :
![mg2](https://cloud.githubusercontent.com/assets/25293877/26709230/ce46c2a6-4783-11e7-8c3c-7cc0f12717fc.png)

**Comment by Lichengchang** [comment]
"SEARCH AND REPORTS" function all not work

![mg3](https://cloud.githubusercontent.com/assets/25293877/26709868/8acb9920-4788-11e7-8301-21d0f9203d47.png)

**Comment by stefaweb** [comment]
Could you try with last 1.2.3 in master?

**Comment by Lichengchang** [comment]
I try to upgrade v1.2.3, also problems :
![mg1](https://cloud.githubusercontent.com/assets/25293877/26723308/8529f6c2-47c6-11e7-8004-8bdd7a3e841d.png)

**Comment by Lichengchang** [comment]
Hi,

I use v1.2.3.tar.gz install new MailWatch, display same error message :

Warning: require_once(PEAR.php): failed to open stream: No such file or directory in /var/www/html/mailscanner/lib/pear/Mail/mimeDecode.php on line 65

Fatal error: require_once(): Failed opening required 'PEAR.php' (include_path='/var/www/html/mailscanner/lib/htmlpurifier/standalone:.:/opt/mailwatch/mailscanner/lib/pear:/opt/mailwatch/mailscanner/lib/xmlrpc') in /var/www/html/mailscanner/lib/pear/Mail/mimeDecode.php on line 65

**Comment by shawniverson** [comment]
Check MAILWATCH_HOME in conf.php. It appears the path is pointing to
/opt/mailwatch/mailscanner instead of /var/www/html/mailscanner in the
branches.

**Comment by Lichengchang** [comment]
OK, I replace MAILWATCH_HOME to /var/www/html/mailscanner,  is work.

But "1.2.0 - RC 4" upgrade to "1.2.3" still some error :
error 1 :
![mg1](https://cloud.githubusercontent.com/assets/25293877/26725440/28aefba8-47d1-11e7-844e-e173de0f2b4a.png)

error 2 : SEARCH AND REPORTS > Total Messages by Date
![mg2](https://cloud.githubusercontent.com/assets/25293877/26725477/51306c4c-47d1-11e7-8c1c-f9a4da610f32.png)

Should anyone come up with any ideas I would appreciate.
Thank you.

**Comment by Skywalker-11** [comment]
@Lichengchang You probably moved MailWatch to an other server or other ip and moved the database over. Which is why MailWatch is trying to contact the old server ip which first received the mail. On that server you seem to have a redirect (HTTP 301). 

The second problem will be solved by current develop which will replace the JpGraph library.
