### ISSUE TITLE
Wishlist: Add GeoIP Update to cron.monthly

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#816]
In some cases after an update, the GeoIP database is emptied.

It would be good to have a warning message in the header of the status.php page asking to update the GeoIP database.

GeoIP update code can also be rewrote to be managed by cron.daily... But this is another story.

**Comment by shawniverson** [comment]
https://github.com/E-F-A/v3/blob/3.0.2.3/build/EFA/geoip_update_cmd.php

**Comment by shawniverson** [comment]
A caveat.....it is important to chown the *dat files after running so that they are correct.  This can probably be incorporated into the script, of course.

```
 chown apache:apache /var/www/html/mailscanner/temp/*dat
```

**Comment by shawniverson** [comment]
Another caveat....maxmind is strict on public geoip updates, be cautious about using cron to update this....I think they have an update frequency policy....be sure to check and make sure.

**Comment by asuweb** [comment]
This should be set to update say once per month on a cron I think. We should also add this to the upgrade script as it usually removes the geoip data on upgrade.

**Comment by stefaweb** [comment]
Started to work on this in #826.

**Comment by endelwar** [comment]
> The GeoLite2 Country and City databases are updated on the first Tuesday of each month.
(quote from https://dev.maxmind.com/geoip/geoip2/geolite2/)

A check on web gui about the first Tuesday would be a nice addon

**Comment by Skywalker-11** [comment]
can this be closed?

**Comment by stefaweb** [comment]
Done.
