### ISSUE TITLE
SpamAssassin Rule Hits %

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#833]
Last develop.

% in last column seems to not working. Alway 100%.

![capture d ecran 2017-06-04 a 15 38 55](https://cloud.githubusercontent.com/assets/12907102/26763107/346e6b40-494d-11e7-9e10-8a03a38a1fe3.png)

**Comment by Skywalker-11** [comment]
It looks correct. The percentage there shows what percentage of the messages for that the rule was applied was spam or ham. Because you always have 0 Ham they have 100% spam

**Comment by stefaweb** [comment]
ok, I was wrong. I understood that this percentage showed the ratio of the rules.
