### ISSUE TITLE
Listed in RBL in detail.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#845]
Do we really need to enclose RBL between `(...)` ?

![capture d ecran 2017-06-11 a 18 15 31](https://user-images.githubusercontent.com/12907102/27012563-22d3c576-4ed2-11e7-858b-289590b18b1a.png)

**Comment by stefaweb** [comment]
Another question.

If High Score Spam = YES, is it logical to have Spam to Yes too?

(on my system HSS = 15)

![capture d ecran 2017-06-12 a 15 22 23](https://user-images.githubusercontent.com/12907102/27035857-2464cc94-4f83-11e7-8e51-d50c131d5ac1.png)

**Comment by stefaweb** [comment]
Error.

**Comment by asuweb** [comment]
> Do we really need to enclose RBL between (...) ?

The brackets don't have any technical advantage, so no we don't really need them, but equally, I can't see an issue in them being there.  

> If High Score Spam = YES, is it logical to have Spam to Yes too?
I would say it's more logical this way than having Spam = NO, and High Score Spam = YES, as one contradicts the other. We could write code to remove the SPAM line when high score spam = YES, but I'm not sure the effort is worth the reward personally.

**Comment by Skywalker-11** [comment]
I go with asuweb regarding the spam marking. It wouldn't be logical if it is high score spam but marked as "Spam = NO"

**Comment by stefaweb** [comment]
ok, I can close this.
