### ISSUE TITLE
Wishlist: Remove mouse over in some box of status.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#869]
As the title said. Mouse over color change not needed in the four boxes.

![capture d ecran 2017-06-20 a 08 45 42](https://user-images.githubusercontent.com/12907102/27320150-1e684f4c-5595-11e7-83e9-e7b5cac25545.png)

**Comment by asuweb** [comment]
Fixed in #906

**Comment by stefaweb** [comment]
Great!
