### ISSUE TITLE
Bottom legend in graph

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#870]
The too large space between the graphic and the bottom legend is back!

![capture d ecran 2017-06-22 a 13 13 56](https://user-images.githubusercontent.com/12907102/27431455-e4b919ac-574c-11e7-8a65-78b97011382c.png)

**Comment by stefaweb** [comment]
I've forgotten. If you can, use K to reduce number of zero. It's not easy to read as this.

![27431455-e4b919ac-574c-11e7-8a65-78b97011382c](https://user-images.githubusercontent.com/12907102/27431685-a701cca2-574d-11e7-93c0-d7bf7be20674.png)

**Comment by Skywalker-11** [comment]
Forgot to apply the fix for the alignment on the bundle.js files. PR does that and uses KB, MB etc. for the volume 
![image](https://user-images.githubusercontent.com/11180862/27440342-b54453a8-576a-11e7-96b8-687c743f2c76.png)

**Comment by stefaweb** [comment]
Done.
