### ISSUE TITLE
Wishlist: Add MTA version in sf_version.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#895]
As the title said.

Add MTA version in sf_version.php between MailWatch and MailScanner line.

![capture d ecran 2017-07-05 a 15 39 27](https://user-images.githubusercontent.com/12907102/27866938-7bd37b20-6198-11e7-968b-63009d5f2a0a.png)

For Exim:

```
# /usr/sbin/exim -bV | grep "Exim version"

Exim version 4.84_2 #1 built 14-Jun-2017 11:59:29

```

**Comment by Skywalker-11** [comment]
postfix:
```
# postconf -d | grep "mail_version ="
mail_version = 2.11.3
```

**Comment by stefaweb** [comment]
For Sendmail (from the doc).

```
# sendmail -d0.1 -bt < /dev/null

Version 8.12.9p2
Compiled with DNSMAP LOG MAP_REGEX MATCHGECOS MILTER MIME7TO8 MIME8TO7
NAMED_BIND NETINET NETINET6 NETUNIX NEWDB NIS PIPELINING SCANF
STARTTLS TCPWRAPPERS USERDB XDEBUG
============ SYSTEM IDENTITY (after readcf) ============
(short domain name) $w = host
(canonical domain name) $j = host.domain.com
(subdomain name) $m = domain.com
(node name) $k = host.domain.com
=======================================================

```

**Comment by Skywalker-11** [comment]
`sendmail -d0.4 -bv root  | grep Version` should work
[http://www.sendmail.org/~ca/email/lfaq.html#VERSION](http://www.sendmail.org/~ca/email/lfaq.html#VERSION)

**Comment by stefaweb** [comment]
But how to know/select if exim/postfix/sendmail/other-don't print ?

**Comment by Skywalker-11** [comment]
mta setting of mailscanner

**Comment by stefaweb** [comment]
Done.
