### ISSUE TITLE
Slight tidy on install docs

### ISSUE THREAD

**Issue by mealerz** [mailwatch/MailWatch#900]
Just need to remove this from the install docs on the website - 

 $ chown root:apache images/cache
 $ chmod ug+rwx images/cache

When I ran the upgrade script it said this was not needed any more. I did create this since the docs said I had to change permissions / owners / groups etc. The upgrade.php script complained and said it couldn't remove it, but it did remove it? Maybe that needs looking at as well.

**Comment by Skywalker-11** [comment]
Can be closed
