### ISSUE TITLE
RBL Injection - Feature request

### ISSUE THREAD

**Issue by mealerz** [mailwatch/MailWatch#901]
I run my own RBL since I work for an ISP and we have a lot of incoming email. I use my own Mailwatch reports sometimes to gather a list of hosts that are clearly compromised. It would be useful to have some sort of feature that gathered a list of compromised hosts so these can be added to a central location, or RBL for use by others. I'm not sure what others think about this idea.

**Comment by Skywalker-11** [comment]
You can already do this. Just go to the detail page of an mail and in the row of `Received from:` click on the `Add to blacklist` there you will get to the black/white list page where you can add the ip. On the detail page you can also see all viruses and spams that you already have received from one of the relaying servers. Covers that what you want to achieve?

Else you can always go to the mysql database and query the servers that send mails that are marked as spam/virus like this:
`select clientip, count(virusinfected) as viruscount, count(isspam) as spamcount from maillog where isspam=1 or virusinfected=1 group by clientip;`
