### ISSUE TITLE
SQLSpamSettings.pm is not used

### ISSUE THREAD

**Issue by Skywalker-11** [mailwatch/MailWatch#902]
The functions in SQLSpamSettings.pm aren't used by MailScanner. I placed debug output at the beginning of all functions and none of them has been called. 

Is there something missing in the install instructions has something in MailScanner changed that it is not working anymore?

**Comment by stefaweb** [comment]
What the MailScanner version used?

**Comment by Skywalker-11** [comment]
I think it was 5.0.3 but I have to look it up later

**Comment by stefaweb** [comment]
I've the 5.0. (manually compiled March 29 from GitHub) and no problem here on my dev and prod server.

**Comment by Skywalker-11** [comment]
I just checked and it is 5.0.3 installed with the installation script so it should be 5.0.3-7. The file is loaded but functions aren't called

**Comment by asuweb** [comment]
I'm assuming mailscanner needs to be told to use SQLSpamSettings, but I can't seen any reference to this in the docs?

**Comment by Skywalker-11** [comment]
I just created a new VM with the 5.0.3 version and it seems to work there. Will try to investigate further.

**Comment by Skywalker-11** [comment]
I could reproduce this on an ARM system running Raspbian but seems to work fine with normal Debian on x64 and x86 systems. Maybe thigs in the perl libraries are broken in Raspbian.
