### ISSUE TITLE
Undefined variable: null in functions.php on line 1404

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#903]
With last develop version.

`Notice: Undefined variable: null in /var/www/html/mailscanner/functions.php on line 1404
`

![capture d ecran 2017-07-25 a 09 16 04](https://user-images.githubusercontent.com/12907102/28560307-6e355ec0-711a-11e7-9a9b-70edafd57e43.png)

**Comment by endelwar** [comment]
Could you please add a `var_dump($virus_reports);` between lines 1401 and 1402 and post the values?

**Comment by stefaweb** [comment]
Hi @endelwar!

I got this:

```
Notice: Undefined variable: virus_reports in /var/www/html/mailscanner/functions.php on line 1402
NULL 
```

**Comment by endelwar** [comment]
I need more debug, please change var_dump line with this: `var_dump(VIRUS_REGEX, $row->report, $virus_reports);` (omit sensitive data if needed)

**Comment by stefaweb** [comment]
Got this:

```
Notice: Use of undefined constant VIRUS_REGEX - assumed 'VIRUS_REGEX' in /var/www/html/mailscanner/functions.php on line 1402

Notice: Trying to get property of non-object in /var/www/html/mailscanner/functions.php on line 1402

Notice: Undefined variable: virus_reports in /var/www/html/mailscanner/functions.php on line 1402
string(11) "VIRUS_REGEX" NULL NULL 
Notice: Undefined variable: null in /var/www/html/mailscanner/functions.php on line 1405
```

**Comment by stefaweb** [comment]
In conf.php (default)

```
// Override VIRUS_REGEX??
// define('VIRUS_REGEX', '/(\S+) was infected by (\S+)/'); // SophosSAVI
```

**Comment by Skywalker-11** [comment]
Try changing `$null` to `null` in line 1404

**Comment by stefaweb** [comment]
The error message is gone with "null".

But if `var_dump(VIRUS_REGEX, $row->report, $virus_reports);`, I still have:

```
Notice: Use of undefined constant VIRUS_REGEX - assumed 'VIRUS_REGEX' in /var/www/html/mailscanner/functions.php on line 1402

Notice: Trying to get property of non-object in /var/www/html/mailscanner/functions.php on line 1402
```

Notice: Undefined variable: virus_reports in /var/www/html/mailscanner/functions.php on line 1402
string(11) "VIRUS_REGEX" NULL NULL

**Comment by endelwar** [comment]
Sorry, my bad, I was looking in master branch and not develop branch! As @Skywalker-11 said line 1404 must read ` $top = null;`

**Comment by Skywalker-11** [comment]
The current version does not explicitely use the VIRUS_REGEX anymore but uses the function getVirusRegex instead. This was changed with #874 for support of multiple virus scanners.

**Comment by Skywalker-11** [comment]
VIRUS_REGEX is only used to overwrite the MailScanner scanner configuration

**Comment by endelwar** [comment]
should be ok with last commit

**Comment by stefaweb** [comment]
Great. I close.
