### ISSUE TITLE
About quarantine release function

### ISSUE THREAD

**Issue by Lichengchang** [mailwatch/MailWatch#908]
I release mail from quarantine, then display error message :
![mg](https://user-images.githubusercontent.com/25293877/28766243-51c93fcc-7601-11e7-9c2b-ff16302deb79.png)

## Server configuration
MailWatch Version: 1.2.4
MailScanner Version: 5.0.3
PHP Version: 5.6.30
MySQL Version: 10.1.25-MariaDB

**Comment by asuweb** [comment]
This has been fixed in the development branch.

**Comment by Lichengchang** [comment]
Next version fix?

**Comment by Skywalker-11** [comment]
@Lichengchang yes it will be fixed by next release. 

@endelwar when do you plan to release 1.2.5?

**Comment by endelwar** [comment]
> @endelwar when do you plan to release 1.2.5?

Monday 21/8, when I return to office

**Comment by Skywalker-11** [comment]
@Lichengchang new version is out: [v1.2.5](https://github.com/mailwatch/MailWatch/releases/tag/v1.2.5)
Can you try if it is fixed?

**Comment by Skywalker-11** [comment]
@Lichengchang any update on this?

**Comment by Lichengchang** [comment]
Upgrade to 1.2.7, is fixed.
Thx.
