### ISSUE TITLE
Wrong formatted report messages when releasing mails

### ISSUE THREAD

**Issue by Skywalker-11** [mailwatch/MailWatch#910]
If you have umlauts in the report messages defined by conf.php variables the conf file needs to be ansi encoded or will be displayed with wrong formatting in mail clients . Eg.
```
define('QUARANTINE_REPORT_FROM_NAME', 'MailWatch für MailScanner');
define('QUARANTINE_REPORT_SUBJECT', 'E-Mail Quarantäne-Bericht');
define('QUARANTINE_SUBJECT', 'Nachricht aus Quarantäne freigegeben');
define('QUARANTINE_MSG_BODY', 'Dies ist eine automatisierte Mail.
Die ursprüngliche E-Mail befindet sich im Anhang dieser Mail.

Mit freundlichen Grüßen,
Eure IT');
```

will result in the following mail body if the conf file encoding is utf-8
```
Dies ist eine automatisierte Mail.
Die ursprÃ¼ngliche E-Mail befindet sich im Anhang dieser Mail.

Mit freundlichen GrÃ¼ÃYen,
Eure IT
```

Thats because the mail encoding defined by the mail headers are "ISO-8859-1" in mailscanner/lib/pear/Mail/mime.php

**Comment by endelwar** [comment]
@Skywalker-11 could you please try the branch https://github.com/mailwatch/MailWatch/tree/feature/fix-mail-headers that should fix this header problem?

**Comment by Skywalker-11** [comment]
Yes working now with utf-8 encoding. 
Problem could be that ANSI/ISO-8859-1 encoding is not working anymore so that people who adjusted the conf file in the past to be ANSI encoded will get the character garbage when they will update MailWatch

**Comment by endelwar** [comment]
Right. I'm going to implement https://github.com/neitanod/forceutf8 for this case to convert safely to utf8, once this library is in place it can be used in other sections of the actual code that deal with unknown encoding (e.g.: email subject or headers)
