### ISSUE TITLE
Create database erro ERROR 1293 (HY000)

### ISSUE THREAD

**Issue by ConceiTI** [mailwatch/MailWatch#914]
Hi dear,

I have installation MailWatch, but whant database this is error:
 mysql -u root -p < create.sql 
Enter password: 
ERROR 1293 (HY000) at line 89: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

Descriptions:
SO = CentOS7
DB = mariadb-5.5.52-1
MailWatch = 1.2.4

**Comment by Skywalker-11** [comment]
Can you try the updated create.sql of #915:
 [https://raw.githubusercontent.com/Skywalker-11/1.2.0/47ecdd8bf6f39f70207e94bd8c6a6eff5951fbbe/create.sql](https://raw.githubusercontent.com/Skywalker-11/1.2.0/47ecdd8bf6f39f70207e94bd8c6a6eff5951fbbe/create.sql)

**Comment by Skywalker-11** [comment]
This problem should be fixed with current develop version
