### ISSUE TITLE
release mail form quarantain

### ISSUE THREAD

**Issue by ghost235** [mailwatch/MailWatch#916]
### Issue summary
Hi,
I got a problem and I don't know where to look for it.
I want to release mails for the quarantain but it sends no mail (I can't see anyting in the mail.log) when I click the release button.

### Steps to reproduce
1. 
2. 
3. 

### Expected result
Tell us what should happen

### Actual result
Tell us what happens instead

### Version and method
 - MailWatch Version: [ stable 1.2.2]
 - Install type: [  Zip/tarball install  ]
 - Updated from an older MailWatch or fresh install: [ Fresh install ]

### Server configuration
 - Operation System: [ Debian ]
 - PHP version: [ 5.6.30-0+deb8u1 ]
 - Database: [ MySQL]  version [ 5.6.37 ]
 - Mail Server: [ Postfix ]
 - Used web server: [ Apache ] version [ 2.4.10 ]

### Client configuration 
 - Operation System: [ operation system ] version [ version ]
 - Browser: [ browser name and version ]

**Comment by Skywalker-11** [comment]
Can you anything in the apache log?

**Comment by ghost235** [comment]
[Mon Aug 21 12:09:47.627424 2017] [:error] [pid 13144] [client IP:63718] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:10:10.617469 2017] [:error] [pid 13326] [client IP:63796] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:10:48.623393 2017] [:error] [pid 13325] [client IP:63923] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:11:11.616293 2017] [:error] [pid 13146] [client IP:64003] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:11:23.199762 2017] [:error] [pid 13326] [client IP:53446] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/detail$
[Mon Aug 21 12:11:49.618039 2017] [:error] [pid 13144] [client IP:64133] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:12:12.607873 2017] [:error] [pid 13146] [client IP:64207] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:12:50.615788 2017] [:error] [pid 13326] [client IP:64333] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:13:13.644990 2017] [:error] [pid 13142] [client IP:64404] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:13:51.649799 2017] [:error] [pid 13145] [client IP:64528] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:14:14.611594 2017] [:error] [pid 13144] [client IP:64605] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:14:52.608878 2017] [:error] [pid 13143] [client IP:64752] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:15:15.603048 2017] [:error] [pid 13142] [client IP:64832] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:15:53.736092 2017] [:error] [pid 31045] [client IP:64955] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:15:55.182046 2017] [:error] [pid 31046] [client IP:33839] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/detail$
[Mon Aug 21 12:15:55.182420 2017] [:error] [pid 31046] [client IP:33839] PHP Notice:  Undefined index: token in /opt/mailwatch/mailscanner/detail.php on line 48
[Mon Aug 21 12:15:57.503593 2017] [:error] [pid 31049] [client IP:33849] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/detail$
[Mon Aug 21 12:15:57.503670 2017] [:error] [pid 31049] [client IP:33849] PHP Notice:  Undefined index: token in /opt/mailwatch/mailscanner/detail.php on line 48
[Mon Aug 21 12:16:03.021204 2017] [:error] [pid 31054] [client IP:54196] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/status$
[Mon Aug 21 12:16:16.652572 2017] [:error] [pid 31046] [client IP:65032] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:16:33.348405 2017] [:error] [pid 31045] [client IP:54295] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/status$
[Mon Aug 21 12:16:35.306018 2017] [:error] [pid 31055] [client IP:33974] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/status$
[Mon Aug 21 12:16:35.356621 2017] [:error] [pid 31046] [client IP:33975] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:16:49.131602 2017] [:error] [pid 31055] [client IP:34005] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/checkl$
[Mon Aug 21 12:16:49.307481 2017] [:error] [pid 31054] [client IP:34006] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/status$
[Mon Aug 21 12:16:52.924702 2017] [:error] [pid 31048] [client IP:34010] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/detail$
[Mon Aug 21 12:16:54.611151 2017] [:error] [pid 31046] [client IP:65166] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:16:57.257063 2017] [:error] [pid 31054] [client IP:34043] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/detail$
[Mon Aug 21 12:17:03.631206 2017] [:error] [pid 31047] [client IP:54525] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/status$
[Mon Aug 21 12:17:17.599274 2017] [:error] [pid 31055] [client IP:65237] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:17:25.351333 2017] [:error] [pid 31046] [client IP:34105] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/detail$
[Mon Aug 21 12:17:33.888581 2017] [:error] [pid 31055] [client IP:54566] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/status$
[Mon Aug 21 12:17:55.607842 2017] [:error] [pid 31047] [client IP:65360] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:18:04.156500 2017] [:error] [pid 31049] [client IP:54628] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/status$
[Mon Aug 21 12:18:18.600076 2017] [:error] [pid 31054] [client IP:65439] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:18:34.428470 2017] [:error] [pid 31055] [client IP:54686] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/status$
[Mon Aug 21 12:18:56.599591 2017] [:error] [pid 31054] [client IP:49181] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:19:04.710071 2017] [:error] [pid 31581] [client IP:54759] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/status$
[Mon Aug 21 12:19:19.608127 2017] [:error] [pid 31054] [client IP:49255] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:19:34.978385 2017] [:error] [pid 31581] [client IP:55006] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/status$
[Mon Aug 21 12:19:57.598446 2017] [:error] [pid 31049] [client IP:49380] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:20:05.228342 2017] [:error] [pid 31048] [client IP:55066] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/status$
[Mon Aug 21 12:20:20.594518 2017] [:error] [pid 31045] [client IP:49457] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:20:35.554705 2017] [:error] [pid 31047] [client IP:55129] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/status$
[Mon Aug 21 12:20:58.643403 2017] [:error] [pid 31581] [client IP:49582] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$
[Mon Aug 21 12:21:05.805879 2017] [:error] [pid 31046] [client IP:55161] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/status$
[Mon Aug 21 12:21:21.636121 2017] [:error] [pid 31049] [client IP:49656] PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$

**Comment by Skywalker-11** [comment]
For the errors with `PHP Notice: session_start(): ps_files_cleanup_dir: opendir(/var/lib/php5/sessions) failed: Permission denied (13) in /opt/mailwatch/mailscanner/login.$` See #720

**Comment by Skywalker-11** [comment]
Just to be sure. You have selected the checkbox below "Release" and then hit "Submit"?
![image](https://user-images.githubusercontent.com/11180862/29523321-f29202e0-868c-11e7-9c78-ecc251de4a7b.png)

Do you see a message like this at the bottom of the page after submitting?
![image](https://user-images.githubusercontent.com/11180862/29523142-44ab0140-868c-11e7-9065-2f8d04f66f65.png)

**Comment by ghost235** [comment]
;)
Of course I check release.

And no there is no message.
even if I check "Alternate Recipient" and leave the field enty there is no error.

**Comment by ghost235** [comment]
OK! got it!
I switch back from german to english in conf.php now it works!
Than back to 'de' don't work.
What I have to that it also works in german?

**Comment by stefaweb** [comment]
Variable wrongly localized somewhere.

**Comment by Skywalker-11** [comment]
If I remember correctly there was an problem with a previous version where some logic code used translated values but I think that was fixed already

**Comment by Skywalker-11** [comment]
Can you try updating MailWatch?

**Comment by ghost235** [comment]
Ok I'll try it.
One thing from http://docs.mailwatch.org/install/upgrading.html

Zip install
•download the new release zip file
•uncompress it in a temporary directory
•remove old installed directory and replace it with the new one **<- Which install directory??**
•copy conf.php in mailscanner directory
•replace all cron files with the ones from new release

**Comment by Skywalker-11** [comment]
Directory `mailscanner/` in your case `/opt/mailwatch/mailscanner` and all its contents

**Comment by ghost235** [comment]
Got it!

With 1.2.4 release works in all languages.

Thanks to all!!!
