### ISSUE TITLE
mailwatch shows wrong mailscanner version and no clam av status

### ISSUE THREAD

**Issue by imilanovic** [mailwatch/MailWatch#921]
On software versions tab MailWatch shows wrong mailscanner version (instead 5.0.6 it shows 5.0.3)
Also no info about ClamAV. In Tools and Links, ClamAV status shows empty page.

mailwatch version: 1.2.5
MailScanner: 5.0.6
PHP 5.4.16
MariaDB 10.1.26
Centos 7

**Comment by stefaweb** [comment]
Hello!

For ClamAV, do you have the sudo file installed?

https://github.com/mailwatch/MailWatch/blob/master/tools/sudo/INSTALL

**Comment by imilanovic** [comment]
Yes, but not sure now it related to sudo since there entry about ClamAV in mailwatch sudo file

**Comment by stefaweb** [comment]
Look at this old Issue. May be a problem of right.

https://github.com/mailwatch/MailWatch/issues/367

**Comment by stefaweb** [comment]
Mailscanner version use `$mailscanner_version = get_conf_var('MailScannerVersionNumber');`

Have a look in /etc/MailScanner/MailScanner.conf

`MailScanner Version Number =`

MailWatch use this variable.

**Comment by Skywalker-11** [comment]
If you install a newer version of MailScanner that should also updated the version number in the MailScanner.conf. If that didn't happen you should file a bug in the mailscanner repository

**Comment by stefaweb** [comment]
The best is to do not modify the original MailScanner.conf and use another one in /etc/MailScanner/conf.d/00MailWatch.conf for your own setup.

**Comment by Skywalker-11** [comment]
@imilanovic in /etc/MailScanner/virus.scanners.conf you should have a list of virus scanner with test commands like 
```
clamav                  /usr/lib/MailScanner/wrapper/clamav-wrapper                     /usr
```
Try to execute the test. Here: `/usr/lib/MailScanner/wrapper/clamav-wrapper /usr`
This is used to get the ClamAV version and should output something like `ClamAV 0.99.2/23710/Fri Aug 25 10:37:27 2017`

**Comment by imilanovic** [comment]
Thanks, i resolved issue with Mailscanner version number since I used config from version 5.0.3
Still issue with ClamAV. When I execute
`/usr/lib/MailScanner/wrapper/clamav-wrapper /usr`
I get OK Scan Summary

**Comment by Skywalker-11** [comment]
Does it also work with `sudo -u www-data /usr/lib/MailScanner/wrapper/clamav-wrapper /usr` (replace www-data with the user the webserver is running at)

**Comment by imilanovic** [comment]
I got Permission denied.

**Comment by stefaweb** [comment]
Hello @imilanovic!
Check right of sudo file and content.

**Comment by philrandal** [comment]
With the latest 5.0.6 MailScanner, 

passthru(get_virus_conf('clamav') . ' -V | awk -f ' . __DIR__ . '/clamav.awk');

needs changing to

passthru(get_virus_conf('clamav') . ' /pub  -V | awk -f ' . __DIR__ . '/clamav.awk');

Or someother directory name, otherwise no status is returned.
