### ISSUE TITLE
> character displayed below menu on status page

### ISSUE THREAD

**Issue by gordoncolyn** [mailwatch/MailWatch#923]
Once installed a > character shows up under the menu on the status page.  

Found the problem in functions.php
line 428
`<td class="mcp"></td>>`
should be
`<td class="mcp"></td>`

 - MailWatch Version: 1.2.5
 - Install type: Zip install

**Comment by endelwar** [comment]
Nice catch, thanks!
This has been fixed in develop branch

**Comment by Skywalker-11** [comment]
@endelwar do you want to close this issue?
