### ISSUE TITLE
Total message by date shows no graph in distributed mode

### ISSUE THREAD

**Issue by gordoncolyn** [mailwatch/MailWatch#926]
Total message by date shows no graph when selected, rep_total_mail_by_date.php

I am running a web server in Distributed mode with 2 mailscanner servers and a 3rd mysql server, all other graphs, including mail view and release work perfectly.

On the web server I have;
define('DISTRIBUTED_SETUP', true);

Centos 6.9
MailWatch v1.2.5 upgraded from 1.2.4 and 1.2.3 (zip version)
php version 5.3.3
mysql 5.7.19
postfix 2
apache 2.2.9

**Comment by Skywalker-11** [comment]
@gordoncolyn do you get any errors in the web server log?

**Comment by gordoncolyn** [comment]
Nope, no errors at all... :-(

So dont even know where to start.

**Comment by Skywalker-11** [comment]
Can you look into the html of that page. There should be this
```
<canvas id="trafficgraph" class="lineGraph"></canvas>
  <script src="lib/Chart.js/Chart.bundle.min.js"></script>
  <script src="lib/lineConfig.js"></script>
```
followed by an `<script>` tag and the data for the graph and which ends with a `</script>`.
If that is the case can you post the content between the `<script>` and `</script>` ?
Do you get a table with the statistics on that page?

**Comment by gordoncolyn** [comment]
ok, so to confirm;
When I run the page with [define('DISTRIBUTED_SETUP', true);] i get no graph, but i do get all the stats in the table below the white area that should display the graph.  When I run the page with [define('DISTRIBUTED_SETUP', true);] the graph disaplys perfectly fine.  I get no errors in the logs with either page.

Here is the info on the page that does not display the graph;
     <script>
        COLON = ":";
        printLineGraph("reportGraph",  {
          chartTitle : "Total Mail Processed by Date",
          chartId : "reportGraph",
          chartLabels : ["20/06/17", "21/06/17", "22/06/17", "23/06/17", "24/06/17", "25/06/17", "26/06/17", "27/06/17", "28/06/17", "29/06/17", "30/06/17", "01/07/17", "02/07/17", "03/07/17", "04/07/17", "05/07/17", "06/07/17", "07/07/17", "08/07/17", "09/07/17", "10/07/17", "11/07/17", "12/07/17", "13/07/17", "14/07/17", "15/07/17", "16/07/17", "17/07/17", "18/07/17", "19/07/17", "20/07/17", "21/07/17", "24/07/17", "25/07/17", "26/07/17", "27/07/17", "28/07/17", "29/07/17", "30/07/17", "31/07/17", "01/08/17", "02/08/17", "03/08/17", "04/08/17", "05/08/17", "06/08/17", "07/08/17", "08/08/17", "09/08/17", "24/08/17", "25/08/17", "26/08/17", "27/08/17", "28/08/17", "29/08/17"],
          chartNumericData : [[
[10, 26, 26, 26, 26, 26, 26, 27, 26, 26, 26, 26, 27, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 27, 25, 26, 26, 26, 15, 15, 25, 25, 25, 25, 25, 128, 2441, 2549, 3160, 2272, 2131, 488, 444, 1599, 1754, 749, 1032, 1677, 546, 453, 2258, 1958],[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 18, 136, 28, 130, 8, 7, 24, 34, 12, 3, 6, 319, 4, 11, 10, 11],[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 874, 796, 507, 354, 300, 157, 178, 359, 312, 127, 304, 268, 285, 215, 745, 724],],
[
[9733, 27919, 31152, 27919, 31074, 27918, 27999, 28910, 27838, 30992, 31149, 31071, 30672, 27920, 31148, 27840, 30992, 30991, 31039, 28045, 28046, 31040, 31119, 27887, 31119, 28046, 30927, 27263, 30888, 31120, 31042, 19506, 19856, 30344, 30424, 30419, 30340, 30337, 3361700, 161828214, 191124234, 387351212, 200084123, 137852088, 53357877, 37889835, 159527088, 158793370, 41960050, 82801316, 150829362, 26492160, 67159744, 155498565, 162715459],],
],
          chartFormattedData : [[
["10", "26", "26", "26", "26", "26", "26", "27", "26", "26", "26", "26", "27", "26", "26", "26", "26", "26", "26", "26", "26", "26", "26", "26", "26", "26", "27", "25", "26", "26", "26", "15", "15", "25", "25", "25", "25", "25", "128", "2441", "2549", "3160", "2272", "2131", "488", "444", "1599", "1754", "749", "1032", "1677", "546", "453", "2258", "1958"],["1", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "5", "18", "136", "28", "130", "8", "7", "24", "34", "12", "3", "6", "319", "4", "11", "10", "11"],["2", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "51", "874", "796", "507", "354", "300", "157", "178", "359", "312", "127", "304", "268", "285", "215", "745", "724"],],
[
["9.5kB", "27.26kB", "30.42kB", "27.26kB", "30.35kB", "27.26kB", "27.34kB", "28.23kB", "27.19kB", "30.27kB", "30.42kB", "30.34kB", "29.95kB", "27.27kB", "30.42kB", "27.19kB", "30.27kB", "30.26kB", "30.31kB", "27.39kB", "27.39kB", "30.31kB", "30.39kB", "27.23kB", "30.39kB", "27.39kB", "30.2kB", "26.62kB", "30.16kB", "30.39kB", "30.31kB", "19.05kB", "19.39kB", "29.63kB", "29.71kB", "29.71kB", "29.63kB", "29.63kB", "3.21MB", "154.33MB", "182.27MB", "369.41MB", "190.82MB", "131.47MB", "50.89MB", "36.13MB", "152.14MB", "151.44MB", "40.02MB", "78.97MB", "143.84MB", "25.26MB", "64.05MB", "148.29MB", "155.18MB"],],
],
          xAxeDescription : "Date",
          yAxeDescriptions : ["No. of messages", "Volume"],
          fillBelowLine : [false, true],
          plainGraph : false,
          maxTicks: 10,
          
          
          valueTypes: ["plain","volume"],
          chartDataLabels : [[
"E-mail","Viruses","Spam",],
[
"Volume",],
],
          types : [[
"bar","bar","bar",],
[
"line",],
],
        });
      </script>

**Comment by Skywalker-11** [comment]
Can you try the patched graphgenerator.inc.php from #928 ? It should fix this.

**Comment by gordoncolyn** [comment]
Yep, that resolves the problem!

Thank you
