### ISSUE TITLE
Domain Administrator can modifiy other Domain Administrator

### ISSUE THREAD

**Issue by tomwmt** [mailwatch/MailWatch#927]
Mailwatch v 1.2.5

1.  Create 2 Domain Administrators (test.com and example.com)
2.  Login as test.com
3.  Now you can modify example.com Domain Administrator.

### Expected result
Domain Administrators should not see/edit/delete each other.

### Actual result
Domain Administrators can see/edit/delete each other

### Version and method
 - MailWatch Version: 1.2.5
 - Install type: Zip/tarball install
 - Updated from an older MailWatch or fresh install: Fresh install

### Server configuration
 - Operation System:  Debian 9
 - PHP version: 7.0 
 - Database: MariaDB 10.1.26
 - Mail Server: Postfix
 - Used web server: Apache 2.4.25

### Client configuration 
 - Operation System: Windows 10
 - Browser: Firefox ESR 52.3

![grafik](https://user-images.githubusercontent.com/31435224/29812146-f5eaabda-8ca5-11e7-964e-7320f7d02a1c.png)

**Comment by Skywalker-11** [comment]
@tomwmt The multi domain system is using the username to identify the domain the user is in. Therefore the username has to be a mail address where the domain part (after `@`) if you want to use MailWatch for a multi domain environment.

If the usernames doesn't have a mail address it is assumed that they all are in the domain "no domain" and they can see each other

**Comment by stefaweb** [comment]
The MailWatch convention is "domain-admin@domain.tld".

**Comment by tomwmt** [comment]
I followed this instructions: http://docs.mailwatch.org/using/user-filter.html

**Comment by Skywalker-11** [comment]
Can be closed
