### ISSUE TITLE
Wrong print in detail.php for B/L and W/L

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#929]
In last develop.

The space is not good when using other language than English.

![capture d ecran 2017-08-30 a 11 31 06](https://user-images.githubusercontent.com/12907102/29865971-447412a6-8d77-11e7-901d-20a2b2db48a2.png)

![capture d ecran 2017-08-30 a 11 30 53](https://user-images.githubusercontent.com/12907102/29865972-4493b1e2-8d77-11e7-9db0-c88782e298b4.png)

**Comment by Skywalker-11** [comment]
Can you adding in css `white-space: nowrap;`
 [https://www.w3schools.com/cssref/pr_text_white-space.asp](https://www.w3schools.com/cssref/pr_text_white-space.asp)

**Comment by stefaweb** [comment]
This works (at the end of style.css)

```
a {
    white-space: nowrap;
}
```

**Comment by stefaweb** [comment]
Added PR #931.

**Comment by stefaweb** [comment]
Done.
