### ISSUE TITLE
Issue with emails from Gmail or Google Apps

### ISSUE THREAD

**Issue by quintingsnj** [mailwatch/MailWatch#932]
Emails coming from Gmail or Google Apps do not display message details, just the from ip address, and the rest of the page is blank.  So far I have only noticed this with Gmail and Google Apps. Screenshot is attached.

This should display details of the email in the white space. Again, this works for every other domain that has emailed me in my test environment (hoping to go live with this once the bugs are worked out).

Same results happen in IE and Chrome.

Running MS 5.0.6 and MW 1.2.5

Thanks for any insight into this.

Quintin

![ms-gmail](https://user-images.githubusercontent.com/31482430/29883805-00ffc65a-8d77-11e7-88bc-440bf5c1d8b9.png)

**Comment by Skywalker-11** [comment]
Are there any errors in the webserver or mail log when viewing the page/receiving the mail? 
Is this also happening if you send mails from https://mail.google.com?
Can you also fill out the missing information from [ISSUE_TEMPLATE.md](https://github.com/mailwatch/MailWatch/edit/master/.github/ISSUE_TEMPLATE.md)

It's working for me when I send mails from Gmail app or the google website using a google account:
![image](https://user-images.githubusercontent.com/11180862/29885317-a99798b2-8db6-11e7-9fb0-248591c087d4.png)

**Comment by quintingsnj** [comment]
Thanks for the reply.  I feel a little silly, I had checked the logs, but must have not noticed this error: 

PHP Notice:  Undefined offset: 2 in /opt/mailwatch/mailscanner/functions.php on line 566, referer: http://mailwatch.snjlaw.local/geoip_update.php

In any case, re-ran the GeoIP update, and all is good now....

Also, I apologize if I was lacking info, first time filling out a support request...also, the template that you directed me to, I can't access, it says I need to "fork" it or something...I would, but I already had lunch, and put my fork in the dishwasher.  LOL


Thanks.

**Comment by Skywalker-11** [comment]
@quintingsnj url was my mistake should be [ISSUE_TEMPLATE.md](https://github.com/mailwatch/MailWatch/blob/master/.github/ISSUE_TEMPLATE.md). So basically if you open an issue fill out the formular that it displays to you

But can you leave this issue open for now as we should look at why the geoip cause the rest of the site not to work

**Comment by quintingsnj** [comment]
Re-opened as requested.

**Comment by Skywalker-11** [comment]
Cannot replicate it here. May not be related to geoip at all but only to sendmail problems.

**Comment by Skywalker-11** [comment]
Has anyone else seen this problem?

**Comment by thctlo** [comment]
I do know that i created #1015 because of something simular, but that was 8 months ago. i remember that because i didnt update geo-ip at first with the mailwatch site. 
Thats the only info i have, sorry..

**Comment by endelwar** [comment]
When we migrated to GeoLite2 on 26 Mar 2018 (https://github.com/mailwatch/MailWatch/commit/1e97b3a1673a9bf7db5dca96eab7de376195e069) return_geoip_country function returns false if it cannot find a country for the given ip, so this exception should not appear any more
