### ISSUE TITLE
Undefined Offset

### ISSUE THREAD

**Issue by quintingsnj** [mailwatch/MailWatch#934]
### Issue summary
Have errors showing up in the httpd error logs every 30 seconds it looks like (2 almost identical lines - just the line # is different)

I have searched for this error, and found no other report.

The only thing I have running in cron is the queue monitor, and that is set to every minute, not every 30 seconds.  I have disabled the cron job, and the errors still persist.

### Steps to reproduce
1.  Just leave the system running

### Expected result
Should be no errors in the logs

### Actual result
[Wed Aug 30 12:36:26.419888 2017] [:error] [pid 1977] [client 192.168.0.127:57429] PHP Notice:  Undefined offset: 2 in /opt/mailwatch/mailscanner/functions.php on line 566, referer: http://mailwatch.snjlaw.local/status.php
[Wed Aug 30 12:36:26.437208 2017] [:error] [pid 1977] [client 192.168.0.127:57429] PHP Notice:  Undefined offset: 2 in /opt/mailwatch/mailscanner/functions.php on line 569, referer: http://mailwatch.snjlaw.local/status.php

### Version and method
 - MailWatch Version: [ stable 1.2.5 
 - Install type: Zip/tarball install
 - Updated from an older MailWatch or fresh install: Fresh install

### Server configuration
 - Operation System: CentOS 7
 - PHP version: 5.4
 - Database: MySQL version 5.6.37
 - Mail Server: Sendmail version 8.14.7
 - Used web server: Apache version 2.4.6

### Client configuration  
(N/A in this case)

**Comment by Skywalker-11** [comment]
@quintingsnj sorry for the trouble but there aren't many people who uses sendmail so that parts aren't that well tested.
Can you create a file with the following and then run it  like `sudo -u apache php FILENAME` and give us the output:
```
<?php
            $cmd = exec('sudo ' . SENDMAIL_QUEUE_IN . ' 2>&1');
            var_dump($cmd);
            preg_match("/(Total requests: )(.*)/", $cmd, $output_array);
            var_dump($output_array);
            $inq = $output_array[2];
            var_dump($inq);
?>
```

**Comment by quintingsnj** [comment]
I get this...

[root@mailscanner ~]# sudo -u apache php test.php
Could not open input file: test.php


I am assuming that SENDMAIL_QUEUE_IN should be the sendmail command that I have configured in conf.php?? I so far have just copied and pasted your php code above, and have NOT modified it to contain that, as it seems that it can't read the file...the file is set to world readable...same permissions as the files in my mailwatch/mailscanner folder....

Thanks

**Comment by Skywalker-11** [comment]
Yes SENDMAIL_QUEUE_IN should be replaced with the content of the conf file. Please make sure that the parent directories are also accessible by user apache eg test with `sudo -u apache ls WHATEVERDIR`

**Comment by quintingsnj** [comment]
Now it asks for a password for apache...which I do not have - I believe that is a system user...

running as root produces the following:
string(19) "            Total requests: 0"
array(3) {
  [0]=>
  string(17) "Total requests: 0"
  [1]=>
  string(16) "Total requests: "
  [2]=>
  string(1) "0"
}
string(1) "0"


At this point, I have some other Sendmail issues, so I am going to rebuild (this is still in a lab environment), and try again, probably using postfix this time...and see where I get :)

Thanks for your help

**Comment by asuweb** [comment]
@quintingsnj - Any update on this?

**Comment by bulhoes** [comment]
Hello all,

I have the solution for this problem. I'm setting up a mailscanner with mailwatch system, and I was having the same issue.

It is really simple to solve.

The documentation tells you to place sendmail commands on the sudoers file, but what you need is mailq commands.

Following the documentation, I created the sudoers file for th apache web server as:

```
User_Alias MAILSCANNER = apache
Cmnd_Alias MAILSCANLINT = /usr/sbin/MailScanner
Cmnd_Alias SPAMASSASSINLINT = /usr/bin/spamassassin
Cmnd_Alias SENDMAIL_QUEUE_IN = /usr/bin/sendmail -bp -OQueueDirectory=/var/spool/mqueue.in
Cmnd_Alias SENDMAIL_QUEUE_OUT = /usr/bin/sendmail -bp
MAILSCANNER ALL= NOPASSWD: MAILSCANLINT, SPAMASSASSINLINT, EXIM_QUEUE_IN, EXIM_QUEUE_OUT, SENDMAIL_QUEUE_IN, SENDMAIL_QUEUE_OUT
```

If you correct it to:

```
#
User_Alias MAILSCANNER = apache
Cmnd_Alias MAILSCANLINT = /usr/sbin/MailScanner
Cmnd_Alias SPAMASSASSINLINT = /usr/bin/spamassassin
Cmnd_Alias SENDMAIL_QUEUE_IN = /usr/bin/mailq -bp -OQueueDirectory=/var/spool/mqueue.in
Cmnd_Alias SENDMAIL_QUEUE_OUT = /usr/bin/mailq -bp
MAILSCANNER ALL= NOPASSWD: MAILSCANLINT, SPAMASSASSINLINT, EXIM_QUEUE_IN, EXIM_QUEUE_OUT, SENDMAIL_QUEUE_IN, SENDMAIL_QUEUE_OUT
```

not only you will get rid of the messages, but also you will get the mail queue values on the web interface.

Hope it helps someone.

Kind regards,
JB

**Comment by bulhoes** [comment]
I found out this from the secure log of the system.

You will have a log of "command not allowed" there!

**Comment by Skywalker-11** [comment]
@bulhoes thanks for the info. 
Usually the `mailq` should just be a symlink to the sendmail binary. So its the same binary that would be called
Because we have the `mailq` in the conf.php.example the same has to be used here

**Comment by bulhoes** [comment]
The binary is the same, but as we know sudo doesn't do checksums! ;)
