### ISSUE TITLE
Releasing email NOT as attachments does not work.

### ISSUE THREAD

**Issue by quintingsnj** [mailwatch/MailWatch#935]
### Issue summary

Releasing emails - if I choose SENDMAIL as the method (so as to release the actual message, and not attach it to an email), nothing happens - the email appears in the MW logs, in the web interface, but never actually gets delivered.

### Steps to reproduce

Release an email with settings in conf.php set to use SENDMAIL

### Expected result

Should deliver email intact as it was original

### Actual result

Email appears in MW logs in the web gui, but no email gets delivered.

### Version and method
MailWatch Version: [ stable 1.2.5
Install type: Zip/tarball install
Updated from an older MailWatch or fresh install: Fresh install

###Server configuration
Operation System: CentOS 7
PHP version: 5.4
Database: MySQL version 5.6.37
Mail Server: Sendmail version 8.14.7
Used web server: Apache version 2.4.6
Client configuration

### Client configuration 
 - Operation System: Windows 10
 - Browser: Chrome  60.0.3112.101 and IE 11

**Comment by Skywalker-11** [comment]
Can you check if the sendmail executable is at the location you defined with `SENDMAIL_QUEUE_IN` and `SENDMAIL_QUEUE_OUT` in conf.php and if this command works `sudo -u apache SENDMAIL_QUEUE_IN` (replace SENDMAIL_QUEUE_IN with the value of the conf file)?

**Comment by quintingsnj** [comment]
From my conf.php file:
define('SENDMAIL_QUEUE_IN', '/usr/bin/mailq  -bp -OQueueDirectory=/var/spool/mqueue.in');
define('SENDMAIL_QUEUE_OUT', '/usr/bin/mailq -bp');

Confirmed that this is correct:
[root@mailscanner MailScanner]# whereis sendmail
sendmail: /usr/sbin/sendmail.postfix /usr/sbin/sendmail /usr/sbin/sendmail.sendmail /usr/lib/sendmail.postfix /usr/lib/sendmail.sendmail /usr/lib/sendmail /usr/share/man/man8/sendmail.8.gz


Here are the results of your request: 

[root@mailscanner MailScanner]# sudo -u apache /usr/bin/mailq  -bp -OQueueDirectory=/var/spool/mqueue.in
/var/spool/mqueue.in is empty
                Total requests: 0

**Comment by stefaweb** [comment]
Hello @quintingsnj!

The sendmail syntax should be fine.

Is the size of mqueue.in file changing?
(just to know if used)

**Comment by quintingsnj** [comment]
That is a folder not a file, but yes, files appear in that folder when email is in transit...and then disappears once delivered.

Thanks

**Comment by stefaweb** [comment]
Hello!

Sure, a directory as well.

If you run the command under root: `/usr/bin/mailq -bp -OQueueDirectory=/var/spool/mqueue.in`

Did you get an output?

**Comment by quintingsnj** [comment]
See output below.

[root@mailscanner ~]# /usr/bin/mailq -bp -OQueueDirectory=/var/spool/mqueue.in
/var/spool/mqueue.in is empty
                Total requests: 0

**Comment by stefaweb** [comment]
Seems a problem with sendmail. 

Does `/mailq -bp` works?

**Comment by quintingsnj** [comment]
output below:

[root@mailscanner ~]# mailq -bp
/var/spool/mqueue is empty
                Total requests: 0


Note, the queue is empty right now...it's a new server that's not in production yet.  I can get items to show up in the queue, so I don't believe that it is a problem with Sendmail.  If Sendmail is not commonly used, what is, and do features like queue monitor, and releasing emails intact work with other mail sever solutions (like postfix or exim)?

Thanks

**Comment by asuweb** [comment]
I've had no problem releasing mail when using postfix.

**Comment by quintingsnj** [comment]
OK, maybe it is time to learn a new mail server...lol

**Comment by quintingsnj** [comment]
Quick question.  Does postfix show you your mail queues, or is there someway to see if a message is stuck in the queue in the Mailwatch interface using postfix?

Thanks

**Comment by asuweb** [comment]
Yes, postfix will show you the mail queue from within MW, and yes, there is a way to see if it's stuck. 

If you have a distributed setup / cluster - it'll show the totals for inbound/outbound queue across the cluster, but only the queue of the local machine:
See screenshot

![image](https://user-images.githubusercontent.com/13250955/29929990-092e0bf4-8e65-11e7-8b59-95b7115e30a2.png)

**Comment by quintingsnj** [comment]
Thanks! I will start working on a box with postfix then, and see if I can get things working the way I want :)

Thanks so much for your help and advice.

**Comment by asuweb** [comment]
@quintingsnj - Can this be closed?
