### ISSUE TITLE
PHP Fatal error in database.php

### ISSUE THREAD

**Issue by m3morx** [mailwatch/MailWatch#937]
Hi

Im about to upgrade a running mailwatch 1.2.0 RC2

MailWatch Version:1.2.0 - RC2
MailScanner Version:5.0.3
ClamAV Version:0.99.2 
SpamAssassin Version:3.4.0 
PHP Version:5.4.16
MySQL Version:5.5.50-MariaDB

If i run Upgrade.php withthis DB Version i get a error to upgrade the DB.
If i run the Upgrade with a upgraded version 10.1.26-MariaDB i get this error.

PHP Fatal error:  Class 'mysqli_driver' not found in /var/www/html/mailscanner/database.php on line 48

anny suggestions ?

R memorx

**Comment by stefaweb** [comment]
Hello!

Seems php5 mysql native driver is missing. Install php5-mysqlnd.

**Comment by m3morx** [comment]
great!
worked. but still have this warning.
Table Index: MySQL version unsupported for index `subject_idx` on table `maillog`, upgrade to version >= 50604 (you have version 50505)
In the Issue #637 is endelwar talking about "it's safe to add the fulltext index on maillog.subject" 
how can i perform this ?
nothing else to do on the tables ? ignore this warning ?

**Comment by stefaweb** [comment]
Look at the Issue #920. upgrade.php seems to have problem to manage all differents versions of mysql/mariadb. Report your problem in this issue.

You can close this one.

**Comment by Skywalker-11** [comment]
You can just ignore that. To enable it you would nees to update to MariaDB or MySql 5.6 or higher and then run the upgrade.php

**Comment by Skywalker-11** [comment]
Can be closed
