### ISSUE TITLE
see dangerous content

### ISSUE THREAD

**Issue by ghost235** [mailwatch/MailWatch#938]
Issue summary
Hey,

is there an issue when I set in conf.php
define('DOMAINADMIN_CAN_RELEASE_DANGEROUS_CONTENTS', true);
define('DOMAINADMIN_CAN_SEE_DANGEROUS_CONTENTS', false);

tha the admin can't see dangerous content too?

Steps to reproduce
1.
2.
3.

Expected result

Tell us what should happen

Actual result

Tell us what happens instead

Installation

Version and method
•MailWatch Version: [ stable 1.2.4]
•Install type: [ Zip/tarball install ]
•Updated from an older MailWatch or fresh install: [ Fresh install ]

Server configuration
•Operation System: [ Debian ]
•PHP version: [ 5.6.30-0+deb8u1 ]
•Database: [ MySQL] version [ 5.6.37 ]
•Mail Server: [ Postfix ]
•Used web server: [ Apache ] version [ 2.4.10 ]

Client configuration
•Operation System: [ operation system ] version [ version ]
•Browser: [ browser name and version ]

**Comment by Skywalker-11** [comment]
@ghost235 In general only mail parts that are of the mime type `message/rfc822` can be viewed inside the MailWatch gui. The settings you mentioned only apply to domain admins. Global admins can always view `message/rfc822` parts and release them. So its the expected behaviour

**Comment by Skywalker-11** [comment]
Can this be closed?

**Comment by ghost235** [comment]
Yes. But one more question.
'DOMAINADMIN_CAN_RELEASE_DANGEROUS_CONTENTS' affected the release checkboxes
but wat do 'DOMAINADMIN_CAN_SEE_DANGEROUS_CONTENTS' I can't see any difference between true/false

**Comment by ghost235** [comment]
ok got it .... ;)
