### ISSUE TITLE
Absolute paths to logo files do not resolve without dns record

### ISSUE THREAD

**Issue by shawniverson** [mailwatch/MailWatch#943]
### Steps to reproduce
1.  Install MailWatch 1.2.5 
2.  Do not configure upstream dns for MailWatch

### Expected result
Logos should render regardless of presence of dns record.

### Actual result
Logos fail to load, this is a result of the addition of MAILWATCH_HOSTURL in commit d0d9595440d3c34e32878451eace6f646e02a82d.  This should be a relative path instead of an absolute path, as not all installations may have an upstream dns record (such as test environments or special use cases of MailWatch).

### Version and method
 - MailWatch Version: [ stable 1.2.5 master ]
 - Install type: [ GitHub checkout ]
 - Updated from an older MailWatch or fresh install: [ Fresh install ])

### Server configuration
 - Operation System: [ CentOS ] version [ 6.9 ]
 - PHP version: [ 5.3 ]
 - Database: [  MariaDB ] version [ 10x ]
 - Mail Server: [ Postfix  ]
 - Used web server: [ Apache ] version [ 2.4 ]

**Comment by asuweb** [comment]
There was a reason I / We added MAILWATCH_HOSTURL but I can't remember off the top of my head why.  I'll have to trawl through the thread for that PR as it was talked about in there if memory serves.

**Comment by shawniverson** [comment]
@asuweb It was for the quarantine reports, I believe.

**Comment by asuweb** [comment]
Yes, that rings a bell.  I seem to remember a case where for quarantine reports relative url's were causing issue with the logo not loading, hence this change.  Can't recall specifically why the relative urls weren't working though.

**Comment by shawniverson** [comment]
@asuweb I think that commit d0d9595440d3c34e32878451eace6f646e02a82d was intended for consistency, but I'm not sure that makes sense for the login and mailwatch pages.

**Comment by asuweb** [comment]
@shawniverson - I agree, should be relative paths for those ones - only need the absolute paths for the emails
