### ISSUE TITLE
Software Version - No translation in English

### ISSUE THREAD

**Issue by imilanovic** [mailwatch/MailWatch#949]
#Hi,

I found this line in sf_version.php

`html_start(__('mwandmsversion52'), 0, false, false);`

In translations there is no mwandmsversion52 value so in title for Software Version shows "No translation in English"

**Comment by stefaweb** [comment]
Hello!

Should be `mwandmsversion11`.

**Comment by stefaweb** [comment]
PR #950.

Found another problem too.
