### ISSUE TITLE
Queues Are Always Empty

### ISSUE THREAD

**Issue by quintingsnj** [mailwatch/MailWatch#951]
### Issue summary
The queue status shows x emails in the queue, but when clicking on them, the queues are empty.  Running mailq on the console brings up a list of queued emails.

### Steps to reproduce
1.  See queue number on status page
2.  Click on the queue
3.  Queue is empty, and now shows 0 emails in queue
4. Go back to status page, queue still shows x emails in queue.

### Expected result
The queue should display a list of emails in the mail queue when you click on inbound or outbound respectively.

### Actual result
The queue shows as empty, even when it is not.

### Version and method
 - MailWatch Version: [ stable 1.2.6 ]
 - Install type: [ Zip/tarball install ]
 - Updated from an older MailWatch or fresh install: [ Fresh install ]

### Server configuration
 - Operation System: [ CentOS ] version [ 7 ]
 - PHP version: [ 5.4 ]
 - Database: [ MySQL ] version [ 5.6 ]
 - Mail Server: [ Postfix ]
 - Used web server: [ Apache ] version [ 2.4.6 ]

### Client configuration 
 - Operation System: [ Windows ] version [ 10 ]
 - Browser: [ Chrome ]

**Comment by Skywalker-11** [comment]
Can you try stopping MailScanner, then send a mail and see if it still isn't shown? Maybe MailScanner is just too fast 😄

**Comment by quintingsnj** [comment]
No, that's not it, as I have an outgoing message stuck in the queue retrying to a dead domain :)

That was my first thought too :)

**Comment by Skywalker-11** [comment]
Anything in the web server log?
What are the permissions of `/var/spool/postfix/`?

**Comment by quintingsnj** [comment]
drwxr-xr-x. 17 root root 215 Sep  5 12:09 /var/spool/postfix/

Nothing in the httpd error logs.

**Comment by quintingsnj** [comment]
Permissions on the contents of /var/spool/postfix/

drwx------.  2 postfix root        6 Sep  7 09:58 active
drwx------.  2 postfix root        6 Sep  7 09:50 bounce
drwx------.  2 postfix root        6 Jun  9  2014 corrupt
drwx------. 10 postfix root       78 Sep  6 16:36 defer
drwx------. 10 postfix root       78 Sep  6 16:36 deferred
drwx------.  2 postfix root       20 Aug 31 11:27 flush
drwxr-x---.  2 postfix apache      6 Sep  7 09:58 hold
drwxr-x---.  2 postfix apache      6 Sep  7 09:58 incoming
drwx-wx---.  2 postfix postdrop    6 Sep  7 09:01 maildrop
drwxr-xr-x.  2 root    root      205 Sep  5 15:12 pid
drwx------.  2 postfix root      256 Sep  5 15:12 private
drwx--x---.  2 postfix postdrop   73 Sep  5 15:12 public
drwxr-xr-x.  2 postfix postfix  4.0K Sep  5 12:12 .razor
drwx------.  2 postfix root        6 Jun  9  2014 saved
drwx------.  2 postfix root        6 Jun  9  2014 trace

**Comment by quintingsnj** [comment]
OK, that is strange. I tried copying the postfixmailq.php from 1.2.5 to my new 1.2.6 install, and it showed 1.2.5 as the version, but same result. I then copied the 1.2.6 one back, and it still showed 1.2.5 as the version, but then I refreshed it, and it showed 1.2.6 AND the queue showed up....

I really haven't changed anything...very strange.

**Comment by Skywalker-11** [comment]
It maybe is a caching problem. When reloading the queue page have you try to force invalidating the cache (STRG+F5) or did you just navigated to the page or used F5?

**Comment by quintingsnj** [comment]
I don't know, but it has worked as expected since my last post to this issue.  I think we can close it, and call it a mystery.  :)
