### ISSUE TITLE
ldap login not workin

### ISSUE THREAD

**Issue by m3morx** [mailwatch/MailWatch#955]
Hi,
It worked in erlier version of Mailwatch.
Im not able to autenticate with ldap users.

my config:
// LDAP settings for authentication
define('USE_LDAP', true);
define('LDAP_SSL', false); // Set to true if using LDAP with SSL encryption.
define('LDAP_HOST', '10.1.30.50');
define('LDAP_PORT', '389');
define('LDAP_DN', 'DC=lab,DC=local');
define('LDAP_USER', 'CN=Administrator,CN=Users,DC=lab,DC=local');
define('LDAP_PASS', 'Secret.1');
define('LDAP_FILTER', 'mail=%s'); //%s will be replaced by username eg. 'mail=%', 'mail=SMTP:%s', 'sAMAccountName=%s'
define('LDAP_PROTOCOL_VERSION', 3);
// can be set to 'proxyaddresses' or 'mail'. Please refer to your LDAP system manual for the right keyword
define('LDAP_EMAIL_FIELD', 'mail');
// Ldap field that is used to bind to the ldap server to check the credentials.
// The value of the LDAP_USERNAME_FIELD will be extended by LDAP_BIND_PREFIX and LDAP_BIND_SUFFIX to created the binding username.
define('LDAP_USERNAME_FIELD', 'sAMAccountName');
// define('LDAP_BIND_PREFIX', 'cn=');
// define('LDAP_BIND_SUFFIX', ',' . LDAP_DN);
// Microsoft Active Directory compatibility support for searches from Domain Base DN
define('LDAP_MS_AD_COMPATIBILITY', true);

httpd/error_log no errors logged
local authentication works
php-ldap installed

MailWatch Version: 1.2.6
Operating System Version: CentOS Linux 7 (Core)
Postfix Version: 3.2.2 
MailScanner Version: 5.0.6
ClamAV Version: 0.99.2 
SpamAssassin Version: 3.4.0 
PHP Version: 5.4.16
MySQL Version: 10.1.26-MariaDB

any suggestions ?

**Comment by Skywalker-11** [comment]
@m3morx Can you try using `define('LDAP_USERNAME_FIELD', 'userprincipalname');`

**Comment by m3morx** [comment]
excellent!
Why does it not work with sAMAccountName ? Same content as cn !

**Comment by Skywalker-11** [comment]
The username that will effective be used to bind to the ldap server (for checking the user credentials) is `LDAP_BIND_PREFIX.LDAP_USERNAME_FIELD.LDAP_BIND_SUFFIX`. 
When using the userprincipalname you use the account name in format `sAMAccountName@EXAMPLE.COM`.

You can also use `define('LDAP_USERNAME_FIELD', 'sAMAccountName');` but you need to specify `LDAP_BIND_SUFFIX` to be like `@EXAMPLE.COM`. So that the binding username is correct.

**Comment by Skywalker-11** [comment]
Actually you shouldn't need the LDAP_BIND_SUFFIX but can use `define('LDAP_USERNAME_FIELD', 'samaccountname');` with `define('LDAP_FILTER', 'samaccountname=%s');`. But there is a bug that prevents this. I'm preparing a patch right now.

**Comment by Skywalker-11** [comment]
@m3morx problem is fixed in the current develop version

**Comment by Skywalker-11** [comment]
@m3morx can you test if the code in current develop branch fixes this?

**Comment by m3morx** [comment]
I'll test it, not sure if i find some time until the end of the week. I'll comback asap

**Comment by m3morx** [comment]
tried it with the modified code from checklogin.php but samaccountname don't work either

**Comment by Skywalker-11** [comment]
Can you try running the following command to see if the ldap query is working:
`ldapsearch -D LDAP_USER -W -b LDAP_DN -H LDAP_HOST:LDAP_PORT "LDAP_FILTER"

Replace LDAP_USRE, LDAP_DN, LDAP_HOST, LDAP_PORT, LDAP_FILTER with the values from the MailWatch conf.php. 

For LDAP_FILTER also replace the `%s` with an existing login name from your ldap server. Eg.:

ldapsearch -D cn=ldap,ou=users,dc=example,dc=org -W -b dc=example,dc=org-H ldap://ldap1.example.org:389 "samaccountname=m3morx"

It should ask for the password for the ldap user (not the m3morx user here) and then output the ldap entry for m3morx  and at the end something like:
```
# search result
search: 3
result: 0 Success

# numResponses: 6
# numEntries: 1
# numReferences: 4
```

Also make sure that the value of the field defined by LDAP_USERNAME_FIELD in your conf.php matches the login name. Eg if you have `define('LDAP_USERNAME_FIELD', 'userprincipalname');` then there should be something like `userPrincipalName: m3morx@example.org` in the result of the command above which matches the login for the AD for that user.

**Comment by m3morx** [comment]
this is the output

# search result
search: 2
result: 0 Success

# numResponses: 5
# numEntries: 1
# numReferences: 3

lab.tld = maildomain
lab.local = MS AD Domain internal

something interesting:
I'm using a testuser01 as username to check. 
if define('LDAP_USERNAME_FIELD', 'cn');
im able to login with my exchange domain. i.e. testuser01@lab.tld
cn field in AD is "Testuser 01"
if define('LDAP_USERNAME_FIELD', 'samaccountname');
the exampel above does not work! despite the AD sammaccountname file is "testuser01".
in both cases, if the domain is left off, not possible to sing in!

**Comment by Skywalker-11** [comment]
You should use ` define('LDAP_USERNAME_FIELD', 'userprincipalname');` as the `userprincipalname` should contain the login name the user can use to login on AD server/computers. 
This is how ldap MailWatch login basically works:
1. search LDAP/AD with the filter of LDAP_FILTER using the credentials of the conf.php
2. get the field of LDAP_USERNAME_FIELD from the result and use that with the entered password to bind to the ldap user
2a) if the bind was successful get the mail address (LDAP_EMAIL_FIELD) and stores that as MailWatch username
2b) if the bind fails that means the user can't be authenticated on AD with the username

This settings should work for you:
```
define('LDAP_FILTER',      'samaccountname=%s'); 
define('LDAP_USERNAME_FIELD', 'userprincipalname');
define('LDAP_EMAIL_FIELD', 'mail'); //or maybe proxyaddresses. depending on your mail setup
define('LDAP_DN', 'DC=lab,DC=local');
define('LDAP_PORT', '389');
define('LDAP_HOST', 'LABDC01.lab.local');
define('LDAP_USER', 'CN=Testuser 01,OU=LAB_Users,DC=lab,DC=local');
define('LDAP_MS_AD_COMPATIBILITY', true);
//not define LDAP_BIND_PREFIX or LDAP_BIND_SUFFIX
```

**Comment by Skywalker-11** [comment]
If that still doesn't work find this line in functions.php `$bindResult = @ldap_bind($ds, $user, $password);` and add `error_log($user);` in front of that. This should write the username with which MW tries to login the user to AD to the webserver log so you can validate that you can login with it on a normal AD computer.

**Comment by endelwar** [comment]
@m3morx any news on this issue?
