### ISSUE TITLE
Domain-Admin cannot change password

### ISSUE THREAD

**Issue by tomwmt** [mailwatch/MailWatch#956]
### Steps to reproduce
1.  create user with type Domain Administrator
2.  login as this user
3.  try to change the password

### Expected result
The user should be able to change his password.

### Actual result
Error: You don't have the permissions to create/edit/delete admin

### Version and method
 - MailWatch Version: 1.2.6
 - Install type: ZIP
 - Updated from an older MailWatch or fresh install: upgrade from 1.2.5

**Comment by Skywalker-11** [comment]
@tomwmt this should be fixed by #957 in current develop branch. Can you validate this and then close this ticket?

**Comment by tomwmt** [comment]
Ok works now!
