### ISSUE TITLE
Error with mailwatch_sendmail_queue.php

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#959]
Hello!

With develop version (and 1.2.6 too).

Sometimes, I got this error message:

`Notice: Unknown: Invalid quoted-printable sequence: =  fi junior (errflg=3) in Unknown on line 0
`

`fi junior` seems part of message title.

If someone have an idea?

**Comment by Skywalker-11** [comment]
Duplicate #702 (your ticket 😄)

**Comment by stefaweb** [comment]
Oops. I had completely forgotten that.

And the manual path done in my prod server was cleared when I updated to 1.2.6. I never received a wrong message.

I remember only of this below but I've forgotten how to implement this in the code and where.

```
function errorHandler($errno, $errstr, $errfile, $errline)
{
  global $messageid;
  error_log("Error in mailwatch_sendmail_queue at message " . $messageid . ":[" . $errno . "]" . $errstr);
  return true;
}
set_error_handler("errorHandler");

```

**Comment by Skywalker-11** [comment]
See here https://github.com/mailwatch/MailWatch/issues/702#issuecomment-315205227
Someone else also referenced that old issue in the SSilence repo with an example mail attached that causes the problem. That might help to figure out whats wrong.

**Comment by stefaweb** [comment]
Ok, great. Thanks. I added the function.

Need to wait now.  😀

**Comment by Skywalker-11** [comment]
@stefaweb did you see the error again?

**Comment by Skywalker-11** [comment]
Any news about this or can we close?

**Comment by Skywalker-11** [comment]
Closing for now
