### ISSUE TITLE
XML-RPC Error: Didn't receive 200 OK from remote server. (HTTP/1.1 404 Not Found)

### ISSUE THREAD

**Issue by quintingsnj** [mailwatch/MailWatch#960]
### Issue summary
When clicking on email details, I get this at the bottom of the page, instead of options to release, learn, etc: XML-RPC Error: Didn't receive 200 OK from remote server. (HTTP/1.1 404 Not Found).  This also shows up when learning in bulk from the operations page.

### Steps to reproduce
1. Click on message details

### Expected result
Should display the  link to the email, and options to learn as ham or spam and release.

### Actual result
Generates error:  XML-RPC Error: Didn't receive 200 OK from remote server. (HTTP/1.1 404 Not Found)

### Version and method
 - MailWatch Version: [ stable 1.2.6 ]
 - Install type: [ Zip/tarball install ]
 - Updated from an older MailWatch or fresh install: [ Fresh install ]

### Server configuration
 - Operation System: [ CentOS ] [ 7 ]
 - PHP version: [ 5.4 ]
 - Database: [ MySQL ] version [ 5.6 ]
 - Mail Server: [ Postfix ]
 - Used web server: [ Apache ] version [ 2.4 ]

### Client configuration 
 - Operation System: [ Windows ] version [ 10 ]
 - Browser: [ Chrome 60.0.3112.113 ]

**Comment by quintingsnj** [comment]
It is not all emails, but in a report I did for yesterday's email to flesh out false positives, several generated that error. Was able to go to the queue/quarantine folders on the server, and find the message in question.  It is there, and rights are correct.  I could read the email from there to determine if it was spam or not, so I got around it, and fortunately didn't have to release any of them...

In any case, I'll monitor for the next while, and see if it still occurs, or was a one time thing.

**Comment by Skywalker-11** [comment]
Can you provide a example link that doesn't work and a link that does work?

**Comment by quintingsnj** [comment]
Here are 2 screenshots.

![working](https://user-images.githubusercontent.com/31482430/30598611-d16f68ce-9d1f-11e7-8533-3ecc6576c8d6.png)
![notworking](https://user-images.githubusercontent.com/31482430/30598610-d113ba1a-9d1f-11e7-84e5-128eae15320e.png)

**Comment by Skywalker-11** [comment]
@quintingsnj were the mails received by different servers?

**Comment by quintingsnj** [comment]
No, only have 1 mailscanner server, and 1 exchange server.

**Comment by shawniverson** [comment]
@quintingsnj Wait, 1 mailscanner server?  Why is XML-RPC mode even enabled?

**Comment by Skywalker-11** [comment]
Problem would be here:     
`if (!$rpc_only && is_local($row->hostname)) {` ([functions.php#L3353](https://github.com/mailwatch/MailWatch/blob/master/mailscanner/functions.php#L3353))

Which means that @quintingsnj either has `define(RPC_ONLY, true);` in conf.php or the hostname does not resolve to localhost

@quintingsnj is it possible that you changed the hostname of the server? If not can you try to execute the following mysql query: 
` select hostname from maillog limit 1 where id="1E5BA4076146.A6A0D";` 
And then create a file called test.php with the following content:
```
<?php
echo strtolower(rtrim(gethostname()));
echo gethostbyaddr('127.0.0.1');
?>
```
Execute it with `php test.php`
The sql result should match one of the outputs from the php script. If that's not the case check your /etc/hosts and/or /etc/hostname files that the hostname from sql matches them

**Comment by quintingsnj** [comment]
I never enabled it…so what do I do to disable it?

**Comment by quintingsnj** [comment]
Weird, it is doubling up my domainname…adding my domainname twice to my hostname.

e.g. hostname.domain.name.domain.name

I wonder what I did to cause that?

Define(RPC_ONLY, false); (from my config.php)

Thanks.

**Comment by quintingsnj** [comment]
OK, got my hostname fixed…sort of…on the centOS command line, it shows the proper domain name now (it didn’t before).

In the php script, it shows the proper domain name, and then at the end with no period or space, localhost

Any idea why it would at that? It was doing that before I changed the hostname, I just hadn’t noticed it (so before it was printing this: hostname.domain.name.domain.namelocalhost, now it is showing this: hostname.domain.namelocalhost).

Thanks for your help with this.

Q

**Comment by quintingsnj** [comment]
Well, the double domain names have stopped in mailwatch, and that error is gone now (it was intermittent before, so I’ll keep my eye on it).

Thanks.

Q

**Comment by Skywalker-11** [comment]
@quintingsnj is it fixed? If it is can you close the issue?

**Comment by quintingsnj** [comment]
Yes, good to close.

Thanks
