### ISSUE TITLE
Permissions on Bayes keeps reverting

### ISSUE THREAD

**Issue by quintingsnj** [mailwatch/MailWatch#962]
### Issue summary
Permissions on bayes database file always reverts to postfix:postfix

### Steps to reproduce
1. Change permissions on /etc/MailScanner/bayes/bayes* to postfix:apache
2. Eventually permissions revert to postfix:postfix

### Expected result
Permissions should stay at postfix:apache

### Actual result
Permissions reverted to postfix:postfix

### Version and method
 - MailWatch Version: [ stable 1.2.6 ]
 - Install type: [ Zip/tarball install ]
 - Updated from an older MailWatch or fresh install: [ Upgrade ] (from version [ 1.2.5 ])

### Server configuration
 - Operation System: [ CentOS ] version [ 7 ]
 - PHP version: [ 5.4 ]
 - Database: [ MySQL ] version [ 5.6 ]
 - Mail Server: [ Postfix ]
 - Used web server: [ Apache ] version [ 2.4 ]

### Client configuration (N/A in this case)
 - Operation System: [ Windows ] version [ 10 ]
 - Browser: [ Chrome ]

**Comment by Skywalker-11** [comment]
Do you have the following in your MailScanner.conf or config file in the conf.d directory?
```
Run As User = postfix
Run As Group = apache
```

**Comment by quintingsnj** [comment]
That was probably it.  Both were set to postfix.

Thanks.
