### ISSUE TITLE
& in Email Address (Username and Name in MailWatch)

### ISSUE THREAD

**Issue by achandlerwchg** [mailwatch/MailWatch#964]
Currently running MailWatch for MailScanner v1.2.1-dev running on EFA-3.0.1.9.  Not the latest version but the change logs don't mention this being fixed.

We have an email address containing the an "&".  

This "user" cannot be changed within MailWatch User Management as both the Username and Name appear blank, I am assuming as the & is an escape symbol.

If I create a new user, then when saving with a username or name containing the &, I get an error saying the fields cannot be blanked, as the save process empties the field.

I had a similar issue with the ldap sync containing an ' apostrophe, the sync failed and we had to make alterations to rewrite this, although this is referenced in a changelog already.

**Comment by shawniverson** [comment]
In the RFCs, & is a permitted character in email , so this should be added to the field validations for users.  If time permits, I will get a PR ready.

**Comment by stefaweb** [comment]
Hello!

Seems the last PR do not work with Mariadb 10.1.28 (Debian) when we run upgrade.php.

```
 - Add id field in `users` table...................................... ERROR
Database error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FIRST;
            )' at line 2 - SQL = 'ALTER TABLE `users` ADD COLUMN (
            `id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE KEY FIRST;
            );'

```
