### ISSUE TITLE
PHP Warning:  preg_match(): Empty regular expression in /var/www/html/mailscanner/functions.php on line 4773

### ISSUE THREAD

**Issue by IKatsu** [mailwatch/MailWatch#968]
### Issue summary
I just set up a fresh MS/MW setup that includes a (atm non working) f-prot AV.
I noticed my apache error_log was filling up with:
PHP Warning:  preg_match(): Empty regular express
ion in /var/www/html/mailscanner/functions.php on line 4773, referer: <few different php pages>
Line 4773 is the virus scanner regex, I noticed that at line 197 it says case 'f-protd-6'
The old f-prot script was called 'f-prot-6'.
It's no longer included but I copied it from an older installation. Removed the d from the functions.php and the error went away.

### Version and method
 - MailWatch Version: stable 1.2.6
 - Install type: Zip/tarball install 
 - Updated from an older MailWatch or fresh install: Fresh install / Upgrade
The DB from a 1.2.0 - RC1 DEV install was copied and upgraded with upgrade.php
old software tree has not been present on this server.

### Server configuration
 - Operation System: CentOS  version 7
 - PHP version: 5.4
 - Database: MariaDB version 10.2
 - Mail Server: Postfix
 - Used web server: Apache version 2.4.6

**Comment by Skywalker-11** [comment]
Both `f-protd-6` and `f-prot-6` are valid virus scanners in mailscanner: https://github.com/MailScanner/v5/blob/master/config.index/conf_array.php#L3421-L3422.

Can you provide the script?

Not sure but maybe we also need to adjust the file name in https://github.com/mailwatch/MailWatch/blob/master/mailscanner/f-prot_status.php#L43 (the if currently doesn't make sense)

**Comment by IKatsu** [comment]
```
#!/bin/sh

# f-prot-6-wrapper --   invoke F-Prot version 6 AV for use with
#                       mailscanner
#
# JKF, 29/08/2007
#
#   MailScanner - SMTP E-Mail Virus Scanner
#   Copyright (C) 2001  Julian Field
#
#   $Id: f-prot-6-wrapper 1805 2003-08-09 11:04:02Z jkf $
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#   The author, Julian Field, can be contacted by email at
#      Jules@JulianField.net
#   or by paper mail at
#      Julian Field
#      Dept of Electronics & Computer Science
#      University of Southampton
#      Southampton
#      SO17 1BJ
#      United Kingdom
#
#


# You may want to check this script for bash-isms

PackageDir=$1           # This may vary depending on your OS
shift
Scanner=fpscan

if [ "x$PackageDir" = "x" ]; then
  # No command-line arg, so set default at /opt/f-prot
  PackageDir="/opt/f-prot"
fi

ScanOptions=""

if [ "x$1" = "x-IsItInstalled" ]; then
  [ -x ${PackageDir}/$Scanner ] && exit 0
  exit 1
fi

exec ${PackageDir}/$Scanner $ScanOptions "$@"
```

It might be mentioned in the config file but the scripts are no longer there by default.
This is what I have after a fresh install (with the f-prot ones being manually placed there)

>  -rwxr-xr-x 1 root root  1181 Sep 30 04:42 avast-wrapper
> -rwxr-xr-x 1 root root  1357 Sep 30 04:42 avg-autoupdate
> -rwxr-xr-x 1 root root  1219 Sep 30 04:42 avg-wrapper
> -rwxr-xr-x 1 root root 22718 Sep 30 04:42 bitdefender-autoupdate
> -rwxr-xr-x 1 root root  1667 Sep 30 04:42 bitdefender-wrapper
> -rwxr-xr-x 1 root root  2169 Sep 30 04:42 clamav-autoupdate
> -rwxr-xr-x 1 root root  5949 Oct 25 16:46 clamav-wrapper
> -rwxr-xr-x 1 root root  1187 Sep 30 04:42 esets-wrapper
> -rwxr-xr-x 1 root root  4204 Oct 24 15:35 f-prot-6-autoupdate
> -rwxr-xr-x 1 root root  1685 Oct 24 15:35 f-prot-6-wrapper
> -rwxr-xr-x 1 root root  1094 Sep 30 04:42 f-secure-autoupdate
> -rwxr-xr-x 1 root root  2983 Sep 30 04:42 f-secure-wrapper
> -rwxr-xr-x 1 root root  1020 Sep 30 04:42 generic-autoupdate
> -rwxr-xr-x 1 root root  2173 Sep 30 04:42 generic-wrapper
> -rwxr-xr-x 1 root root  5322 Sep 30 04:42 sophos-autoupdate
> -rwxr-xr-x 1 root root  1669 Sep 30 04:42 sophos-wrapper

**Comment by Skywalker-11** [comment]
PullRequest #969 will enable f-prot-6 scanner for mailwatch

Please open a seperate issue on the MailScanner git for inclusion of the wrapper script as they are coming from MailScanner:
https://github.com/MailScanner/v5/issues

**Comment by IKatsu** [comment]
First I need to get MS to actually work with f-prot which is what I haven't had time to figure out why it isn't yet.
At least this one is solved :-)
