### ISSUE TITLE
mailwatch shows no clamav status

### ISSUE THREAD

**Issue by philrandal** [mailwatch/MailWatch#970]
### Issue summary
Mailwatch doesn't report ClamAV status

### Steps to reproduce
1.  as an administrator, visit clamav_status.php
2. 
3. 

### Expected result
ClamAV version and database version should be reported

### Actual result
Blank output

### Version and method
 - MailWatch Version: develop
 - Install type: Installer (beta)
 - Updated from an older MailWatch or fresh install: Upgrade (from version 1.2.6)

### Server configuration
 - Operation System: CentOS version 7.4
 - PHP version:  5.4 
 - Database: MariaDB 
 - Mail Server: Postfix
 - Used web server: Apache

Running 

# /usr/lib/MailScanner/wrapper/clamav-wrapper  -V
/opt/mailwatch/public/auto-release.php: OK
/opt/mailwatch/public/bayes_info.php: OK
/opt/mailwatch/public/checklogin.php: OK
/opt/mailwatch/public/clamav.awk: OK
/opt/mailwatch/public/clamav_status.php: OK
/opt/mailwatch/public/conf.php.example: OK
/opt/mailwatch/public/database.php: OK
/opt/mailwatch/public/detail.php: OK
/opt/mailwatch/public/docs.php: OK
/opt/mailwatch/public/do_message_ops.php: OK
/opt/mailwatch/public/favicon.ico: OK
/opt/mailwatch/public/filter.inc.php: OK
/opt/mailwatch/public/f-prot.awk: OK
/opt/mailwatch/public/f-prot_status.php: OK
/opt/mailwatch/public/f-secure.awk: OK
/opt/mailwatch/public/f-secure_status.php: OK
/opt/mailwatch/public/functions.php: OK
/opt/mailwatch/public/geoip_update.php: OK
/opt/mailwatch/public/graphgenerator.inc.php: OK
/opt/mailwatch/public/index.php: OK
/opt/mailwatch/public/lists.php: OK
/opt/mailwatch/public/login.function.php: OK
/opt/mailwatch/public/login.php: OK
/opt/mailwatch/public/logout.php: OK
/opt/mailwatch/public/mailq.php: OK
/opt/mailwatch/public/mcafee.awk: OK
/opt/mailwatch/public/mcafee_status.php: OK
/opt/mailwatch/public/mcp_rules_update.php: OK
/opt/mailwatch/public/msconfig.php: OK
/opt/mailwatch/public/ms_lint.php: OK
/opt/mailwatch/public/msre_edit.php: OK
/opt/mailwatch/public/msre_index.php: OK
/opt/mailwatch/public/msre_table_functions.php: OK
/opt/mailwatch/public/msrule.php: OK
/opt/mailwatch/public/mtalogprocessor.inc.php: OK
/opt/mailwatch/public/mysql_status.php: OK
/opt/mailwatch/public/other.php: OK
/opt/mailwatch/public/password_reset.php: OK
/opt/mailwatch/public/postfix.inc.php: OK
/opt/mailwatch/public/postfixmailq.php: OK
/opt/mailwatch/public/quarantine_action.php: OK
/opt/mailwatch/public/quarantine.php: OK
/opt/mailwatch/public/quarantine_report.inc.php: OK
/opt/mailwatch/public/rep_audit_log.php: OK
/opt/mailwatch/public/rep_mcp_rule_hits.php: OK
/opt/mailwatch/public/rep_mcp_score_dist.php: OK
/opt/mailwatch/public/rep_message_listing.php: OK
/opt/mailwatch/public/rep_message_ops.php: OK
/opt/mailwatch/public/reports.php: OK
/opt/mailwatch/public/rep_previous_day.php: OK
/opt/mailwatch/public/rep_sa_rule_hits.php: OK
/opt/mailwatch/public/rep_sa_score_dist.php: OK
/opt/mailwatch/public/rep_top_mail_relays.php: OK
/opt/mailwatch/public/rep_top_recipient_domains_by_quantity.php: OK
/opt/mailwatch/public/rep_top_recipient_domains_by_volume.php: OK
/opt/mailwatch/public/rep_top_recipients_by_quantity.php: OK
/opt/mailwatch/public/rep_top_recipients_by_volume.php: OK
/opt/mailwatch/public/rep_top_sender_domains_by_quantity.php: OK
/opt/mailwatch/public/rep_top_sender_domains_by_volume.php: OK
/opt/mailwatch/public/rep_top_senders_by_quantity.php: OK
/opt/mailwatch/public/rep_top_senders_by_volume.php: OK
/opt/mailwatch/public/rep_top_viruses.php: OK
/opt/mailwatch/public/rep_total_mail_by_date.php: OK
/opt/mailwatch/public/rep_viruses.php: OK
/opt/mailwatch/public/robots.txt: OK
/opt/mailwatch/public/rpcserver.php: OK
/opt/mailwatch/public/sa_lint.php: OK
/opt/mailwatch/public/sa_rules_update.php: OK
/opt/mailwatch/public/sf_version.php: OK
/opt/mailwatch/public/sophos.awk: OK
/opt/mailwatch/public/sophos_status.php: OK
/opt/mailwatch/public/status.php: OK
/opt/mailwatch/public/style.css: OK
/opt/mailwatch/public/syslog_parser.inc.php: OK
/opt/mailwatch/public/user_manager.php: OK
/opt/mailwatch/public/viewmail.php: OK
/opt/mailwatch/public/viewpart.php: OK
/opt/mailwatch/public/conf.php: OK

----------- SCAN SUMMARY -----------
Known viruses: 6333382
Engine version: 0.99.2
Scanned directories: 1
Scanned files: 78
Infected files: 0
Data scanned: 1.02 MB
Data read: 0.47 MB (ratio 2.17:1)
Time: 16.927 sec (0 m 16 s)

whereas

# /usr/lib/MailScanner/wrapper/clamav-wrapper . -V
ClamAV 0.99.2/24020/Mon Nov  6 21:05:54 2017

does the right thing.

Fix is to change the passthru line in clamav_status.php from

    passthru(get_virus_conf('clamav') . ' -V | awk -f ' . __DIR__. '/clamav.awk');

to

    passthru(get_virus_conf('clamav') . ' . -V | awk -f ' . __DIR__. '/clamav.awk');

This is the proper fix for the clamav part of Issue #921

**Comment by philrandal** [comment]
Whilst the problem lies in MailScanner's clamav-wrapper not handling the corner case of being passed -V without a directory to scan being specified, my proposed fix breaks nothing and works even if MailScanner's clamav-wrapper did the right thing.

**Comment by pztop** [comment]
I am having the same issue here. I changed the passthru line but still no luck. 

philrandal, I noticed that your line has 2 differences with the original line:
1. add a dot in front of -V
2. The __DIR__ in original line has space both in front and behind, your new line seems onle have the front space.

I am not a programmer so I couldn't fig it out. I just copy-paste your line to the file and commented out the old line but it still won't show status.

**Comment by philrandal** [comment]
You need to add dot space in front of the - V

**Comment by pztop** [comment]
Pulling my hair out!
I tried this and still no luck:
```
//  passthru(get_virus_conf('clamav') . ' -V | awk -f ' . __DIR__ . '/clamav.awk');
    passthru(get_virus_conf('clamav') . ' . -V | awk -f ' . __DIR__ . '/clamav.awk');
```

My `clamav-wrapper -V` output correctly. I am using Nginx+PHP7.1, is that make any difference?

Here is my system info:
MailWatch Version: 1.2.6
Operating System Version: CentOS Linux 7 (Core)
Postfix Version: 3.2.4 
MailScanner Version: 5.0.6
ClamAV Version: 
SpamAssassin Version: 3.4.0 
PHP Version: 7.1.11
MySQL Version: 5.5.56-MariaDB
GeoIP Database Version: Tue, 07 Nov 2017 14:45:13 -0800 (download date)
GeoIPv6 Database Version: Tue, 07 Nov 2017 14:45:13 -0800 (download date)

**Comment by Skywalker-11** [comment]
Can you try running `sudo -u apache /usr/lib/MailScanner/wrapper/clamav-wrapper  .  /usr -V`
Maybe its a permission problem for the clamav temp directory.

**Comment by pztop** [comment]
Hi Skywalker-11,

I think you are right on the permission issue. Here is my test result:
```
[root@mail ~]# sudo -u nginx /usr/lib/MailScanner/wrapper/clamav-wrapper . /usr -V
mktemp: failed to create directory via template ‘/tmp/clamav-tmp/tmp.XXXXXXXXXX’: Permission denied
ERROR: Option --tempdir requires a non-empty string argument
ERROR: Can't parse command line options

[root@mail ~]# sudo  /usr/lib/MailScanner/wrapper/clamav-wrapper . /usr -V
ClamAV 0.99.2/24028/Thu Nov  9 05:09:21 2017

[root@mail ~]# ps aux | grep clamd
clamscan   899  0.0 13.8 1002932 538280 ?      Ssl  Nov08   0:58 /usr/sbin/clamd -c /etc/clamd.d/scan.conf --foreground=yes

[root@mail ~]# ll /tmp
drwx------  2 postfix postfix     6 Nov  9 08:48 clamav-tmp    10468  0.0  0.0 112664   972 pts/0    S+   
```
Now I am confused: The /tmp/clamav-tmp directory is created and owned by user "postfix", but my clamd is running by user "clamscan". So who created this folder? postfix or MailScanner? Where can I adjust its permission so it can let user "nginx" to have correct permission?

**Comment by pztop** [comment]
Read [here ](http://lists.mailscanner.info/pipermail/mailscanner/2016-October/103911.html) I see it's MailScanner created that clamav-tmp folder. But I am running a VM so during the installation of  MailScanner I selected not to use RAM disk.

**Comment by Skywalker-11** [comment]
you should be able to solve it by running `chmod g+rwx /tmp/clamav-tmp/`

**Comment by pztop** [comment]
Change the group permission when the group is "postfix" won't work. However, I just delete this `/tmp/clamav-temp` folder since it's a temporary directory anyway, then I reboot the sever. I wait for a while and this  `/tmp/clamav-temp` directory never got created again! And MailWatch can show the clamav version info now. I tried to send some virus emails (through http://www.emailsecuritycheck.net) to let the clamd works but still there is no more  `/tmp/clamav-temp` directory. Anyway this seems self healed and I have no what is going on here.

**Comment by philrandal** [comment]
I'd appreciate it if my pull request which fixes the issue as I reported it was merged

**Comment by philrandal** [comment]
I just rebuilt my test box from scratch, using Mailwatch 1.2.7 and MailScanner 5.0.6, with the aid of the Mailwatch install script.

And alas, no output, event though MailScanner --lint is working fine.

Fixed with `chmod g+rwx /var/spool/MailScanner/incoming/clamav-tmp/`, which works fine until the next reboot.

Rather than messing about with a tmpfiles.d entry for clamav-tmp, there's a much simpler and better solution to this, which is to avoid the clamav-wrapper altogether.

This requires changes to sf_version.php and clamav_status.php:

```#diff -Naur sf_version.php.old sf_version.php
--- sf_version.php.old  2017-12-18 12:45:02.646138998 +0000
+++ sf_version.php      2017-12-18 12:46:45.088075853 +0000
@@ -132,7 +132,10 @@
     // Add test for others virus scanners.
     if (preg_match('/clam/i', $virusScanner)) {
         echo 'ClamAV ' . __('version11') . ' ';
-        passthru(get_virus_conf('clamav') . " -V | cut -d/ -f1 | cut -d' ' -f2");
+        exec("which clamscan", $clamscan);
+        if (isset($clamscan[0])) {
+            passthru("$clamscan[0] -V | cut -d/ -f1 | cut -d' ' -f2");
+        }
         echo '<br>' . "\n";
     }
```

and 

```# diff -Naur clamav_status.php.old clamav_status.php
--- clamav_status.php.old       2017-12-18 12:34:34.672757433 +0000
+++ clamav_status.php   2017-12-19 15:16:27.398311197 +0000
@@ -44,9 +44,10 @@
     echo '<tr>';
     echo '<td align="center">';

-    // Output the information from the conf file
-    passthru(get_virus_conf('clamav') . ' -V | awk -f ' . __DIR__ . '/clamav.awk');
-
+    exec("which clamscan", $clamscan);
+    if (isset($clamscan[0])) {
+        passthru("$clamscan[0] -V | awk -f " . __DIR__ . '/clamav.awk');
+    }
     echo '</td>';
     echo '</tr>';
     echo '</table>';
```

Cheers,

Phil
