### ISSUE TITLE
User not showing on the top panel 

### ISSUE THREAD

**Issue by pztop** [mailwatch/MailWatch#973]
### Issue summary
In the v1.2.6 when user login, it doesn't show the user's name on the top panel (beside the "System Time") . 

### Steps to reproduce
1. Login
2. 
3. 

### Expected result
Show who is login 

### Actual result
empty space showed

### Version and method
 - MailWatch Version: [ stable 1.2.6 ]
 - Install type: [ tarball install ]
 - Updated from an older MailWatch or fresh install: [ Fresh install)

### Server configuration
 - Operation System: [ CentOS 7.4 ]
 - PHP version: [  7.1 ]
 - Database: [  MariaDB ] version [ 5.5.56 ]
 - Mail Server: [ Postfix 3.2.4 ]
 - Used web server: [  Nginx ] version [ 1.13.6 ]

### Client configuration 
 - Operation System: [ Ubuntu 16.04 ]
 - Browser: [ chrome ]

**Comment by Skywalker-11** [comment]
@pztop 
* are there any errors in the nginx log? 
* Is it not working for all users or just some of them? 
* Please also check that the user has set a name not only a login name over the user management page (<yourserver>/user_manager.php).
* What user backend are you using (sql or ldap)?

**Comment by pztop** [comment]
Yeah I forgot to set the full name. Thank you for the quick reply.

**Comment by Skywalker-11** [comment]
@pztop Can you close this then?
