### ISSUE TITLE
Reverse Lookup Failed with 127.0.1.5

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#974]
Hello!

Something seems wrong with geoip code in message detail.

![geoip](https://user-images.githubusercontent.com/12907102/32689202-3d751c78-c6e0-11e7-806e-f45f516e1647.png)

With last MW version.

**Comment by shawniverson** [comment]
Looks like it needs to be modified to treat all loopback addresses as localhost?

**Comment by endelwar** [comment]
I agree, the entire 127.0.0.0/8 block is reserved for loopback as per [RFC 3330](http://www.ietf.org/rfc/rfc3330.txt).

**Comment by endelwar** [comment]
commit f5b90bea1ddd666dce6a06459b0ebfc2f1a8b103 should fix this, can you try it @stefaweb ?

**Comment by stefaweb** [comment]
Ok fine.
