### ISSUE TITLE
mailscanner and openDKIM

### ISSUE THREAD

**Issue by janarzz** [mailwatch/MailWatch#975]
Hey, i have a problem with OpenDKIM.
My mailserver conf:
ubuntu server 16.04+postfix+dovecot+mailscanner+mailwatch+opendkim.
When i tested opendkim, then i get error:
wrong body hash.
Any ideas ?

**Comment by Skywalker-11** [comment]
Can you explain where you get that error and tell us steps to reproduce it?

**Comment by janarzz** [comment]
Hey,
i get this error when i send outgoin mails OpenDKIM test page:
http://www.appmaildev.com/en/dkim

**Comment by Skywalker-11** [comment]
This seems to be a MailScanner issue. Please post it here: https://github.com/mailscanner/v5/issues

MailWatch doesn't modify the mails. That is done by MailScanner.

**Comment by janarzz** [comment]
Hey, thnaks. I posted there.

**Comment by Skywalker-11** [comment]
https://github.com/MailScanner/v5/issues/115

@janarzz Can you close this issue here?
