### ISSUE TITLE
minor html error in lists.php

### ISSUE THREAD

**Issue by pdwalker** [mailwatch/MailWatch#977]
Really minor html error

In lists.php, a <TD> tag is improperly closed, creating an unnecessary, empty table column in function build_table().

The problem exists in the [current version of the code](https://github.com/mailwatch/MailWatch/blame/master/mailscanner/lists.php) as of the time of this message

The line:
`$table_html .= '  <td><a href="lists.php?token=' . $_SESSION['token'] . '&amp;submit=delete&amp;listid=' . $row[0] . '&amp;to=' . $row[2] . '&amp;list=' . $list . '">' . __('delete07') . '</a><td>' . "\n";`

Should be:
`$table_html .= '  <td><a href="lists.php?token=' . $_SESSION['token'] . '&amp;submit=delete&amp;listid=' . $row[0] . '&amp;to=' . $row[2] . '&amp;list=' . $list . '">' . __('delete07') . '</a></td>' . "\n";`

Look for the last "td>" on the line to see the correction.

**Comment by Skywalker-11** [comment]
Should be fixed
