### ISSUE TITLE
MailWatch apache conf

### ISSUE THREAD

**Issue by janarzz** [mailwatch/MailWatch#988]
Hey,
can you tell me, how i find secure MailWatch apache configuration ?

**Comment by xpufx** [comment]
What do you mean? Secure in what way, and how?

**Comment by janarzz** [comment]
Hey, i mean secure mailwatch apache..example turn on Options - Indexes or smth...

**Comment by Skywalker-11** [comment]
With MailWatch 1.2.7 we have included .htaccess files to restrict indexes and folder access: https://github.com/mailwatch/mailwatch-docs/blob/develop/_posts/2014-07-31-faq.md (near bottom of the page)

That are MW specific settings. Everything else is about securing apache in general and you can find many tutorials for that in the web (ssl, hsts, logging, etc.)

**Comment by asuweb** [comment]
@janarzz - is this still an issue or can it be closed?

**Comment by janarzz** [comment]
Hey, you can close this issue.
