### ISSUE TITLE
Add Japanese to USER_SELECTABLE_LANG

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#993]
Hello @endelwar!

Following PR of Japanese langage in dev (https://github.com/mailwatch/MailWatch/commit/36bbb070f09e9eb3ffffaccc2888043beb1d6ec0), I got this.

![sc1](https://user-images.githubusercontent.com/12907102/33386445-3d508936-d52b-11e7-8436-97e6f1d0cd2c.png)

![sc2](https://user-images.githubusercontent.com/12907102/33386454-42f83ec4-d52b-11e7-9a1f-fed8e7d2b001.png)

My conf.php:

define('LANG', 'fr');
define('USER_SELECTABLE_LANG', 'de,en,fr,it,ja,nl,pt_br');

**Comment by Skywalker-11** [comment]
There is no japanese https://github.com/mailwatch/MailWatch/tree/master/mailscanner/languages
To add an additional language 
* create the translation file that language eg `mailscanner/languages/ja.php` 
* add `'ja' => 'Japanese'` to each of the existing lang files
* add it to the USER_SELECTABLE_LANG

**Comment by stefaweb** [comment]
We know have it. @endelwar pushed it.

https://github.com/mailwatch/MailWatch/tree/develop/mailscanner/languages

**Comment by Skywalker-11** [comment]
de translation for `'ja' => 'Japanese'` is `'ja' => 'Japanisch'`

**Comment by stefaweb** [comment]
fr translation for 'ja' => 'Japanese' is 'ja' => 'Japonais'

**Comment by Skywalker-11** [comment]
@stefaweb if you provide fr translation I can make the pr

**Comment by Skywalker-11** [comment]
On second thought ther is no need for translation there as we use the languages name in its own. 
Shall we also use the japanese characters or keep it in latin chars `Japanese`.

**Comment by endelwar** [comment]
ooops! never push after 23:00 ;)
Japanese in japanese is 日本語
